# Generated by Django 5.1.4 on 2025-06-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SSHUser',
            new_name='Host_User',
        ),
    ]
