# Generated by Django 5.1.4 on 2025-06-07 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_rename_sshuser_host_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host_type',
            options={'ordering': ['-id']},
        ),
        migrations.AlterUniqueTogether(
            name='host_user',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='host',
            table='Host',
        ),
        migrations.AlterModelTable(
            name='host_type',
            table='Host_type',
        ),
        migrations.AlterModelTable(
            name='host_user',
            table='Host_User',
        ),
    ]
