# Generated by Django 5.1.4 on 2025-06-07 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_alter_host_type_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='host',
            table='assets_host',
        ),
        migrations.AlterModelTable(
            name='host_type',
            table='assets_host_type',
        ),
        migrations.AlterModelTable(
            name='host_user',
            table='assets_host_User',
        ),
    ]
