// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: agent_channel.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// backend -> agent
type ServerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerFrame_HelloAck
	//	*ServerFrame_ListRequest
	//	*ServerFrame_StatRequest
	//	*ServerFrame_ReadRequest
	//	*ServerFrame_WriteOpenRequest
	//	*ServerFrame_WriteChunkRequest
	//	*ServerFrame_WriteCloseRequest
	//	*ServerFrame_RenameRequest
	//	*ServerFrame_DeleteRequest
	//	*ServerFrame_MkdirRequest
	//	*ServerFrame_CreateFileRequest
	//	*ServerFrame_TerminalOpenRequest
	//	*ServerFrame_TerminalDataRequest
	//	*ServerFrame_TerminalResizeRequest
	//	*ServerFrame_TerminalCloseRequest
	//	*ServerFrame_AutomationExecuteRequest
	Payload       isServerFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_agent_channel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{0}
}

func (x *ServerFrame) GetPayload() isServerFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerFrame) GetHelloAck() *HelloAck {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_HelloAck); ok {
			return x.HelloAck
		}
	}
	return nil
}

func (x *ServerFrame) GetListRequest() *ListRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_ListRequest); ok {
			return x.ListRequest
		}
	}
	return nil
}

func (x *ServerFrame) GetStatRequest() *StatRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_StatRequest); ok {
			return x.StatRequest
		}
	}
	return nil
}

func (x *ServerFrame) GetReadRequest() *ReadRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_ReadRequest); ok {
			return x.ReadRequest
		}
	}
	return nil
}

func (x *ServerFrame) GetWriteOpenRequest() *WriteOpenRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_WriteOpenRequest); ok {
			return x.WriteOpenRequest
		}
	}
	return nil
}

func (x *ServerFrame) GetWriteChunkRequest() *WriteChunkRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_WriteChunkRequest); ok {
			return x.WriteChunkRequest
		}
	}
	return nil
}

func (x *ServerFrame) GetWriteCloseRequest() *WriteCloseRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_WriteCloseRequest); ok {
			return x.WriteCloseRequest
		}
	}
	return nil
}

func (x *ServerFrame) GetRenameRequest() *RenameRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_RenameRequest); ok {
			return x.RenameRequest
		}
	}
	return nil
}

func (x *ServerFrame) GetDeleteRequest() *DeleteRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_DeleteRequest); ok {
			return x.DeleteRequest
		}
	}
	return nil
}

func (x *ServerFrame) GetMkdirRequest() *MkdirRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_MkdirRequest); ok {
			return x.MkdirRequest
		}
	}
	return nil
}

func (x *ServerFrame) GetCreateFileRequest() *CreateFileRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_CreateFileRequest); ok {
			return x.CreateFileRequest
		}
	}
	return nil
}

func (x *ServerFrame) GetTerminalOpenRequest() *TerminalOpenRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_TerminalOpenRequest); ok {
			return x.TerminalOpenRequest
		}
	}
	return nil
}

func (x *ServerFrame) GetTerminalDataRequest() *TerminalDataRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_TerminalDataRequest); ok {
			return x.TerminalDataRequest
		}
	}
	return nil
}

func (x *ServerFrame) GetTerminalResizeRequest() *TerminalResizeRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_TerminalResizeRequest); ok {
			return x.TerminalResizeRequest
		}
	}
	return nil
}

func (x *ServerFrame) GetTerminalCloseRequest() *TerminalCloseRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_TerminalCloseRequest); ok {
			return x.TerminalCloseRequest
		}
	}
	return nil
}

func (x *ServerFrame) GetAutomationExecuteRequest() *AutomationExecuteRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerFrame_AutomationExecuteRequest); ok {
			return x.AutomationExecuteRequest
		}
	}
	return nil
}

type isServerFrame_Payload interface {
	isServerFrame_Payload()
}

type ServerFrame_HelloAck struct {
	HelloAck *HelloAck `protobuf:"bytes,1,opt,name=hello_ack,json=helloAck,proto3,oneof"`
}

type ServerFrame_ListRequest struct {
	ListRequest *ListRequest `protobuf:"bytes,2,opt,name=list_request,json=listRequest,proto3,oneof"`
}

type ServerFrame_StatRequest struct {
	StatRequest *StatRequest `protobuf:"bytes,3,opt,name=stat_request,json=statRequest,proto3,oneof"`
}

type ServerFrame_ReadRequest struct {
	ReadRequest *ReadRequest `protobuf:"bytes,4,opt,name=read_request,json=readRequest,proto3,oneof"`
}

type ServerFrame_WriteOpenRequest struct {
	WriteOpenRequest *WriteOpenRequest `protobuf:"bytes,5,opt,name=write_open_request,json=writeOpenRequest,proto3,oneof"`
}

type ServerFrame_WriteChunkRequest struct {
	WriteChunkRequest *WriteChunkRequest `protobuf:"bytes,6,opt,name=write_chunk_request,json=writeChunkRequest,proto3,oneof"`
}

type ServerFrame_WriteCloseRequest struct {
	WriteCloseRequest *WriteCloseRequest `protobuf:"bytes,7,opt,name=write_close_request,json=writeCloseRequest,proto3,oneof"`
}

type ServerFrame_RenameRequest struct {
	RenameRequest *RenameRequest `protobuf:"bytes,8,opt,name=rename_request,json=renameRequest,proto3,oneof"`
}

type ServerFrame_DeleteRequest struct {
	DeleteRequest *DeleteRequest `protobuf:"bytes,9,opt,name=delete_request,json=deleteRequest,proto3,oneof"`
}

type ServerFrame_MkdirRequest struct {
	MkdirRequest *MkdirRequest `protobuf:"bytes,10,opt,name=mkdir_request,json=mkdirRequest,proto3,oneof"`
}

type ServerFrame_CreateFileRequest struct {
	CreateFileRequest *CreateFileRequest `protobuf:"bytes,11,opt,name=create_file_request,json=createFileRequest,proto3,oneof"`
}

type ServerFrame_TerminalOpenRequest struct {
	// WebSSH 终端（在同一条 agent 长连接上以 request_id 区分不同终端会话，
	// 不再为每个终端会话单独建一条 gRPC 连接——agent 是拨出方，backend 无法主动发起新连接）。
	TerminalOpenRequest *TerminalOpenRequest `protobuf:"bytes,12,opt,name=terminal_open_request,json=terminalOpenRequest,proto3,oneof"`
}

type ServerFrame_TerminalDataRequest struct {
	TerminalDataRequest *TerminalDataRequest `protobuf:"bytes,13,opt,name=terminal_data_request,json=terminalDataRequest,proto3,oneof"` // backend -> agent 的 stdin
}

type ServerFrame_TerminalResizeRequest struct {
	TerminalResizeRequest *TerminalResizeRequest `protobuf:"bytes,14,opt,name=terminal_resize_request,json=terminalResizeRequest,proto3,oneof"`
}

type ServerFrame_TerminalCloseRequest struct {
	TerminalCloseRequest *TerminalCloseRequest `protobuf:"bytes,15,opt,name=terminal_close_request,json=terminalCloseRequest,proto3,oneof"`
}

type ServerFrame_AutomationExecuteRequest struct {
	// 自动化/workflow 实时任务：复用同一条 agent 长连接下发 playbook/shell 执行命令，
	// agent 本地降权执行后回传一次 automation_execute_response（以 request_id 关联）。
	// 取代旧的 backend 直连 host.ip:19090 HTTP 执行路径。
	AutomationExecuteRequest *AutomationExecuteRequest `protobuf:"bytes,16,opt,name=automation_execute_request,json=automationExecuteRequest,proto3,oneof"`
}

func (*ServerFrame_HelloAck) isServerFrame_Payload() {}

func (*ServerFrame_ListRequest) isServerFrame_Payload() {}

func (*ServerFrame_StatRequest) isServerFrame_Payload() {}

func (*ServerFrame_ReadRequest) isServerFrame_Payload() {}

func (*ServerFrame_WriteOpenRequest) isServerFrame_Payload() {}

func (*ServerFrame_WriteChunkRequest) isServerFrame_Payload() {}

func (*ServerFrame_WriteCloseRequest) isServerFrame_Payload() {}

func (*ServerFrame_RenameRequest) isServerFrame_Payload() {}

func (*ServerFrame_DeleteRequest) isServerFrame_Payload() {}

func (*ServerFrame_MkdirRequest) isServerFrame_Payload() {}

func (*ServerFrame_CreateFileRequest) isServerFrame_Payload() {}

func (*ServerFrame_TerminalOpenRequest) isServerFrame_Payload() {}

func (*ServerFrame_TerminalDataRequest) isServerFrame_Payload() {}

func (*ServerFrame_TerminalResizeRequest) isServerFrame_Payload() {}

func (*ServerFrame_TerminalCloseRequest) isServerFrame_Payload() {}

func (*ServerFrame_AutomationExecuteRequest) isServerFrame_Payload() {}

// agent -> backend
type AgentFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentFrame_Hello
	//	*AgentFrame_ListResponse
	//	*AgentFrame_StatResponse
	//	*AgentFrame_ReadChunk
	//	*AgentFrame_WriteOpenResponse
	//	*AgentFrame_WriteChunkAck
	//	*AgentFrame_WriteCloseResponse
	//	*AgentFrame_RenameResponse
	//	*AgentFrame_DeleteResponse
	//	*AgentFrame_MkdirResponse
	//	*AgentFrame_CreateFileResponse
	//	*AgentFrame_TerminalOpenResponse
	//	*AgentFrame_TerminalDataResponse
	//	*AgentFrame_TerminalExitResponse
	//	*AgentFrame_AutomationExecuteResponse
	Payload       isAgentFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentFrame) Reset() {
	*x = AgentFrame{}
	mi := &file_agent_channel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentFrame) ProtoMessage() {}

func (x *AgentFrame) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentFrame.ProtoReflect.Descriptor instead.
func (*AgentFrame) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{1}
}

func (x *AgentFrame) GetPayload() isAgentFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentFrame) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*AgentFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentFrame) GetListResponse() *ListResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentFrame_ListResponse); ok {
			return x.ListResponse
		}
	}
	return nil
}

func (x *AgentFrame) GetStatResponse() *StatResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentFrame_StatResponse); ok {
			return x.StatResponse
		}
	}
	return nil
}

func (x *AgentFrame) GetReadChunk() *ReadChunk {
	if x != nil {
		if x, ok := x.Payload.(*AgentFrame_ReadChunk); ok {
			return x.ReadChunk
		}
	}
	return nil
}

func (x *AgentFrame) GetWriteOpenResponse() *WriteOpenResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentFrame_WriteOpenResponse); ok {
			return x.WriteOpenResponse
		}
	}
	return nil
}

func (x *AgentFrame) GetWriteChunkAck() *WriteChunkAck {
	if x != nil {
		if x, ok := x.Payload.(*AgentFrame_WriteChunkAck); ok {
			return x.WriteChunkAck
		}
	}
	return nil
}

func (x *AgentFrame) GetWriteCloseResponse() *WriteCloseResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentFrame_WriteCloseResponse); ok {
			return x.WriteCloseResponse
		}
	}
	return nil
}

func (x *AgentFrame) GetRenameResponse() *RenameResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentFrame_RenameResponse); ok {
			return x.RenameResponse
		}
	}
	return nil
}

func (x *AgentFrame) GetDeleteResponse() *DeleteResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentFrame_DeleteResponse); ok {
			return x.DeleteResponse
		}
	}
	return nil
}

func (x *AgentFrame) GetMkdirResponse() *MkdirResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentFrame_MkdirResponse); ok {
			return x.MkdirResponse
		}
	}
	return nil
}

func (x *AgentFrame) GetCreateFileResponse() *CreateFileResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentFrame_CreateFileResponse); ok {
			return x.CreateFileResponse
		}
	}
	return nil
}

func (x *AgentFrame) GetTerminalOpenResponse() *TerminalOpenResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentFrame_TerminalOpenResponse); ok {
			return x.TerminalOpenResponse
		}
	}
	return nil
}

func (x *AgentFrame) GetTerminalDataResponse() *TerminalDataResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentFrame_TerminalDataResponse); ok {
			return x.TerminalDataResponse
		}
	}
	return nil
}

func (x *AgentFrame) GetTerminalExitResponse() *TerminalExitResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentFrame_TerminalExitResponse); ok {
			return x.TerminalExitResponse
		}
	}
	return nil
}

func (x *AgentFrame) GetAutomationExecuteResponse() *AutomationExecuteResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentFrame_AutomationExecuteResponse); ok {
			return x.AutomationExecuteResponse
		}
	}
	return nil
}

type isAgentFrame_Payload interface {
	isAgentFrame_Payload()
}

type AgentFrame_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentFrame_ListResponse struct {
	ListResponse *ListResponse `protobuf:"bytes,2,opt,name=list_response,json=listResponse,proto3,oneof"`
}

type AgentFrame_StatResponse struct {
	StatResponse *StatResponse `protobuf:"bytes,3,opt,name=stat_response,json=statResponse,proto3,oneof"`
}

type AgentFrame_ReadChunk struct {
	ReadChunk *ReadChunk `protobuf:"bytes,4,opt,name=read_chunk,json=readChunk,proto3,oneof"`
}

type AgentFrame_WriteOpenResponse struct {
	WriteOpenResponse *WriteOpenResponse `protobuf:"bytes,5,opt,name=write_open_response,json=writeOpenResponse,proto3,oneof"`
}

type AgentFrame_WriteChunkAck struct {
	WriteChunkAck *WriteChunkAck `protobuf:"bytes,6,opt,name=write_chunk_ack,json=writeChunkAck,proto3,oneof"`
}

type AgentFrame_WriteCloseResponse struct {
	WriteCloseResponse *WriteCloseResponse `protobuf:"bytes,7,opt,name=write_close_response,json=writeCloseResponse,proto3,oneof"`
}

type AgentFrame_RenameResponse struct {
	RenameResponse *RenameResponse `protobuf:"bytes,8,opt,name=rename_response,json=renameResponse,proto3,oneof"`
}

type AgentFrame_DeleteResponse struct {
	DeleteResponse *DeleteResponse `protobuf:"bytes,9,opt,name=delete_response,json=deleteResponse,proto3,oneof"`
}

type AgentFrame_MkdirResponse struct {
	MkdirResponse *MkdirResponse `protobuf:"bytes,10,opt,name=mkdir_response,json=mkdirResponse,proto3,oneof"`
}

type AgentFrame_CreateFileResponse struct {
	CreateFileResponse *CreateFileResponse `protobuf:"bytes,11,opt,name=create_file_response,json=createFileResponse,proto3,oneof"`
}

type AgentFrame_TerminalOpenResponse struct {
	TerminalOpenResponse *TerminalOpenResponse `protobuf:"bytes,12,opt,name=terminal_open_response,json=terminalOpenResponse,proto3,oneof"`
}

type AgentFrame_TerminalDataResponse struct {
	TerminalDataResponse *TerminalDataResponse `protobuf:"bytes,13,opt,name=terminal_data_response,json=terminalDataResponse,proto3,oneof"` // agent -> backend 的 stdout/stderr（PTY 已合并两者）
}

type AgentFrame_TerminalExitResponse struct {
	TerminalExitResponse *TerminalExitResponse `protobuf:"bytes,14,opt,name=terminal_exit_response,json=terminalExitResponse,proto3,oneof"` // shell 进程退出
}

type AgentFrame_AutomationExecuteResponse struct {
	AutomationExecuteResponse *AutomationExecuteResponse `protobuf:"bytes,15,opt,name=automation_execute_response,json=automationExecuteResponse,proto3,oneof"` // 自动化/workflow 任务执行结果
}

func (*AgentFrame_Hello) isAgentFrame_Payload() {}

func (*AgentFrame_ListResponse) isAgentFrame_Payload() {}

func (*AgentFrame_StatResponse) isAgentFrame_Payload() {}

func (*AgentFrame_ReadChunk) isAgentFrame_Payload() {}

func (*AgentFrame_WriteOpenResponse) isAgentFrame_Payload() {}

func (*AgentFrame_WriteChunkAck) isAgentFrame_Payload() {}

func (*AgentFrame_WriteCloseResponse) isAgentFrame_Payload() {}

func (*AgentFrame_RenameResponse) isAgentFrame_Payload() {}

func (*AgentFrame_DeleteResponse) isAgentFrame_Payload() {}

func (*AgentFrame_MkdirResponse) isAgentFrame_Payload() {}

func (*AgentFrame_CreateFileResponse) isAgentFrame_Payload() {}

func (*AgentFrame_TerminalOpenResponse) isAgentFrame_Payload() {}

func (*AgentFrame_TerminalDataResponse) isAgentFrame_Payload() {}

func (*AgentFrame_TerminalExitResponse) isAgentFrame_Payload() {}

func (*AgentFrame_AutomationExecuteResponse) isAgentFrame_Payload() {}

// 会话建立后 agent 发送的第一帧：携带 agent_id 与共享密钥供 backend 校验注册，
// 校验失败 backend 会直接关闭流，避免未授权 client 冒充 agent 下发文件操作。
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_agent_channel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Hello) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type HelloAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_agent_channel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{3}
}

func (x *HelloAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *HelloAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Mode          uint32                 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	IsDir         bool                   `protobuf:"varint,4,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Mtime         int64                  `protobuf:"varint,5,opt,name=mtime,proto3" json:"mtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_agent_channel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{4}
}

func (x *FileEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileEntry) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileEntry) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_agent_channel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{5}
}

func (x *ListRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ListRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	CurrentPath   string                 `protobuf:"bytes,2,opt,name=current_path,json=currentPath,proto3" json:"current_path,omitempty"`
	Entries       []*FileEntry           `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_agent_channel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{6}
}

func (x *ListResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ListResponse) GetCurrentPath() string {
	if x != nil {
		return x.CurrentPath
	}
	return ""
}

func (x *ListResponse) GetEntries() []*FileEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_agent_channel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{7}
}

func (x *StatRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StatRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StatResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	NormalizedPath string                 `protobuf:"bytes,2,opt,name=normalized_path,json=normalizedPath,proto3" json:"normalized_path,omitempty"`
	Size           int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Mode           uint32                 `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	IsDir          bool                   `protobuf:"varint,5,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Mtime          int64                  `protobuf:"varint,6,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Error          string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_agent_channel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{8}
}

func (x *StatResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StatResponse) GetNormalizedPath() string {
	if x != nil {
		return x.NormalizedPath
	}
	return ""
}

func (x *StatResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StatResponse) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *StatResponse) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *StatResponse) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *StatResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// offset/length 用于支持 Range 断点下载；length<=0 表示读到文件末尾。
type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        int64                  `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_agent_channel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{9}
}

func (x *ReadRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ReadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReadRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadRequest) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type ReadChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Eof           bool                   `protobuf:"varint,3,opt,name=eof,proto3" json:"eof,omitempty"`
	FileSize      int64                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadChunk) Reset() {
	*x = ReadChunk{}
	mi := &file_agent_channel_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChunk) ProtoMessage() {}

func (x *ReadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChunk.ProtoReflect.Descriptor instead.
func (*ReadChunk) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{10}
}

func (x *ReadChunk) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ReadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReadChunk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

func (x *ReadChunk) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *ReadChunk) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WriteOpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	DirPath       string                 `protobuf:"bytes,2,opt,name=dir_path,json=dirPath,proto3" json:"dir_path,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteOpenRequest) Reset() {
	*x = WriteOpenRequest{}
	mi := &file_agent_channel_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteOpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteOpenRequest) ProtoMessage() {}

func (x *WriteOpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteOpenRequest.ProtoReflect.Descriptor instead.
func (*WriteOpenRequest) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{11}
}

func (x *WriteOpenRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WriteOpenRequest) GetDirPath() string {
	if x != nil {
		return x.DirPath
	}
	return ""
}

func (x *WriteOpenRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type WriteOpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteOpenResponse) Reset() {
	*x = WriteOpenResponse{}
	mi := &file_agent_channel_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteOpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteOpenResponse) ProtoMessage() {}

func (x *WriteOpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteOpenResponse.ProtoReflect.Descriptor instead.
func (*WriteOpenResponse) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{12}
}

func (x *WriteOpenResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WriteOpenResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WriteChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteChunkRequest) Reset() {
	*x = WriteChunkRequest{}
	mi := &file_agent_channel_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteChunkRequest) ProtoMessage() {}

func (x *WriteChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteChunkRequest.ProtoReflect.Descriptor instead.
func (*WriteChunkRequest) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{13}
}

func (x *WriteChunkRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WriteChunkRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteChunkAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	BytesWritten  int64                  `protobuf:"varint,2,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteChunkAck) Reset() {
	*x = WriteChunkAck{}
	mi := &file_agent_channel_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteChunkAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteChunkAck) ProtoMessage() {}

func (x *WriteChunkAck) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteChunkAck.ProtoReflect.Descriptor instead.
func (*WriteChunkAck) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{14}
}

func (x *WriteChunkAck) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WriteChunkAck) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

func (x *WriteChunkAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// abort=true 表示上传中途失败/取消，agent 侧需要清理临时文件、不做原子 rename。
type WriteCloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Abort         bool                   `protobuf:"varint,2,opt,name=abort,proto3" json:"abort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteCloseRequest) Reset() {
	*x = WriteCloseRequest{}
	mi := &file_agent_channel_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteCloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteCloseRequest) ProtoMessage() {}

func (x *WriteCloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteCloseRequest.ProtoReflect.Descriptor instead.
func (*WriteCloseRequest) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{15}
}

func (x *WriteCloseRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WriteCloseRequest) GetAbort() bool {
	if x != nil {
		return x.Abort
	}
	return false
}

type WriteCloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	TotalBytes    int64                  `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteCloseResponse) Reset() {
	*x = WriteCloseResponse{}
	mi := &file_agent_channel_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteCloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteCloseResponse) ProtoMessage() {}

func (x *WriteCloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteCloseResponse.ProtoReflect.Descriptor instead.
func (*WriteCloseResponse) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{16}
}

func (x *WriteCloseResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WriteCloseResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteCloseResponse) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *WriteCloseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RenameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	NewName       string                 `protobuf:"bytes,3,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameRequest) Reset() {
	*x = RenameRequest{}
	mi := &file_agent_channel_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameRequest) ProtoMessage() {}

func (x *RenameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameRequest.ProtoReflect.Descriptor instead.
func (*RenameRequest) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{17}
}

func (x *RenameRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RenameRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RenameRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type RenameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameResponse) Reset() {
	*x = RenameResponse{}
	mi := &file_agent_channel_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameResponse) ProtoMessage() {}

func (x *RenameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameResponse.ProtoReflect.Descriptor instead.
func (*RenameResponse) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{18}
}

func (x *RenameResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RenameResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RenameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RenameResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Recursive     bool                   `protobuf:"varint,3,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_agent_channel_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DeleteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DeleteRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_agent_channel_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DeleteResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DeleteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MkdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirRequest) Reset() {
	*x = MkdirRequest{}
	mi := &file_agent_channel_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirRequest) ProtoMessage() {}

func (x *MkdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirRequest.ProtoReflect.Descriptor instead.
func (*MkdirRequest) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{21}
}

func (x *MkdirRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MkdirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MkdirRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MkdirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirResponse) Reset() {
	*x = MkdirResponse{}
	mi := &file_agent_channel_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirResponse) ProtoMessage() {}

func (x *MkdirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirResponse.ProtoReflect.Descriptor instead.
func (*MkdirResponse) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{22}
}

func (x *MkdirResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MkdirResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MkdirResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MkdirResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileRequest) Reset() {
	*x = CreateFileRequest{}
	mi := &file_agent_channel_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileRequest) ProtoMessage() {}

func (x *CreateFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileRequest.ProtoReflect.Descriptor instead.
func (*CreateFileRequest) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{23}
}

func (x *CreateFileRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CreateFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateFileRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileResponse) Reset() {
	*x = CreateFileResponse{}
	mi := &file_agent_channel_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileResponse) ProtoMessage() {}

func (x *CreateFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileResponse.ProtoReflect.Descriptor instead.
func (*CreateFileResponse) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{24}
}

func (x *CreateFileResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CreateFileResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateFileResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// WebSSH 终端：一个 request_id 代表一个终端会话（一个 PTY 进程），open 之后
// backend 可持续发送 terminal_data_request（stdin）/terminal_resize_request，
// agent 持续回传 terminal_data_response（stdout，PTY 下 stdout/stderr 已合并），
// 进程退出时回传一次 terminal_exit_response 结束该 request_id 的生命周期。
type TerminalOpenRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Cols      uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows      uint32                 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	// 目标登录用户：为空时使用 agent 进程当前用户；非空时由 agent 尝试切换用户后再打开 shell。
	TargetUser    string `protobuf:"bytes,4,opt,name=target_user,json=targetUser,proto3" json:"target_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalOpenRequest) Reset() {
	*x = TerminalOpenRequest{}
	mi := &file_agent_channel_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalOpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalOpenRequest) ProtoMessage() {}

func (x *TerminalOpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalOpenRequest.ProtoReflect.Descriptor instead.
func (*TerminalOpenRequest) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{25}
}

func (x *TerminalOpenRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TerminalOpenRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *TerminalOpenRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *TerminalOpenRequest) GetTargetUser() string {
	if x != nil {
		return x.TargetUser
	}
	return ""
}

type TerminalOpenResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Error     string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// 实际生效的系统用户名（用于审计与前端展示）。
	EffectiveUser string `protobuf:"bytes,3,opt,name=effective_user,json=effectiveUser,proto3" json:"effective_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalOpenResponse) Reset() {
	*x = TerminalOpenResponse{}
	mi := &file_agent_channel_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalOpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalOpenResponse) ProtoMessage() {}

func (x *TerminalOpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalOpenResponse.ProtoReflect.Descriptor instead.
func (*TerminalOpenResponse) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{26}
}

func (x *TerminalOpenResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TerminalOpenResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TerminalOpenResponse) GetEffectiveUser() string {
	if x != nil {
		return x.EffectiveUser
	}
	return ""
}

type TerminalDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalDataRequest) Reset() {
	*x = TerminalDataRequest{}
	mi := &file_agent_channel_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalDataRequest) ProtoMessage() {}

func (x *TerminalDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalDataRequest.ProtoReflect.Descriptor instead.
func (*TerminalDataRequest) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{27}
}

func (x *TerminalDataRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TerminalDataRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TerminalDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalDataResponse) Reset() {
	*x = TerminalDataResponse{}
	mi := &file_agent_channel_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalDataResponse) ProtoMessage() {}

func (x *TerminalDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalDataResponse.ProtoReflect.Descriptor instead.
func (*TerminalDataResponse) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{28}
}

func (x *TerminalDataResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TerminalDataResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TerminalResizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalResizeRequest) Reset() {
	*x = TerminalResizeRequest{}
	mi := &file_agent_channel_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalResizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalResizeRequest) ProtoMessage() {}

func (x *TerminalResizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalResizeRequest.ProtoReflect.Descriptor instead.
func (*TerminalResizeRequest) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{29}
}

func (x *TerminalResizeRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TerminalResizeRequest) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *TerminalResizeRequest) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type TerminalCloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalCloseRequest) Reset() {
	*x = TerminalCloseRequest{}
	mi := &file_agent_channel_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalCloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalCloseRequest) ProtoMessage() {}

func (x *TerminalCloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalCloseRequest.ProtoReflect.Descriptor instead.
func (*TerminalCloseRequest) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{30}
}

func (x *TerminalCloseRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type TerminalExitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalExitResponse) Reset() {
	*x = TerminalExitResponse{}
	mi := &file_agent_channel_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalExitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalExitResponse) ProtoMessage() {}

func (x *TerminalExitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalExitResponse.ProtoReflect.Descriptor instead.
func (*TerminalExitResponse) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{31}
}

func (x *TerminalExitResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TerminalExitResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *TerminalExitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 自动化/workflow 实时任务：backend 把一台主机的 playbook/shell 执行请求下发给 agent。
// params_json 为 JSON 编码的参数对象（含 template_type/template_content/env_vars/extra_vars/
// run_as_user/run_as_group/work_dir 等嵌套结构），不用 map<string,string> 以免丢失嵌套信息。
type AutomationExecuteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	JobId          string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`                                            // 任务类型，典型为 "custom"
	Action         string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`                                        // 固定为 "run_automation_task"
	ParamsJson     string                 `protobuf:"bytes,5,opt,name=params_json,json=paramsJson,proto3" json:"params_json,omitempty"`              // JSON 编码的 params
	TimeoutSeconds int32                  `protobuf:"varint,6,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // 执行超时（秒）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AutomationExecuteRequest) Reset() {
	*x = AutomationExecuteRequest{}
	mi := &file_agent_channel_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutomationExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutomationExecuteRequest) ProtoMessage() {}

func (x *AutomationExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutomationExecuteRequest.ProtoReflect.Descriptor instead.
func (*AutomationExecuteRequest) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{32}
}

func (x *AutomationExecuteRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AutomationExecuteRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AutomationExecuteRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AutomationExecuteRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AutomationExecuteRequest) GetParamsJson() string {
	if x != nil {
		return x.ParamsJson
	}
	return ""
}

func (x *AutomationExecuteRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type AutomationExecuteResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	JobId          string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // success/failed/timeout/canceled
	ExitCode       int32                  `protobuf:"varint,4,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout         string                 `protobuf:"bytes,5,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr         string                 `protobuf:"bytes,6,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ResultDataJson string                 `protobuf:"bytes,7,opt,name=result_data_json,json=resultDataJson,proto3" json:"result_data_json,omitempty"` // JSON 编码的结构化结果
	ErrorMessage   string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CostMs         int64                  `protobuf:"varint,9,opt,name=cost_ms,json=costMs,proto3" json:"cost_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AutomationExecuteResponse) Reset() {
	*x = AutomationExecuteResponse{}
	mi := &file_agent_channel_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutomationExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutomationExecuteResponse) ProtoMessage() {}

func (x *AutomationExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_channel_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutomationExecuteResponse.ProtoReflect.Descriptor instead.
func (*AutomationExecuteResponse) Descriptor() ([]byte, []int) {
	return file_agent_channel_proto_rawDescGZIP(), []int{33}
}

func (x *AutomationExecuteResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AutomationExecuteResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AutomationExecuteResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AutomationExecuteResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *AutomationExecuteResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *AutomationExecuteResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *AutomationExecuteResponse) GetResultDataJson() string {
	if x != nil {
		return x.ResultDataJson
	}
	return ""
}

func (x *AutomationExecuteResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *AutomationExecuteResponse) GetCostMs() int64 {
	if x != nil {
		return x.CostMs
	}
	return 0
}

var File_agent_channel_proto protoreflect.FileDescriptor

const file_agent_channel_proto_rawDesc = "" +
	"\n" +
	"\x13agent_channel.proto\x12\x10djadmin.agent.v1\"\xbc\n" +
	"\n" +
	"\vServerFrame\x129\n" +
	"\thello_ack\x18\x01 \x01(\v2\x1a.djadmin.agent.v1.HelloAckH\x00R\bhelloAck\x12B\n" +
	"\flist_request\x18\x02 \x01(\v2\x1d.djadmin.agent.v1.ListRequestH\x00R\vlistRequest\x12B\n" +
	"\fstat_request\x18\x03 \x01(\v2\x1d.djadmin.agent.v1.StatRequestH\x00R\vstatRequest\x12B\n" +
	"\fread_request\x18\x04 \x01(\v2\x1d.djadmin.agent.v1.ReadRequestH\x00R\vreadRequest\x12R\n" +
	"\x12write_open_request\x18\x05 \x01(\v2\".djadmin.agent.v1.WriteOpenRequestH\x00R\x10writeOpenRequest\x12U\n" +
	"\x13write_chunk_request\x18\x06 \x01(\v2#.djadmin.agent.v1.WriteChunkRequestH\x00R\x11writeChunkRequest\x12U\n" +
	"\x13write_close_request\x18\a \x01(\v2#.djadmin.agent.v1.WriteCloseRequestH\x00R\x11writeCloseRequest\x12H\n" +
	"\x0erename_request\x18\b \x01(\v2\x1f.djadmin.agent.v1.RenameRequestH\x00R\rrenameRequest\x12H\n" +
	"\x0edelete_request\x18\t \x01(\v2\x1f.djadmin.agent.v1.DeleteRequestH\x00R\rdeleteRequest\x12E\n" +
	"\rmkdir_request\x18\n" +
	" \x01(\v2\x1e.djadmin.agent.v1.MkdirRequestH\x00R\fmkdirRequest\x12U\n" +
	"\x13create_file_request\x18\v \x01(\v2#.djadmin.agent.v1.CreateFileRequestH\x00R\x11createFileRequest\x12[\n" +
	"\x15terminal_open_request\x18\f \x01(\v2%.djadmin.agent.v1.TerminalOpenRequestH\x00R\x13terminalOpenRequest\x12[\n" +
	"\x15terminal_data_request\x18\r \x01(\v2%.djadmin.agent.v1.TerminalDataRequestH\x00R\x13terminalDataRequest\x12a\n" +
	"\x17terminal_resize_request\x18\x0e \x01(\v2'.djadmin.agent.v1.TerminalResizeRequestH\x00R\x15terminalResizeRequest\x12^\n" +
	"\x16terminal_close_request\x18\x0f \x01(\v2&.djadmin.agent.v1.TerminalCloseRequestH\x00R\x14terminalCloseRequest\x12j\n" +
	"\x1aautomation_execute_request\x18\x10 \x01(\v2*.djadmin.agent.v1.AutomationExecuteRequestH\x00R\x18automationExecuteRequestB\t\n" +
	"\apayload\"\xdd\t\n" +
	"\n" +
	"AgentFrame\x12/\n" +
	"\x05hello\x18\x01 \x01(\v2\x17.djadmin.agent.v1.HelloH\x00R\x05hello\x12E\n" +
	"\rlist_response\x18\x02 \x01(\v2\x1e.djadmin.agent.v1.ListResponseH\x00R\flistResponse\x12E\n" +
	"\rstat_response\x18\x03 \x01(\v2\x1e.djadmin.agent.v1.StatResponseH\x00R\fstatResponse\x12<\n" +
	"\n" +
	"read_chunk\x18\x04 \x01(\v2\x1b.djadmin.agent.v1.ReadChunkH\x00R\treadChunk\x12U\n" +
	"\x13write_open_response\x18\x05 \x01(\v2#.djadmin.agent.v1.WriteOpenResponseH\x00R\x11writeOpenResponse\x12I\n" +
	"\x0fwrite_chunk_ack\x18\x06 \x01(\v2\x1f.djadmin.agent.v1.WriteChunkAckH\x00R\rwriteChunkAck\x12X\n" +
	"\x14write_close_response\x18\a \x01(\v2$.djadmin.agent.v1.WriteCloseResponseH\x00R\x12writeCloseResponse\x12K\n" +
	"\x0frename_response\x18\b \x01(\v2 .djadmin.agent.v1.RenameResponseH\x00R\x0erenameResponse\x12K\n" +
	"\x0fdelete_response\x18\t \x01(\v2 .djadmin.agent.v1.DeleteResponseH\x00R\x0edeleteResponse\x12H\n" +
	"\x0emkdir_response\x18\n" +
	" \x01(\v2\x1f.djadmin.agent.v1.MkdirResponseH\x00R\rmkdirResponse\x12X\n" +
	"\x14create_file_response\x18\v \x01(\v2$.djadmin.agent.v1.CreateFileResponseH\x00R\x12createFileResponse\x12^\n" +
	"\x16terminal_open_response\x18\f \x01(\v2&.djadmin.agent.v1.TerminalOpenResponseH\x00R\x14terminalOpenResponse\x12^\n" +
	"\x16terminal_data_response\x18\r \x01(\v2&.djadmin.agent.v1.TerminalDataResponseH\x00R\x14terminalDataResponse\x12^\n" +
	"\x16terminal_exit_response\x18\x0e \x01(\v2&.djadmin.agent.v1.TerminalExitResponseH\x00R\x14terminalExitResponse\x12m\n" +
	"\x1bautomation_execute_response\x18\x0f \x01(\v2+.djadmin.agent.v1.AutomationExecuteResponseH\x00R\x19automationExecuteResponseB\t\n" +
	"\apayload\"8\n" +
	"\x05Hello\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"@\n" +
	"\bHelloAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"t\n" +
	"\tFileEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\x12\x15\n" +
	"\x06is_dir\x18\x04 \x01(\bR\x05isDir\x12\x14\n" +
	"\x05mtime\x18\x05 \x01(\x03R\x05mtime\"@\n" +
	"\vListRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x9d\x01\n" +
	"\fListResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12!\n" +
	"\fcurrent_path\x18\x02 \x01(\tR\vcurrentPath\x125\n" +
	"\aentries\x18\x03 \x03(\v2\x1b.djadmin.agent.v1.FileEntryR\aentries\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"@\n" +
	"\vStatRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\xc1\x01\n" +
	"\fStatResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12'\n" +
	"\x0fnormalized_path\x18\x02 \x01(\tR\x0enormalizedPath\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\rR\x04mode\x12\x15\n" +
	"\x06is_dir\x18\x05 \x01(\bR\x05isDir\x12\x14\n" +
	"\x05mtime\x18\x06 \x01(\x03R\x05mtime\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\"p\n" +
	"\vReadRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06length\x18\x04 \x01(\x03R\x06length\"\x83\x01\n" +
	"\tReadChunk\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x03 \x01(\bR\x03eof\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x03R\bfileSize\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"i\n" +
	"\x10WriteOpenRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x19\n" +
	"\bdir_path\x18\x02 \x01(\tR\adirPath\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\"H\n" +
	"\x11WriteOpenResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"F\n" +
	"\x11WriteChunkRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"i\n" +
	"\rWriteChunkAck\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12#\n" +
	"\rbytes_written\x18\x02 \x01(\x03R\fbytesWritten\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"H\n" +
	"\x11WriteCloseRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05abort\x18\x02 \x01(\bR\x05abort\"~\n" +
	"\x12WriteCloseResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x03R\n" +
	"totalBytes\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"]\n" +
	"\rRenameRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x19\n" +
	"\bnew_name\x18\x03 \x01(\tR\anewName\"m\n" +
	"\x0eRenameResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"`\n" +
	"\rDeleteRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x03 \x01(\bR\trecursive\"Y\n" +
	"\x0eDeleteResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"U\n" +
	"\fMkdirRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"l\n" +
	"\rMkdirResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"Z\n" +
	"\x11CreateFileRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"q\n" +
	"\x12CreateFileResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"}\n" +
	"\x13TerminalOpenRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\rR\x04rows\x12\x1f\n" +
	"\vtarget_user\x18\x04 \x01(\tR\n" +
	"targetUser\"r\n" +
	"\x14TerminalOpenResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12%\n" +
	"\x0eeffective_user\x18\x03 \x01(\tR\reffectiveUser\"H\n" +
	"\x13TerminalDataRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"I\n" +
	"\x14TerminalDataResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"^\n" +
	"\x15TerminalResizeRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\rR\x04rows\"5\n" +
	"\x14TerminalCloseRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\"h\n" +
	"\x14TerminalExitResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xc6\x01\n" +
	"\x18AutomationExecuteRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1f\n" +
	"\vparams_json\x18\x05 \x01(\tR\n" +
	"paramsJson\x12'\n" +
	"\x0ftimeout_seconds\x18\x06 \x01(\x05R\x0etimeoutSeconds\"\x9e\x02\n" +
	"\x19AutomationExecuteResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1b\n" +
	"\texit_code\x18\x04 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x05 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x06 \x01(\tR\x06stderr\x12(\n" +
	"\x10result_data_json\x18\a \x01(\tR\x0eresultDataJson\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\x12\x17\n" +
	"\acost_ms\x18\t \x01(\x03R\x06costMs2Z\n" +
	"\fAgentChannel\x12J\n" +
	"\aSession\x12\x1c.djadmin.agent.v1.AgentFrame\x1a\x1d.djadmin.agent.v1.ServerFrame(\x010\x01B;Z9github.com/chlinwei/djadmin/dj_agent/internal/grpcfile/pbb\x06proto3"

var (
	file_agent_channel_proto_rawDescOnce sync.Once
	file_agent_channel_proto_rawDescData []byte
)

func file_agent_channel_proto_rawDescGZIP() []byte {
	file_agent_channel_proto_rawDescOnce.Do(func() {
		file_agent_channel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_channel_proto_rawDesc), len(file_agent_channel_proto_rawDesc)))
	})
	return file_agent_channel_proto_rawDescData
}

var file_agent_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_agent_channel_proto_goTypes = []any{
	(*ServerFrame)(nil),               // 0: djadmin.agent.v1.ServerFrame
	(*AgentFrame)(nil),                // 1: djadmin.agent.v1.AgentFrame
	(*Hello)(nil),                     // 2: djadmin.agent.v1.Hello
	(*HelloAck)(nil),                  // 3: djadmin.agent.v1.HelloAck
	(*FileEntry)(nil),                 // 4: djadmin.agent.v1.FileEntry
	(*ListRequest)(nil),               // 5: djadmin.agent.v1.ListRequest
	(*ListResponse)(nil),              // 6: djadmin.agent.v1.ListResponse
	(*StatRequest)(nil),               // 7: djadmin.agent.v1.StatRequest
	(*StatResponse)(nil),              // 8: djadmin.agent.v1.StatResponse
	(*ReadRequest)(nil),               // 9: djadmin.agent.v1.ReadRequest
	(*ReadChunk)(nil),                 // 10: djadmin.agent.v1.ReadChunk
	(*WriteOpenRequest)(nil),          // 11: djadmin.agent.v1.WriteOpenRequest
	(*WriteOpenResponse)(nil),         // 12: djadmin.agent.v1.WriteOpenResponse
	(*WriteChunkRequest)(nil),         // 13: djadmin.agent.v1.WriteChunkRequest
	(*WriteChunkAck)(nil),             // 14: djadmin.agent.v1.WriteChunkAck
	(*WriteCloseRequest)(nil),         // 15: djadmin.agent.v1.WriteCloseRequest
	(*WriteCloseResponse)(nil),        // 16: djadmin.agent.v1.WriteCloseResponse
	(*RenameRequest)(nil),             // 17: djadmin.agent.v1.RenameRequest
	(*RenameResponse)(nil),            // 18: djadmin.agent.v1.RenameResponse
	(*DeleteRequest)(nil),             // 19: djadmin.agent.v1.DeleteRequest
	(*DeleteResponse)(nil),            // 20: djadmin.agent.v1.DeleteResponse
	(*MkdirRequest)(nil),              // 21: djadmin.agent.v1.MkdirRequest
	(*MkdirResponse)(nil),             // 22: djadmin.agent.v1.MkdirResponse
	(*CreateFileRequest)(nil),         // 23: djadmin.agent.v1.CreateFileRequest
	(*CreateFileResponse)(nil),        // 24: djadmin.agent.v1.CreateFileResponse
	(*TerminalOpenRequest)(nil),       // 25: djadmin.agent.v1.TerminalOpenRequest
	(*TerminalOpenResponse)(nil),      // 26: djadmin.agent.v1.TerminalOpenResponse
	(*TerminalDataRequest)(nil),       // 27: djadmin.agent.v1.TerminalDataRequest
	(*TerminalDataResponse)(nil),      // 28: djadmin.agent.v1.TerminalDataResponse
	(*TerminalResizeRequest)(nil),     // 29: djadmin.agent.v1.TerminalResizeRequest
	(*TerminalCloseRequest)(nil),      // 30: djadmin.agent.v1.TerminalCloseRequest
	(*TerminalExitResponse)(nil),      // 31: djadmin.agent.v1.TerminalExitResponse
	(*AutomationExecuteRequest)(nil),  // 32: djadmin.agent.v1.AutomationExecuteRequest
	(*AutomationExecuteResponse)(nil), // 33: djadmin.agent.v1.AutomationExecuteResponse
}
var file_agent_channel_proto_depIdxs = []int32{
	3,  // 0: djadmin.agent.v1.ServerFrame.hello_ack:type_name -> djadmin.agent.v1.HelloAck
	5,  // 1: djadmin.agent.v1.ServerFrame.list_request:type_name -> djadmin.agent.v1.ListRequest
	7,  // 2: djadmin.agent.v1.ServerFrame.stat_request:type_name -> djadmin.agent.v1.StatRequest
	9,  // 3: djadmin.agent.v1.ServerFrame.read_request:type_name -> djadmin.agent.v1.ReadRequest
	11, // 4: djadmin.agent.v1.ServerFrame.write_open_request:type_name -> djadmin.agent.v1.WriteOpenRequest
	13, // 5: djadmin.agent.v1.ServerFrame.write_chunk_request:type_name -> djadmin.agent.v1.WriteChunkRequest
	15, // 6: djadmin.agent.v1.ServerFrame.write_close_request:type_name -> djadmin.agent.v1.WriteCloseRequest
	17, // 7: djadmin.agent.v1.ServerFrame.rename_request:type_name -> djadmin.agent.v1.RenameRequest
	19, // 8: djadmin.agent.v1.ServerFrame.delete_request:type_name -> djadmin.agent.v1.DeleteRequest
	21, // 9: djadmin.agent.v1.ServerFrame.mkdir_request:type_name -> djadmin.agent.v1.MkdirRequest
	23, // 10: djadmin.agent.v1.ServerFrame.create_file_request:type_name -> djadmin.agent.v1.CreateFileRequest
	25, // 11: djadmin.agent.v1.ServerFrame.terminal_open_request:type_name -> djadmin.agent.v1.TerminalOpenRequest
	27, // 12: djadmin.agent.v1.ServerFrame.terminal_data_request:type_name -> djadmin.agent.v1.TerminalDataRequest
	29, // 13: djadmin.agent.v1.ServerFrame.terminal_resize_request:type_name -> djadmin.agent.v1.TerminalResizeRequest
	30, // 14: djadmin.agent.v1.ServerFrame.terminal_close_request:type_name -> djadmin.agent.v1.TerminalCloseRequest
	32, // 15: djadmin.agent.v1.ServerFrame.automation_execute_request:type_name -> djadmin.agent.v1.AutomationExecuteRequest
	2,  // 16: djadmin.agent.v1.AgentFrame.hello:type_name -> djadmin.agent.v1.Hello
	6,  // 17: djadmin.agent.v1.AgentFrame.list_response:type_name -> djadmin.agent.v1.ListResponse
	8,  // 18: djadmin.agent.v1.AgentFrame.stat_response:type_name -> djadmin.agent.v1.StatResponse
	10, // 19: djadmin.agent.v1.AgentFrame.read_chunk:type_name -> djadmin.agent.v1.ReadChunk
	12, // 20: djadmin.agent.v1.AgentFrame.write_open_response:type_name -> djadmin.agent.v1.WriteOpenResponse
	14, // 21: djadmin.agent.v1.AgentFrame.write_chunk_ack:type_name -> djadmin.agent.v1.WriteChunkAck
	16, // 22: djadmin.agent.v1.AgentFrame.write_close_response:type_name -> djadmin.agent.v1.WriteCloseResponse
	18, // 23: djadmin.agent.v1.AgentFrame.rename_response:type_name -> djadmin.agent.v1.RenameResponse
	20, // 24: djadmin.agent.v1.AgentFrame.delete_response:type_name -> djadmin.agent.v1.DeleteResponse
	22, // 25: djadmin.agent.v1.AgentFrame.mkdir_response:type_name -> djadmin.agent.v1.MkdirResponse
	24, // 26: djadmin.agent.v1.AgentFrame.create_file_response:type_name -> djadmin.agent.v1.CreateFileResponse
	26, // 27: djadmin.agent.v1.AgentFrame.terminal_open_response:type_name -> djadmin.agent.v1.TerminalOpenResponse
	28, // 28: djadmin.agent.v1.AgentFrame.terminal_data_response:type_name -> djadmin.agent.v1.TerminalDataResponse
	31, // 29: djadmin.agent.v1.AgentFrame.terminal_exit_response:type_name -> djadmin.agent.v1.TerminalExitResponse
	33, // 30: djadmin.agent.v1.AgentFrame.automation_execute_response:type_name -> djadmin.agent.v1.AutomationExecuteResponse
	4,  // 31: djadmin.agent.v1.ListResponse.entries:type_name -> djadmin.agent.v1.FileEntry
	1,  // 32: djadmin.agent.v1.AgentChannel.Session:input_type -> djadmin.agent.v1.AgentFrame
	0,  // 33: djadmin.agent.v1.AgentChannel.Session:output_type -> djadmin.agent.v1.ServerFrame
	33, // [33:34] is the sub-list for method output_type
	32, // [32:33] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_agent_channel_proto_init() }
func file_agent_channel_proto_init() {
	if File_agent_channel_proto != nil {
		return
	}
	file_agent_channel_proto_msgTypes[0].OneofWrappers = []any{
		(*ServerFrame_HelloAck)(nil),
		(*ServerFrame_ListRequest)(nil),
		(*ServerFrame_StatRequest)(nil),
		(*ServerFrame_ReadRequest)(nil),
		(*ServerFrame_WriteOpenRequest)(nil),
		(*ServerFrame_WriteChunkRequest)(nil),
		(*ServerFrame_WriteCloseRequest)(nil),
		(*ServerFrame_RenameRequest)(nil),
		(*ServerFrame_DeleteRequest)(nil),
		(*ServerFrame_MkdirRequest)(nil),
		(*ServerFrame_CreateFileRequest)(nil),
		(*ServerFrame_TerminalOpenRequest)(nil),
		(*ServerFrame_TerminalDataRequest)(nil),
		(*ServerFrame_TerminalResizeRequest)(nil),
		(*ServerFrame_TerminalCloseRequest)(nil),
		(*ServerFrame_AutomationExecuteRequest)(nil),
	}
	file_agent_channel_proto_msgTypes[1].OneofWrappers = []any{
		(*AgentFrame_Hello)(nil),
		(*AgentFrame_ListResponse)(nil),
		(*AgentFrame_StatResponse)(nil),
		(*AgentFrame_ReadChunk)(nil),
		(*AgentFrame_WriteOpenResponse)(nil),
		(*AgentFrame_WriteChunkAck)(nil),
		(*AgentFrame_WriteCloseResponse)(nil),
		(*AgentFrame_RenameResponse)(nil),
		(*AgentFrame_DeleteResponse)(nil),
		(*AgentFrame_MkdirResponse)(nil),
		(*AgentFrame_CreateFileResponse)(nil),
		(*AgentFrame_TerminalOpenResponse)(nil),
		(*AgentFrame_TerminalDataResponse)(nil),
		(*AgentFrame_TerminalExitResponse)(nil),
		(*AgentFrame_AutomationExecuteResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_channel_proto_rawDesc), len(file_agent_channel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_channel_proto_goTypes,
		DependencyIndexes: file_agent_channel_proto_depIdxs,
		MessageInfos:      file_agent_channel_proto_msgTypes,
	}.Build()
	File_agent_channel_proto = out.File
	file_agent_channel_proto_goTypes = nil
	file_agent_channel_proto_depIdxs = nil
}
