// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: agent_channel.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentChannel_Session_FullMethodName = "/djadmin.agent.v1.AgentChannel/Session"
)

// AgentChannelClient is the client API for AgentChannel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// dj-agent 统一控制/数据通道：与现有 RabbitMQ 心跳/任务模型保持相同的网络方向——
// 由 agent 主动拨号连接 backend 并建立一条长连接双向流，backend 在这条流里下发
// 各类操作命令（文件传输 / WebSSH 终端 / 自动化任务执行），agent 在本地执行后把
// 结果/数据块回传。所有操作以 request_id 在同一条流上多路复用。
// 之所以不采用 backend 主动连 agent 的模型，是因为目标主机通常在 NAT/防火墙后面，
// 不具备被 backend 直接访问的入站连通性；agent-拨出模型可以复用现有网络策略。
type AgentChannelClient interface {
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentFrame, ServerFrame], error)
}

type agentChannelClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentChannelClient(cc grpc.ClientConnInterface) AgentChannelClient {
	return &agentChannelClient{cc}
}

func (c *agentChannelClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentFrame, ServerFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentChannel_ServiceDesc.Streams[0], AgentChannel_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentFrame, ServerFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentChannel_SessionClient = grpc.BidiStreamingClient[AgentFrame, ServerFrame]

// AgentChannelServer is the server API for AgentChannel service.
// All implementations must embed UnimplementedAgentChannelServer
// for forward compatibility.
//
// dj-agent 统一控制/数据通道：与现有 RabbitMQ 心跳/任务模型保持相同的网络方向——
// 由 agent 主动拨号连接 backend 并建立一条长连接双向流，backend 在这条流里下发
// 各类操作命令（文件传输 / WebSSH 终端 / 自动化任务执行），agent 在本地执行后把
// 结果/数据块回传。所有操作以 request_id 在同一条流上多路复用。
// 之所以不采用 backend 主动连 agent 的模型，是因为目标主机通常在 NAT/防火墙后面，
// 不具备被 backend 直接访问的入站连通性；agent-拨出模型可以复用现有网络策略。
type AgentChannelServer interface {
	Session(grpc.BidiStreamingServer[AgentFrame, ServerFrame]) error
	mustEmbedUnimplementedAgentChannelServer()
}

// UnimplementedAgentChannelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentChannelServer struct{}

func (UnimplementedAgentChannelServer) Session(grpc.BidiStreamingServer[AgentFrame, ServerFrame]) error {
	return status.Error(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedAgentChannelServer) mustEmbedUnimplementedAgentChannelServer() {}
func (UnimplementedAgentChannelServer) testEmbeddedByValue()                      {}

// UnsafeAgentChannelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentChannelServer will
// result in compilation errors.
type UnsafeAgentChannelServer interface {
	mustEmbedUnimplementedAgentChannelServer()
}

func RegisterAgentChannelServer(s grpc.ServiceRegistrar, srv AgentChannelServer) {
	// If the following call panics, it indicates UnimplementedAgentChannelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentChannel_ServiceDesc, srv)
}

func _AgentChannel_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentChannelServer).Session(&grpc.GenericServerStream[AgentFrame, ServerFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentChannel_SessionServer = grpc.BidiStreamingServer[AgentFrame, ServerFrame]

// AgentChannel_ServiceDesc is the grpc.ServiceDesc for AgentChannel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentChannel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "djadmin.agent.v1.AgentChannel",
	HandlerType: (*AgentChannelServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _AgentChannel_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agent_channel.proto",
}
