# Generated by Django 5.1.4 on 2024-12-21 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sysmenu',
            table='sys_menu',
        ),
    ]
