# Generated by Django 5.1.4 on 2025-06-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_sysmenu_create_time_alter_sysmenu_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysmenu',
            name='component',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='组件路径'),
        ),
    ]
