# Generated by Django 5.1.4 on 2025-06-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_sysmenu_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysmenu',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='菜单图标'),
        ),
    ]
