# Generated by Django 5.1.4 on 2025-06-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_sysmenu_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysmenu',
            name='perms',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='权限标识'),
        ),
    ]
