# Generated by Django 5.1.4 on 2025-06-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_sysmenu_perms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysmenu',
            name='path',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='路由地址'),
        ),
    ]
