# Generated by Django 5.1.4 on 2025-06-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_sysmenu_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysmenu',
            name='location',
            field=models.SmallIntegerField(choices=[(1, '左侧菜单'), (2, '用户中心')], default=1, verbose_name='权限位置'),
        ),
    ]
