# Generated by Django 5.1.4 on 2026-08-24 09:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0087_merge_20260824_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=16)),
                ('task_snapshot', models.JSONField(blank=True, default=dict)),
                ('group_snapshot', models.JSONField(blank=True, default=dict)),
                ('service_snapshot', models.JSONField(blank=True, default=dict)),
                ('target_snapshot', models.JSONField(blank=True, default=list)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('requested_user_id', models.IntegerField(blank=True, null=True)),
                ('requested_username', models.CharField(blank=True, default='', max_length=100)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inspection_execution',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InspectionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='巡检组名称')),
                ('scope', models.CharField(choices=[('per_deployment', '每个部署实例'), ('controller_once', '控制端单次')], max_length=24, verbose_name='执行范围')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'db_table': 'inspection_group',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InspectionTargetExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('target_name', models.CharField(max_length=255)),
                ('host_id_snapshot', models.IntegerField(blank=True, null=True)),
                ('host_ip_snapshot', models.CharField(blank=True, default='', max_length=64)),
                ('agent_id_snapshot', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=16)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('raw_result', models.JSONField(blank=True, default=dict)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('deployment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_target_executions', to='assets.applicationdeployment')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='inspection.inspectionexecution')),
            ],
            options={
                'db_table': 'inspection_target_execution',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InspectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('check_key', models.CharField(max_length=255)),
                ('check_type', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=16)),
                ('expected_value', models.JSONField(blank=True, null=True)),
                ('actual_value', models.JSONField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='inspection.inspectiontargetexecution')),
            ],
            options={
                'db_table': 'inspection_result',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InspectionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='任务名称')),
                ('concurrency', models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='并发数')),
                ('timeout_seconds', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(3600)], verbose_name='单目标超时')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='inspection.inspectiongroup')),
                ('logical_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_tasks', to='assets.applicationservice')),
            ],
            options={
                'db_table': 'inspection_task',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='inspectionexecution',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='inspection.inspectiontask'),
        ),
        migrations.CreateModel(
            name='InspectionCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=128, verbose_name='检查项名称')),
                ('executor', models.CharField(choices=[('shell', 'Agent Shell'), ('http', '控制端 HTTP'), ('tcp', '控制端 TCP')], max_length=16, verbose_name='执行器')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='检查配置')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='顺序')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='inspection.inspectiongroup')),
            ],
            options={
                'db_table': 'inspection_check',
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('group', 'name'), name='unique_inspection_group_check_name')],
            },
        ),
    ]
