# Generated by Django 5.1.4 on 2026-08-24 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0087_merge_20260824_1332'),
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontargetexecution',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_target_executions', to='assets.host'),
        ),
        migrations.AddField(
            model_name='inspectiontask',
            name='host_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspection_tasks', to='assets.hostgroup'),
        ),
        migrations.AddField(
            model_name='inspectiontask',
            name='target_type',
            field=models.CharField(choices=[('logical_service', '逻辑服务'), ('host_group', '主机组')], default='logical_service', max_length=24, verbose_name='目标类型'),
        ),
        migrations.AlterField(
            model_name='inspectiontask',
            name='logical_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspection_tasks', to='assets.applicationservice'),
        ),
    ]
