# Generated by Django 5.1.4 on 2026-08-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0005_inspectioncheck_schema_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectioncheck',
            name='severity',
            field=models.CharField(choices=[('critical', '严重'), ('warning', '警告')], default='critical', max_length=16, verbose_name='严重级别'),
        ),
        migrations.AddField(
            model_name='inspectionexecution',
            name='trigger_type',
            field=models.CharField(choices=[('manual', '手动'), ('scheduled', '定时')], default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='inspectionresult',
            name='severity',
            field=models.CharField(choices=[('critical', '严重'), ('warning', '警告')], default='critical', max_length=16),
        ),
        migrations.AddField(
            model_name='inspectiontask',
            name='cron_expression',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='cron 表达式'),
        ),
        migrations.AddField(
            model_name='inspectiontask',
            name='last_run_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近运行时间'),
        ),
        migrations.AddField(
            model_name='inspectiontask',
            name='next_run_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='下次运行时间'),
        ),
    ]
