# Generated by Django 5.1.4 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0010_inspectiontask_fixed_host_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectioncheck',
            name='execution_location',
            field=models.CharField(
                choices=[('agent', 'Agent'), ('controller', 'djadmin')],
                default='agent',
                max_length=16,
                verbose_name='执行位置',
            ),
        ),
    ]