# Generated by Django 5.1.4 on 2026-06-29 02:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_scheduledtask_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtasklog',
            name='output',
            field=models.TextField(blank=True, help_text='Task execution output/logs', null=True),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='create_time',
            field=models.DateField(default=datetime.date(2026, 6, 29), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='scheduledtasklog',
            name='create_time',
            field=models.DateField(default=datetime.date(2026, 6, 29), verbose_name='创建时间'),
        ),
    ]
