# Generated by Django 5.1.4 on 2026-06-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_scheduledtasklog_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='next_run_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='下次运行时间'),
        ),
    ]
