# Generated by Django 5.1.4 on 2026-06-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_scheduledtask_next_run_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='is_running',
            field=models.BooleanField(default=False, verbose_name='正在运行'),
        ),
    ]
