# Generated by Django 5.1.4 on 2026-07-05 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_scheduledtask_is_running'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='create_time',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='scheduledtasklog',
            name='create_time',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='创建时间'),
        ),
    ]
