# Generated by Django 5.1.4 on 2026-07-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_alter_scheduledtask_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='scheduledtasklog',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
