# Generated by Django 5.1.4 on 2026-07-02 03:23

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0015_webssh_session_content_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleExecutionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(default=datetime.date(2026, 7, 2), verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('job_id', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual'), ('schedule', 'Schedule')], default='manual', max_length=16)),
                ('inventory_snapshot', models.JSONField(blank=True, default=dict)),
                ('extra_vars', models.JSONField(blank=True, default=dict)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('requested_user_id', models.IntegerField(blank=True, null=True)),
                ('requested_username', models.CharField(blank=True, default='', max_length=100)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'automation_ansible_execution_job',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PlaybookTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(default=datetime.date(2026, 7, 2), verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('code', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(help_text='Playbook YAML content')),
                ('default_extra_vars', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'automation_playbook_template',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AnsibleExecutionTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(default=datetime.date(2026, 7, 2), verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('host_name', models.CharField(blank=True, default='', max_length=128)),
                ('host_ip', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('unreachable', 'Unreachable')], default='pending', max_length=16)),
                ('rc', models.IntegerField(blank=True, null=True)),
                ('stdout', models.TextField(blank=True, default='')),
                ('stderr', models.TextField(blank=True, default='')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ansible_targets', to='assets.host')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='automation.ansibleexecutionjob')),
            ],
            options={
                'db_table': 'automation_ansible_execution_target',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='ansibleexecutionjob',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='automation.playbooktemplate'),
        ),
    ]
