# Generated by Django 5.1.4 on 2026-07-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_remove_playbooktemplate_default_extra_vars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playbooktemplate',
            name='code',
        ),
    ]
