# Generated by Django 5.1.4 on 2026-07-05 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0013_task_default_limit_and_job_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansibleexecutionjob',
            name='create_time',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='ansibleexecutiontarget',
            name='create_time',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='automationinventory',
            name='create_time',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='automationtask',
            name='create_time',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='playbooktemplate',
            name='create_time',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='创建时间'),
        ),
    ]
