# Generated by Django 5.1.4 on 2026-07-05 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0015_workflow_template_and_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationworkflowrun',
            name='create_time',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='automationworkflowtemplate',
            name='create_time',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='创建时间'),
        ),
    ]
