# Generated by Django 5.1.4 on 2026-07-05 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0016_alter_automationworkflowrun_create_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automationworkflowtemplate',
            name='code',
        ),
    ]
