# Generated by Django 5.1.4 on 2026-07-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0017_remove_automationworkflowtemplate_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansibleexecutionjob',
            name='become_enabled_snapshot',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ansibleexecutionjob',
            name='become_method_snapshot',
            field=models.CharField(default='sudo', max_length=16),
        ),
        migrations.AddField(
            model_name='ansibleexecutionjob',
            name='become_user_snapshot',
            field=models.CharField(default='root', max_length=100),
        ),
        migrations.AddField(
            model_name='automationtask',
            name='become_enabled',
            field=models.BooleanField(default=True, help_text='是否启用权限提升'),
        ),
        migrations.AddField(
            model_name='automationtask',
            name='become_method',
            field=models.CharField(choices=[('sudo', 'sudo'), ('su', 'su')], default='sudo', help_text='权限提升方式', max_length=16),
        ),
        migrations.AddField(
            model_name='automationtask',
            name='become_user',
            field=models.CharField(default='root', help_text='目标用户', max_length=100),
        ),
        migrations.AlterField(
            model_name='automationworkflowrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=24),
        ),
    ]
