# Generated by Django 5.1.4 on 2026-07-09 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0019_workflow_default_scope_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansibleexecutionjob',
            name='become_enabled_snapshot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='automationtask',
            name='become_enabled',
            field=models.BooleanField(default=False, help_text='是否启用权限提升'),
        ),
        migrations.AlterField(
            model_name='automationworkflowrun',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='automation.automationworkflowtemplate'),
        ),
    ]
