# Generated by Django 5.1.4 on 2026-07-15 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0021_update_time_to_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ansibleexecutionjob',
            name='template',
        ),
    ]
