# Generated by Django 5.1.4 on 2026-07-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0022_remove_ansibleexecutionjob_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregate_type', models.CharField(max_length=64)),
                ('aggregate_id', models.IntegerField()),
                ('event_type', models.CharField(max_length=128)),
                ('task_name', models.CharField(max_length=255)),
                ('queue_name', models.CharField(blank=True, default='celery', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'automation_outbox_event',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='automation__status_0982f6_idx'), models.Index(fields=['event_type'], name='automation__event_t_a018c1_idx'), models.Index(fields=['aggregate_type', 'aggregate_id'], name='automation__aggrega_e2590f_idx')],
            },
        ),
    ]
