# Generated by Django 5.1.4 on 2026-07-16 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0024_alter_ansibleexecutionjob_create_time_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='DROP TABLE IF EXISTS automation_outbox_event;',
                    reverse_sql='''
                        CREATE TABLE IF NOT EXISTS automation_outbox_event (
                            id BIGINT AUTO_INCREMENT PRIMARY KEY
                        );
                    ''',
                ),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name='OutboxEvent',
                ),
            ],
        ),
    ]
