# Generated by Django 5.1.4 on 2026-07-16 02:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0025_delete_outboxevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleExecutionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('host_name', models.CharField(blank=True, default='', max_length=128)),
                ('host_ip', models.CharField(blank=True, default='', max_length=64)),
                ('stream', models.CharField(blank=True, default='stdout', max_length=16)),
                ('event_type', models.CharField(blank=True, default='log', max_length=32)),
                ('line_no', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='automation.ansibleexecutionjob')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='automation.ansibleexecutiontarget')),
            ],
            options={
                'db_table': 'automation_ansible_execution_event',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['job', 'id'], name='automation__job_id_8cbc99_idx'), models.Index(fields=['job', 'line_no'], name='automation__job_id_9f3411_idx'), models.Index(fields=['host_name'], name='automation__host_na_069fe1_idx')],
            },
        ),
    ]
