# Generated by Django 5.1.4 on 2026-07-16 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0026_ansibleexecutionevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ansibleexecutiontarget',
            name='stderr',
        ),
        migrations.RemoveField(
            model_name='ansibleexecutiontarget',
            name='stdout',
        ),
    ]
