# Generated by Django 5.1.4 on 2026-07-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0032_delete_ansibleexecutiontarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtask',
            name='execution_timeout_seconds',
            field=models.PositiveIntegerField(default=3600, help_text='任务执行超时时间（秒），最大4小时(14400秒)'),
        ),
    ]
