# Generated by Django 5.1.4 on 2026-07-16 09:36

import automation.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0033_automationtask_execution_timeout_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShellScriptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(help_text='Shell script content')),
                ('parameters', models.JSONField(blank=True, default=list, help_text='Script parameters: [{"name": "param1", "description": "desc", "default": "value"}]')),
            ],
            options={
                'db_table': 'automation_shell_script_template',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='automationtask',
            name='template',
        ),
        migrations.AddField(
            model_name='automationtask',
            name='playbook_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='automation.playbooktemplate'),
        ),
        migrations.AlterField(
            model_name='automationtask',
            name='execution_timeout_seconds',
            field=models.PositiveIntegerField(default=3600, help_text='任务执行超时时间（秒），最大4小时(14400秒)', validators=[automation.models.validate_timeout]),
        ),
        migrations.AddField(
            model_name='automationtask',
            name='shell_script_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='automation.shellscripttemplate'),
        ),
    ]
