# Generated by Django 5.2.5 on 2026-07-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0034_add_shell_script_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtask',
            name='shell_parameters',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ansibleexecutionjob',
            name='shell_env_vars',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ansibleexecutionjob',
            name='shell_parameters',
            field=models.TextField(blank=True, default=''),
        ),
    ]
