# Generated by Django 5.1.4 on 2026-07-19 12:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0039_rename_job_table_and_drop_job_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationexecutiontargetlog',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='automationexecutiontargetlog',
            name='remark',
            field=models.TextField(blank=True, default='', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='automationexecutiontargetlog',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
