# Generated by Django 5.1.4 on 2026-07-19 13:58

import automation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0042_alter_automationexecutiontargetlog_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationtask',
            name='execution_timeout_seconds',
            field=models.PositiveIntegerField(default=600, help_text='任务执行超时时间（秒），最大4小时(14400秒)', validators=[automation.models.validate_timeout]),
        ),
    ]
