# Generated by Django 5.1.4 on 2026-07-21 02:49

from django.db import migrations, models


def backfill_software_package_category(apps, schema_editor):
    """将当前已被 监控软件仓库(SoftwarePackage) 的 install_task/uninstall_task 引用到的
    Playbook/Shell 模板，自动回填为 software_package 分类，避免存量数据需要人工整理。
    """
    AutomationTask = apps.get_model('automation', 'AutomationTask')
    try:
        SoftwarePackage = apps.get_model('monitor', 'SoftwarePackage')
    except LookupError:
        # monitor app 未安装/无该表时直接跳过，不影响 automation 自身迁移。
        return

    bound_task_ids = set()
    for field_name in ('install_task_id', 'uninstall_task_id'):
        bound_task_ids.update(
            SoftwarePackage.objects.exclude(**{field_name: None}).values_list(field_name, flat=True)
        )
    if not bound_task_ids:
        return

    playbook_ids = set(
        AutomationTask.objects.filter(id__in=bound_task_ids, playbook_template_id__isnull=False)
        .values_list('playbook_template_id', flat=True)
    )
    shell_ids = set(
        AutomationTask.objects.filter(id__in=bound_task_ids, shell_script_template_id__isnull=False)
        .values_list('shell_script_template_id', flat=True)
    )

    PlaybookTemplate = apps.get_model('automation', 'PlaybookTemplate')
    ShellScriptTemplate = apps.get_model('automation', 'ShellScriptTemplate')
    if playbook_ids:
        PlaybookTemplate.objects.filter(id__in=playbook_ids).update(category='software_package')
    if shell_ids:
        ShellScriptTemplate.objects.filter(id__in=shell_ids).update(category='software_package')


def noop_reverse(apps, schema_editor):
    # 分类回填是单向的数据整理动作，回滚迁移时无需还原（category 字段本身会被 RemoveField 移除）。
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0044_replace_become_with_run_as_identity'),
        ('monitor', '0014_replace_manage_script_with_automation_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbooktemplate',
            name='category',
            field=models.CharField(choices=[('general', '通用'), ('software_package', '软件包安装/卸载专用')], default='general', help_text='模板分类：通用 / 软件包安装卸载专用，用于列表页默认分组展示', max_length=32),
        ),
        migrations.AddField(
            model_name='shellscripttemplate',
            name='category',
            field=models.CharField(choices=[('general', '通用'), ('software_package', '软件包安装/卸载专用')], default='general', help_text='模板分类：通用 / 软件包安装卸载专用，用于列表页默认分组展示', max_length=32),
        ),
        migrations.RunPython(backfill_software_package_category, noop_reverse),
    ]
