# Generated by Django 5.1.4 on 2025-06-09 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='private_key',
            field=models.TextField(blank=True, default='', max_length=8192, null=True, verbose_name='SSH 私钥'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='create_time',
            field=models.DateField(default=datetime.date(2025, 6, 9), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='host',
            name='create_time',
            field=models.DateField(default=datetime.date(2025, 6, 9), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='host_type',
            name='create_time',
            field=models.DateField(default=datetime.date(2025, 6, 9), verbose_name='创建时间'),
        ),
    ]
