# Generated by Django 5.1.4 on 2025-06-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_credential_private_key_alter_credential_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='private_key',
            field=models.TextField(default=None, max_length=8192, null=True, verbose_name='SSH 私钥'),
        ),
    ]
