# Generated by Django 5.1.4 on 2025-06-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_credential_private_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='private_key',
            field=models.TextField(blank=True, default=None, max_length=8192, null=True, verbose_name='SSH 私钥'),
        ),
    ]
