# Generated by Django 5.1.4 on 2025-06-10 08:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_credential_private_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(default=datetime.date(2025, 6, 10), verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('name', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='应用')),
            ],
            options={
                'db_table': 'assets_application',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='host',
            name='host_type',
        ),
        migrations.AlterField(
            model_name='credential',
            name='create_time',
            field=models.DateField(default=datetime.date(2025, 6, 10), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='host',
            name='create_time',
            field=models.DateField(default=datetime.date(2025, 6, 10), verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='host',
            name='application',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.application', verbose_name='主机类别'),
        ),
        migrations.DeleteModel(
            name='Host_Type',
        ),
    ]
