# Generated by Django 5.1.4 on 2025-06-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_application_remove_host_host_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='version',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='应用'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(blank=True, default='', max_length=128, null=True, unique=True, verbose_name='应用名称'),
        ),
    ]
