# Generated by Django 5.1.4 on 2026-02-12 06:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_application_version_alter_application_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(default=datetime.date(2026, 2, 12), verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=128)),
                ('cloud_type', models.CharField(choices=[('vsphere', 'vSphere'), ('aliyun', '阿里云'), ('aws', 'AWS'), ('manual', '手动')], max_length=32)),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('access_key', models.CharField(blank=True, max_length=128, null=True)),
                ('secret_key', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='credential',
            options={},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={},
        ),
        migrations.RemoveField(
            model_name='host',
            name='application',
        ),
        migrations.RemoveField(
            model_name='host',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='host',
            name='disk',
        ),
        migrations.RemoveField(
            model_name='host',
            name='host_credential',
        ),
        migrations.RemoveField(
            model_name='host',
            name='hostname',
        ),
        migrations.RemoveField(
            model_name='host',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='host',
            name='ssh_ip',
        ),
        migrations.RemoveField(
            model_name='host',
            name='ssh_port',
        ),
        migrations.RemoveField(
            model_name='host',
            name='system_product',
        ),
        migrations.AddField(
            model_name='credential',
            name='auth_type',
            field=models.CharField(choices=[('password', 'Password'), ('ssh_key', 'SSH Key')], default='password', max_length=16),
        ),
        migrations.AddField(
            model_name='credential',
            name='username',
            field=models.CharField(default='root', max_length=128),
        ),
        migrations.AddField(
            model_name='host',
            name='instance_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='is_deleted_in_cloud',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='application',
            name='create_time',
            field=models.DateField(default=datetime.date(2026, 2, 12), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='create_time',
            field=models.DateField(default=datetime.date(2026, 2, 12), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='private_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='create_time',
            field=models.DateField(default=datetime.date(2026, 2, 12), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.CharField(default='running', max_length=32),
        ),
        migrations.AlterModelTable(
            name='credential',
            table=None,
        ),
        migrations.AlterModelTable(
            name='host',
            table=None,
        ),
        migrations.AddField(
            model_name='host',
            name='cloud_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.cloudaccount'),
        ),
        migrations.CreateModel(
            name='HostDisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=64)),
                ('mount_point', models.CharField(blank=True, max_length=128, null=True)),
                ('size_gb', models.FloatField(blank=True, null=True)),
                ('used_gb', models.FloatField(blank=True, null=True)),
                ('filesystem', models.CharField(blank=True, max_length=64, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disks', to='assets.host')),
            ],
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(default=datetime.date(2026, 2, 12), verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='assets.hostgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='host',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.hostgroup'),
        ),
        migrations.CreateModel(
            name='HostHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(default=datetime.date(2026, 2, 12), verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('cpu_cores', models.IntegerField(blank=True, null=True)),
                ('cpu_model', models.CharField(blank=True, max_length=255, null=True)),
                ('memory_gb', models.FloatField(blank=True, null=True)),
                ('disk_total_gb', models.FloatField(blank=True, null=True)),
                ('architecture', models.CharField(blank=True, max_length=64, null=True)),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hardware', to='assets.host')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HostSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(default=datetime.date(2026, 2, 12), verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('os_type', models.CharField(blank=True, max_length=64, null=True)),
                ('os_version', models.CharField(blank=True, max_length=128, null=True)),
                ('kernel_version', models.CharField(blank=True, max_length=128, null=True)),
                ('hostname', models.CharField(blank=True, max_length=128, null=True)),
                ('agent_version', models.CharField(blank=True, max_length=64, null=True)),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system', to='assets.host')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HostCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(default=datetime.date(2026, 2, 12), verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('is_default', models.BooleanField(default=False)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.credential')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.host')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('host',), name='unique_default_credential_per_host')],
                'unique_together': {('host', 'credential')},
            },
        ),
    ]
