# Generated by Django 5.1.4 on 2026-02-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_cloudaccount_alter_credential_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='auth_type',
            field=models.IntegerField(choices=[(1, 'Password'), (2, 'SSH Key')], default=1),
        ),
    ]
