# Generated by Django 5.1.4 on 2026-02-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_alter_credential_auth_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='port',
            field=models.PositiveIntegerField(default=22),
        ),
    ]
