# Generated by Django 5.1.4 on 2026-02-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_credential_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='instance_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
