# Generated by Django 5.1.4 on 2026-07-01 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_host_collect_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSSHSessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=36, unique=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('client_ip', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('connected', '已连接'), ('closed', '已关闭'), ('failed', '连接失败')], default='connected', max_length=16)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('close_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('input_bytes', models.IntegerField(default=0)),
                ('command_count', models.IntegerField(default=0)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webssh_sessions', to='assets.host')),
            ],
            options={
                'db_table': 'assets_webssh_session_log',
                'ordering': ['-start_time'],
            },
        ),
    ]
