# Generated by Django 5.1.4 on 2026-07-05 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0018_remove_host_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='create_time',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='cloudaccount',
            name='create_time',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='create_time',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='host',
            name='create_time',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='hostcredential',
            name='create_time',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='hostgroup',
            name='create_time',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='hosthardware',
            name='create_time',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='hostsystem',
            name='create_time',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='创建时间'),
        ),
    ]
