# Generated by Django 5.1.4 on 2026-07-18 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0028_alter_credential_password'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agentjob',
            new_name='assets_agen_agent_i_ed2f13_idx',
            old_name='assets_agen_agent_i_2583a5_idx',
        ),
        migrations.RenameIndex(
            model_name='agentjob',
            new_name='assets_agen_status_d7c3d4_idx',
            old_name='assets_agen_status_4fc5ab_idx',
        ),
        migrations.RenameIndex(
            model_name='agentjobevent',
            new_name='assets_agen_job_id_33a15f_idx',
            old_name='assets_agen_job_id__7d7de9_idx',
        ),
        migrations.RenameIndex(
            model_name='agentjobevent',
            new_name='assets_agen_agent_i_854bb7_idx',
            old_name='assets_agen_agent_i_16ed57_idx',
        ),
        migrations.RenameIndex(
            model_name='agentjobevent',
            new_name='assets_agen_tag_02986e_idx',
            old_name='assets_agen_tag_6f8758_idx',
        ),
    ]
