# Generated by Django 5.1.4 on 2026-07-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0030_agentjob_exit_code_agentjob_stderr_agentjob_stdout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='agent_online_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Agent最后心跳时间'),
        ),
    ]
