# Generated by Django 5.1.4 on 2026-07-20 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0031_host_agent_online_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSSHTempCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_pk', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temp_credential_info', to='assets.credential')),
            ],
            options={
                'db_table': 'assets_webssh_temp_credential',
            },
        ),
    ]
