# Generated by Django 5.1.4 on 2026-07-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0033_webssh_session_log_utf8mb4'),
    ]

    operations = [
        migrations.AddField(
            model_name='websshsessionlog',
            name='effective_username',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='websshsessionlog',
            name='requested_username',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='websshsessionlog',
            name='switch_user_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='websshsessionlog',
            name='switch_user_status',
            field=models.CharField(blank=True, default='none', max_length=16),
        ),
    ]
