# Generated by Django 5.1.4 on 2026-08-22 01:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import re
from django.db import migrations, models


def migrate_application_versions(apps, schema_editor):
    Application = apps.get_model('assets', 'Application')
    ApplicationVersion = apps.get_model('assets', 'ApplicationVersion')

    for application in Application.objects.all():
        normalized_name = str(application.name or '').strip()
        base_code = re.sub(r'[^a-z0-9]+', '-', normalized_name.lower()).strip('-') or f'app-{application.pk}'
        candidate = base_code[:64]
        suffix = 1
        while Application.objects.exclude(pk=application.pk).filter(code=candidate).exists():
            suffix_text = f'-{suffix}'
            candidate = f'{base_code[:64 - len(suffix_text)]}{suffix_text}'
            suffix += 1

        application.name = normalized_name or f'Application-{application.pk}'
        application.code = candidate
        application.save(update_fields=['name', 'code'])

        old_version = str(application.version or '').strip()
        if old_version:
            ApplicationVersion.objects.create(application_id=application.pk, version=old_version)


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0039_hostruntime_remove_host_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='category',
            field=models.CharField(choices=[('web_container', 'Web 容器'), ('database', '数据库'), ('middleware', '中间件'), ('business', '业务应用'), ('other', '其他')], default='other', max_length=32, verbose_name='应用类别'),
        ),
        migrations.AddField(
            model_name='application',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='应用编码'),
        ),
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='application',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='application',
            name='vendor',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='厂商'),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='应用名称'),
        ),
        migrations.CreateModel(
            name='ApplicationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('version', models.CharField(max_length=128, verbose_name='版本号')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('end_of_support', models.DateField(blank=True, null=True, verbose_name='停止支持日期')),
                ('enabled', models.BooleanField(default=True, verbose_name='允许新部署')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='assets.application')),
            ],
            options={
                'db_table': 'assets_application_version',
                'ordering': ['application_id', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('instance_name', models.CharField(max_length=128, verbose_name='实例名称')),
                ('environment', models.CharField(choices=[('production', '生产'), ('testing', '测试'), ('development', '开发'), ('other', '其他')], default='production', max_length=16)),
                ('control_type', models.CharField(choices=[('systemd', 'Systemd'), ('command', '命令行'), ('external_ha', '外部 HA'), ('docker', 'Docker 容器'), ('docker_compose', 'Docker Compose')], max_length=32)),
                ('run_user', models.CharField(max_length=100, verbose_name='运行用户')),
                ('run_group', models.CharField(blank=True, default='', max_length=100, verbose_name='运行组')),
                ('app_home', models.CharField(blank=True, default='', max_length=512, verbose_name='App Home')),
                ('work_directory', models.CharField(blank=True, default='', max_length=512, verbose_name='工作目录')),
                ('service_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Systemd 服务名')),
                ('ha_system_name', models.CharField(blank=True, default='', max_length=128, verbose_name='HA 系统名称')),
                ('ha_cluster_name', models.CharField(blank=True, default='', max_length=128, verbose_name='HA 集群名称')),
                ('ha_resource_name', models.CharField(blank=True, default='', max_length=128, verbose_name='HA 资源名称')),
                ('enabled', models.BooleanField(default=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_deployments', to='assets.host')),
                ('application_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='assets.applicationversion')),
            ],
            options={
                'db_table': 'assets_application_deployment',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DockerComposeControlConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('project_name', models.CharField(max_length=255)),
                ('service_name', models.CharField(max_length=255)),
                ('compose_file_path', models.CharField(max_length=512)),
                ('working_directory', models.CharField(max_length=512)),
                ('env_file', models.CharField(blank=True, default='', max_length=512)),
                ('expected_image', models.CharField(blank=True, default='', max_length=255)),
                ('expected_image_tag', models.CharField(blank=True, default='', max_length=128)),
                ('deployment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compose_config', to='assets.applicationdeployment')),
            ],
            options={
                'db_table': 'assets_docker_compose_control_config',
            },
        ),
        migrations.CreateModel(
            name='DockerControlConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('container_name', models.CharField(max_length=255)),
                ('docker_host', models.CharField(blank=True, default='unix:///var/run/docker.sock', max_length=255)),
                ('expected_image', models.CharField(blank=True, default='', max_length=255)),
                ('expected_image_tag', models.CharField(blank=True, default='', max_length=128)),
                ('deployment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docker_config', to='assets.applicationdeployment')),
            ],
            options={
                'db_table': 'assets_docker_control_config',
            },
        ),
        migrations.CreateModel(
            name='ApplicationControlAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('action', models.CharField(choices=[('start', '启动'), ('stop', '停止'), ('status', '状态'), ('restart', '重启'), ('reload', '重载')], max_length=16)),
                ('command', models.TextField()),
                ('timeout_seconds', models.PositiveIntegerField(default=60)),
                ('success_exit_codes', models.JSONField(blank=True, default=list)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_actions', to='assets.applicationdeployment')),
            ],
            options={
                'db_table': 'assets_application_control_action',
                'ordering': ['deployment_id', 'id'],
                'constraints': [models.UniqueConstraint(fields=('deployment', 'action'), name='unique_deployment_control_action')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationConfigFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=128)),
                ('path', models.CharField(max_length=512)),
                ('file_format', models.CharField(choices=[('xml', 'XML'), ('yaml', 'YAML'), ('json', 'JSON'), ('ini', 'INI'), ('properties', 'Properties'), ('text', '文本')], default='text', max_length=16)),
                ('required', models.BooleanField(default=True)),
                ('baseline_enabled', models.BooleanField(default=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_files', to='assets.applicationdeployment')),
            ],
            options={
                'db_table': 'assets_application_config_file',
                'ordering': ['deployment_id', 'id'],
                'constraints': [models.UniqueConstraint(fields=('deployment', 'path'), name='unique_deployment_config_path')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationLogDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=128)),
                ('path_pattern', models.CharField(max_length=512)),
                ('encoding', models.CharField(default='utf-8', max_length=32)),
                ('collection_enabled', models.BooleanField(default=False)),
                ('retention_days', models.PositiveIntegerField(default=30)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='assets.applicationdeployment')),
            ],
            options={
                'db_table': 'assets_application_log_definition',
                'ordering': ['deployment_id', 'id'],
                'constraints': [models.UniqueConstraint(fields=('deployment', 'name'), name='unique_deployment_log_name')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=64)),
                ('path_type', models.CharField(choices=[('home', 'Home 目录'), ('bin', 'Bin 目录'), ('config', '配置目录'), ('data', '数据目录'), ('log', '日志目录'), ('pid', 'PID 文件'), ('executable', '可执行文件'), ('other', '其他')], max_length=16)),
                ('path', models.CharField(max_length=512)),
                ('required', models.BooleanField(default=True)),
                ('expected_owner', models.CharField(blank=True, default='', max_length=100)),
                ('expected_group', models.CharField(blank=True, default='', max_length=100)),
                ('expected_mode', models.CharField(blank=True, default='', max_length=8)),
                ('check_enabled', models.BooleanField(default=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='assets.applicationdeployment')),
            ],
            options={
                'db_table': 'assets_application_path',
                'ordering': ['deployment_id', 'path_type', 'id'],
                'constraints': [models.UniqueConstraint(fields=('deployment', 'name'), name='unique_deployment_path_name')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=64)),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP')], default='tcp', max_length=8)),
                ('bind_address', models.CharField(blank=True, default='0.0.0.0', max_length=255)),
                ('port', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('required', models.BooleanField(default=True)),
                ('external_access', models.BooleanField(default=False)),
                ('check_enabled', models.BooleanField(default=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='assets.applicationdeployment')),
            ],
            options={
                'db_table': 'assets_application_port',
                'ordering': ['deployment_id', 'protocol', 'port'],
                'constraints': [models.UniqueConstraint(fields=('deployment', 'protocol', 'port'), name='unique_deployment_protocol_port')],
            },
        ),
        migrations.AddConstraint(
            model_name='applicationversion',
            constraint=models.UniqueConstraint(fields=('application', 'version'), name='unique_application_version'),
        ),
        migrations.AddConstraint(
            model_name='applicationdeployment',
            constraint=models.UniqueConstraint(fields=('host', 'instance_name'), name='unique_host_application_instance'),
        ),
        migrations.RunPython(migrate_application_versions, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='application',
            name='version',
        ),
    ]
