# Generated by Django 5.1.4 on 2026-08-22 01:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0041_require_application_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdeployment',
            name='baseline_pass_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationdeployment',
            name='health_status',
            field=models.CharField(choices=[('unknown', '未检查'), ('checking', '检查中'), ('healthy', '正常'), ('unhealthy', '异常'), ('error', '检查失败')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='applicationdeployment',
            name='last_check_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ApplicationBaselineExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('status', models.CharField(choices=[('queued', '等待中'), ('running', '检查中'), ('completed', '已完成'), ('failed', '执行失败')], default='queued', max_length=16)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('passed_count', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('requested_user_id', models.IntegerField(blank=True, null=True)),
                ('requested_username', models.CharField(blank=True, default='', max_length=100)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('agent_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_baseline_execution', to='assets.agentjob')),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_executions', to='assets.applicationdeployment')),
            ],
            options={
                'db_table': 'assets_application_baseline_execution',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationBaselineResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('check_key', models.CharField(max_length=255)),
                ('check_type', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pass', '通过'), ('fail', '失败'), ('error', '错误'), ('skipped', '跳过')], max_length=16)),
                ('expected_value', models.JSONField(blank=True, null=True)),
                ('actual_value', models.JSONField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assets.applicationbaselineexecution')),
            ],
            options={
                'db_table': 'assets_application_baseline_result',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['execution', 'status'], name='assets_appl_executi_a589da_idx'), models.Index(fields=['check_type', 'status'], name='assets_appl_check_t_b752c7_idx')],
            },
        ),
    ]
