# Generated by Django 5.1.4 on 2026-08-22 10:19

import assets.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0047_tomcat_manager_context_xml_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomcatbaselineconfig',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tomcatbaselineconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tomcatbaselineconfig',
            name='remark',
            field=models.TextField(blank=True, default='', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='tomcatbaselineconfig',
            name='required_roles',
            field=models.JSONField(blank=True, default=assets.models.default_tomcat_manager_roles),
        ),
        migrations.AlterField(
            model_name='tomcatbaselineconfig',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
