# Generated by Django 5.1.4 on 2026-08-23 03:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0065_application_deployment_runtime_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='业务系统名称')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='业务系统编码')),
                ('owner', models.CharField(blank=True, default='', max_length=128, verbose_name='负责人')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'db_table': 'assets_business_system',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='applicationdeployment',
            name='business_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='assets.businesssystem', verbose_name='所属业务系统'),
        ),
    ]
