# Generated by Django 5.1.4 on 2026-08-23 03:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0066_businesssystem_alter_application_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdeployment',
            name='member_role',
            field=models.CharField(blank=True, default='standalone', max_length=64, verbose_name='成员角色'),
        ),
        migrations.AlterField(
            model_name='applicationdeployment',
            name='business_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_deployments', to='assets.businesssystem'),
        ),
        migrations.CreateModel(
            name='ApplicationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=128, verbose_name='逻辑服务名称')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='逻辑服务编码')),
                ('environment', models.CharField(choices=[('production', '生产'), ('testing', '测试'), ('development', '开发'), ('other', '其他')], default='production', max_length=16)),
                ('topology_type', models.CharField(choices=[('standalone', '单机'), ('cluster', '集群')], default='standalone', max_length=16)),
                ('availability_mode', models.CharField(choices=[('none', '无高可用'), ('active_standby', '主备'), ('active_active', '双活')], default='none', max_length=24)),
                ('access_type', models.CharField(choices=[('direct', '节点地址'), ('vip', 'VIP'), ('load_balancer', '负载均衡')], default='direct', max_length=24)),
                ('access_address', models.CharField(blank=True, default='', max_length=255, verbose_name='服务入口地址')),
                ('access_port', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='assets.application')),
                ('business_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='assets.businesssystem', verbose_name='所属业务系统')),
            ],
            options={
                'db_table': 'assets_application_service',
                'ordering': ['business_system_id', 'environment', 'name'],
            },
        ),
        migrations.AddField(
            model_name='applicationdeployment',
            name='application_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='assets.applicationservice'),
        ),
        migrations.CreateModel(
            name='ClusterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='集群模型名称')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='集群模型编码')),
                ('profile_type', models.CharField(choices=[('builtin', '内置'), ('custom', '自定义')], default='custom', max_length=16)),
                ('management_mode', models.CharField(choices=[('agent', 'Agent 管理'), ('external', '外部系统管理')], default='agent', max_length=16)),
                ('role_definitions', models.JSONField(blank=True, default=list, verbose_name='成员角色定义')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cluster_profiles', to='assets.application', verbose_name='限定应用')),
            ],
            options={
                'db_table': 'assets_cluster_profile',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='applicationservice',
            name='cluster_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='assets.clusterprofile', verbose_name='集群模型'),
        ),
        migrations.AddConstraint(
            model_name='applicationservice',
            constraint=models.UniqueConstraint(fields=('business_system', 'environment', 'name'), name='unique_business_environment_service'),
        ),
    ]
