# Generated by Django 5.1.4 on 2026-08-23 03:43

import django.db.models.deletion
from django.db import migrations, models


def create_services_for_existing_deployments(apps, schema_editor):
    ApplicationDeployment = apps.get_model('assets', 'ApplicationDeployment')
    ApplicationService = apps.get_model('assets', 'ApplicationService')

    for deployment in ApplicationDeployment.objects.select_related('application_version').all():
        service = ApplicationService.objects.create(
            business_system_id=deployment.business_system_id,
            application_id=deployment.application_version.application_id,
            name=deployment.instance_name,
            code=f'deployment-{deployment.id}',
            environment=deployment.environment,
            topology_type='standalone',
            availability_mode='none',
            access_type='direct',
            enabled=deployment.enabled,
            remark='由现有部署实例迁移生成',
        )
        deployment.application_service_id = service.id
        deployment.member_role = 'standalone'
        deployment.save(update_fields=['application_service', 'member_role'])


def restore_deployment_ownership(apps, schema_editor):
    ApplicationDeployment = apps.get_model('assets', 'ApplicationDeployment')

    for deployment in ApplicationDeployment.objects.select_related('application_service').all():
        service = deployment.application_service
        deployment.business_system_id = service.business_system_id
        deployment.environment = service.environment
        deployment.save(update_fields=['business_system', 'environment'])


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0067_applicationdeployment_member_role_and_more'),
    ]

    operations = [
        migrations.RunPython(create_services_for_existing_deployments, restore_deployment_ownership),
        migrations.RemoveField(
            model_name='applicationdeployment',
            name='business_system',
        ),
        migrations.RemoveField(
            model_name='applicationdeployment',
            name='environment',
        ),
        migrations.AlterField(
            model_name='applicationdeployment',
            name='application_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='assets.applicationservice'),
        ),
    ]
