# Generated by Django 5.1.4 on 2026-08-23 05:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def seed_builtin_cluster_profiles(apps, schema_editor):
    ClusterProfile = apps.get_model('assets', 'ClusterProfile')
    builtin_profiles = (
        ('mysql', 'MySQL 集群', 'mysql', 'agent'),
        ('redis', 'Redis 集群', 'redis', 'agent'),
        ('elasticsearch', 'Elasticsearch 集群', 'elasticsearch', 'agent'),
        ('ha', 'HA 集群', 'ha', 'external'),
    )
    for code, name, cluster_type, management_mode in builtin_profiles:
        ClusterProfile.objects.update_or_create(
            code=code,
            defaults={
                'name': name,
                'profile_type': 'builtin',
                'management_mode': management_mode,
                'cluster_type': cluster_type,
                'enabled': True,
            },
        )

    for profile in ClusterProfile.objects.exclude(code__in=[item[0] for item in builtin_profiles]):
        identity = f'{profile.code} {profile.name}'.lower()
        if 'mysql' in identity:
            profile.cluster_type = 'mysql'
        elif 'redis' in identity:
            profile.cluster_type = 'redis'
        elif 'elastic' in identity or 'es ' in f'{identity} ':
            profile.cluster_type = 'elasticsearch'
        elif 'ha' in identity:
            profile.cluster_type = 'ha'
        else:
            profile.cluster_type = 'custom'
        profile.save(update_fields=['cluster_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0068_remove_applicationdeployment_business_system_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdeployment',
            name='member_role',
        ),
        migrations.RemoveField(
            model_name='clusterprofile',
            name='role_definitions',
        ),
        migrations.AddField(
            model_name='applicationdeployment',
            name='member_port',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='集群成员端口'),
        ),
        migrations.AddField(
            model_name='clusterprofile',
            name='cluster_type',
            field=models.CharField(choices=[('mysql', 'MySQL 集群'), ('redis', 'Redis 集群'), ('elasticsearch', 'Elasticsearch 集群'), ('ha', 'HA 集群'), ('custom', '自定义集群')], default='custom', max_length=24),
        ),
        migrations.AlterField(
            model_name='applicationdeployment',
            name='application_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='assets.applicationservice'),
        ),
        migrations.RunPython(seed_builtin_cluster_profiles, migrations.RunPython.noop),
    ]
