# Generated by Django 5.1.4 on 2026-08-23 05:52

import django.db.models.deletion
from django.db import migrations, models


def bind_cluster_profiles_to_applications(apps, schema_editor):
    Application = apps.get_model('assets', 'Application')
    ClusterProfile = apps.get_model('assets', 'ClusterProfile')
    builtin_applications = {
        'mysql': ('MySQL', 'database'),
        'redis': ('Redis', 'database'),
        'elasticsearch': ('Elasticsearch', 'middleware'),
        'ha': ('HA', 'other'),
    }

    for profile_code, (application_name, category) in builtin_applications.items():
        profile = ClusterProfile.objects.filter(code=profile_code, application__isnull=True).first()
        if profile is None:
            continue
        application, _ = Application.objects.get_or_create(
            code=profile_code,
            defaults={
                'name': application_name,
                'category': category,
                'enabled': True,
            },
        )
        profile.application = application
        profile.save(update_fields=['application'])

    unbound_codes = list(
        ClusterProfile.objects.filter(application__isnull=True).values_list('code', flat=True)
    )
    if unbound_codes:
        codes = ', '.join(sorted(unbound_codes))
        raise RuntimeError(f'集群模型必须先绑定应用，未绑定模型: {codes}')


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0069_remove_applicationdeployment_member_role_and_more'),
    ]

    operations = [
        migrations.RunPython(bind_cluster_profiles_to_applications, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='clusterprofile',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cluster_profiles', to='assets.application', verbose_name='应用'),
        ),
    ]
