# Generated by Django 5.1.4 on 2026-08-23 05:57

from django.db import migrations, models


def seed_nacos_cluster_profile(apps, schema_editor):
    Application = apps.get_model('assets', 'Application')
    ClusterProfile = apps.get_model('assets', 'ClusterProfile')
    application, _ = Application.objects.update_or_create(
        code='nacos',
        defaults={'name': 'Nacos', 'category': 'middleware', 'enabled': True},
    )
    ClusterProfile.objects.update_or_create(
        code='nacos',
        defaults={
            'name': 'Nacos 集群',
            'application': application,
            'profile_type': 'builtin',
            'cluster_type': 'nacos',
            'enabled': True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0070_alter_clusterprofile_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterprofile',
            name='cluster_type',
            field=models.CharField(choices=[('mysql', 'MySQL 集群'), ('redis', 'Redis 集群'), ('nacos', 'Nacos 集群'), ('elasticsearch', 'Elasticsearch 集群'), ('ha', 'HA 集群'), ('custom', '自定义集群')], default='custom', max_length=24),
        ),
        migrations.RunPython(seed_nacos_cluster_profile, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='clusterprofile',
            name='management_mode',
        ),
    ]
