# Generated by Django 5.1.4 on 2026-08-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0071_alter_clusterprofile_cluster_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationservice',
            name='baseline_pass_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationservice',
            name='health_status',
            field=models.CharField(choices=[('unknown', '未检查'), ('healthy', '正常'), ('unhealthy', '异常')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='applicationservice',
            name='last_check_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
