# Generated by Django 5.1.4 on 2026-08-23 06:14

import django.db.models.deletion
from django.db import migrations, models


def unbind_builtin_ha_application(apps, schema_editor):
    ClusterProfile = apps.get_model('assets', 'ClusterProfile')
    ClusterProfile.objects.filter(
        code='ha', profile_type='builtin', cluster_type='ha',
    ).update(application=None)


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0072_applicationservice_baseline_pass_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusterprofile',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cluster_profiles', to='assets.application', verbose_name='应用'),
        ),
        migrations.RunPython(unbind_builtin_ha_application, migrations.RunPython.noop),
    ]
