# Generated by Django 5.1.4 on 2026-08-23 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0074_remove_orphan_ha_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationservice',
            name='primary_deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_services', to='assets.applicationdeployment', verbose_name='VIP 主节点'),
        ),
    ]
