# Generated by Django 5.1.4 on 2026-08-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0084_application_service_deployment_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationservicedeployment',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
