# Generated by Django 5.1.4 on 2026-08-24 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0085_alter_applicationservicedeployment_update_time'),
        ('assets', '0085_remove_applicationservicedeployment_application_port'),
    ]

    operations = [
    ]
