# Generated by Django 5.1.4 on 2026-08-24 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0086_merge_20260824_1327'),
        ('assets', '0086_remove_applicationservice_access_port'),
    ]

    operations = [
    ]
