# Generated by Django 5.1.4 on 2026-08-25 02:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0090_alter_applicationservice_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='项目名称')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='项目编码')),
                ('owner', models.CharField(blank=True, default='', max_length=128, verbose_name='负责人')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('business_systems', models.ManyToManyField(blank=True, related_name='projects', to='assets.businesssystem', verbose_name='关联业务系统')),
            ],
            options={
                'db_table': 'assets_project',
                'ordering': ['name', 'id'],
            },
        ),
    ]
