# Generated by Django 5.1.4 on 2026-08-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0091_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdeploymenttemplate',
            name='macro_definitions',
            field=models.JSONField(blank=True, default=list, verbose_name='宏定义'),
        ),
        migrations.AddField(
            model_name='applicationservice',
            name='macro_values',
            field=models.JSONField(blank=True, default=dict, verbose_name='宏值'),
        ),
    ]
