# Generated by Django 5.1.4 on 2026-08-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0093_host_environment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationlogdefinition',
            name='retention_days',
        ),
        migrations.AddField(
            model_name='applicationlogdefinition',
            name='extra_fields',
            field=models.JSONField(blank=True, default=dict, verbose_name='附加标签'),
        ),
        migrations.AddField(
            model_name='applicationlogdefinition',
            name='ingest_pipeline',
            field=models.CharField(blank=True, default='', help_text='OpenSearch pipeline 名，留空按 app-<application.code>-<log_name> 约定生成', max_length=128, verbose_name='Ingest Pipeline'),
        ),
        migrations.AddField(
            model_name='applicationlogdefinition',
            name='multiline_parser',
            field=models.CharField(blank=True, default='', help_text='Fluent Bit 内置 multiline parser 名（如 java），留空表示单行日志', max_length=64, verbose_name='多行解析器'),
        ),
        migrations.AddField(
            model_name='applicationservice',
            name='log_collection_enabled',
            field=models.BooleanField(default=False, verbose_name='开启日志采集'),
        ),
        migrations.AddField(
            model_name='applicationservice',
            name='log_retention_tier',
            field=models.CharField(choices=[('hot', '热（7 天）'), ('std', '标准（30 天）'), ('cold', '冷（90 天）')], default='std', max_length=8, verbose_name='日志保留档位'),
        ),
    ]
