# Generated by Django 5.1.4 on 2026-08-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0094_remove_applicationlogdefinition_retention_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostsystem',
            name='os_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='hostsystem',
            name='os_id_like',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='hostsystem',
            name='os_version_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
