# Generated by Django 5.1.4 on 2026-08-27 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0095_hostsystem_os_id_hostsystem_os_id_like_and_more'),
        ('monitor', '0059_logprocessingrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationlogdefinition',
            name='ingest_pipeline',
        ),
        migrations.RemoveField(
            model_name='applicationlogdefinition',
            name='multiline_parser',
        ),
        migrations.AddField(
            model_name='applicationlogdefinition',
            name='processing_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='log_definitions', to='monitor.logprocessingrule', verbose_name='日志处理规则'),
        ),
    ]
