# Generated by Django 5.1.4 on 2026-08-28 07:37

import django.db.models.deletion
from django.db import migrations, models


def forwards_assign_project(apps, schema_editor):
    """M2M -> FK：把 project.business_systems 的关联落到 business_system.project。"""
    Project = apps.get_model('assets', 'Project')
    for project in Project.objects.order_by('id'):
        for business_system in project.business_systems.all():
            # 历史数据允许一个业务系统挂多个项目，按项目 id 升序取第一个，保证迁移结果可复现。
            if business_system.project_id is None:
                business_system.project_id = project.id
                business_system.save(update_fields=['project'])


def backwards_restore_m2m(apps, schema_editor):
    Project = apps.get_model('assets', 'Project')
    BusinessSystem = apps.get_model('assets', 'BusinessSystem')
    for business_system in BusinessSystem.objects.exclude(project_id=None):
        Project.objects.get(pk=business_system.project_id).business_systems.add(business_system)


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0097_applicationservice_log_retention_tier_fk'),
    ]

    operations = [
        # 先用 related_name='+' 落列，避免与仍然存在的 Project.business_systems 反向名冲突；
        # 数据搬完并删掉 M2M 后，再改回正式反向名。
        migrations.AddField(
            model_name='businesssystem',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assets.project', verbose_name='所属项目'),
        ),
        migrations.RunPython(forwards_assign_project, backwards_restore_m2m),
        migrations.RemoveField(
            model_name='project',
            name='business_systems',
        ),
        migrations.AlterField(
            model_name='businesssystem',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_systems', to='assets.project', verbose_name='所属项目'),
        ),
    ]
