# Generated by Django 5.1.4 on 2026-08-28 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0098_remove_project_business_systems_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationBaselineCheck',
        ),
    ]
