# Generated by Django 5.1.4 on 2026-08-28 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0099_delete_applicationbaselinecheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationbaselineresult',
            name='execution',
        ),
        migrations.RemoveField(
            model_name='applicationconfigfile',
            name='baseline_enabled',
        ),
        migrations.RemoveField(
            model_name='applicationdeployment',
            name='baseline_pass_rate',
        ),
        migrations.RemoveField(
            model_name='applicationdeployment',
            name='health_status',
        ),
        migrations.RemoveField(
            model_name='applicationdeployment',
            name='last_check_time',
        ),
        migrations.RemoveField(
            model_name='applicationservice',
            name='baseline_pass_rate',
        ),
        migrations.RemoveField(
            model_name='applicationservice',
            name='health_status',
        ),
        migrations.RemoveField(
            model_name='applicationservice',
            name='last_check_time',
        ),
        migrations.DeleteModel(
            name='ApplicationBaselineExecution',
        ),
        migrations.DeleteModel(
            name='ApplicationBaselineResult',
        ),
    ]
