# Generated by Django 5.1.4 on 2026-08-30 03:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0100_remove_applicationbaselineresult_execution_and_more'),
        ('monitor', '0063_alerthistory_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationServiceLogSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('collection_enabled', models.BooleanField(blank=True, null=True, verbose_name='采集开关')),
                ('log_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_overrides', to='assets.applicationlogdefinition')),
                ('retention_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_log_settings', to='monitor.logretentiontier', verbose_name='日志保留档位')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_settings', to='assets.applicationservice')),
            ],
            options={
                'db_table': 'assets_application_service_log_setting',
                'ordering': ['service_id', 'log_definition_id'],
                'constraints': [models.UniqueConstraint(fields=('service', 'log_definition'), name='unique_service_log_setting')],
            },
        ),
    ]
