# Generated by Django 5.1.4 on 2026-08-30 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0101_applicationservicelogsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationlogdefinition',
            name='encoding',
        ),
    ]
