# Generated by Django 5.1.4 on 2026-08-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0102_remove_applicationlogdefinition_encoding'),
        ('monitor', '0063_alerthistory_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationservicelogsetting',
            name='processing_rule',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='service_log_settings',
                to='monitor.logprocessingrule',
                verbose_name='日志处理规则',
            ),
        ),
    ]
