# Generated by Django 5.1.4 on 2026-08-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0103_applicationservicelogsetting_processing_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationservicelogsetting',
            name='collection_mode',
            field=models.CharField(
                blank=True,
                choices=[('all', '全量'), ('error_only', '仅错误'), ('custom', '自定义过滤')],
                default='all',
                max_length=16,
                verbose_name='采集策略',
            ),
        ),
        migrations.AddField(
            model_name='applicationservicelogsetting',
            name='filter_pattern',
            field=models.TextField(blank=True, default='', verbose_name='过滤正则'),
        ),
    ]