# Generated by Django 5.1.4 on 2026-08-30 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0104_applicationservicelogsetting_collection_mode'),
        ('monitor', '0064_logcollectionfilterrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationservicelogsetting',
            name='collection_mode',
        ),
        migrations.RemoveField(
            model_name='applicationservicelogsetting',
            name='filter_pattern',
        ),
        migrations.AddField(
            model_name='applicationservicelogsetting',
            name='collection_filter_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_log_settings', to='monitor.logcollectionfilterrule', verbose_name='采集过滤规则'),
        ),
    ]
