# Generated by Django 5.1.4 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('assets', '0104_applicationservicelogsetting_collection_mode')]

    operations = [
        migrations.AlterField(model_name='businesssystem', name='name', field=models.CharField(max_length=128, verbose_name='业务系统名称')),
        migrations.AlterField(model_name='businesssystem', name='code', field=models.CharField(max_length=64, verbose_name='业务系统编码')),
        migrations.AddConstraint(model_name='businesssystem', constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_project_business_system_name')),
        migrations.AddConstraint(model_name='businesssystem', constraint=models.UniqueConstraint(fields=('project', 'code'), name='unique_project_business_system_code')),
    ]