# Generated by Django 5.1.4 on 2026-08-30 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0105_businesssystem_project_scoped_unique'),
        ('assets', '0105_remove_applicationservicelogsetting_collection_mode_and_more'),
    ]

    operations = [
    ]
