CREATE TABLE sys_role (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name varchar(30) DEFAULT NULL,
  code varchar(100) DEFAULT NULL,
  create_time date DEFAULT NULL,
  update_time date DEFAULT NULL,
  remark varchar(500) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE sys_user (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  username varchar(100) NOT NULL,
  password varchar(100) NOT NULL,
  avatar varchar(255) DEFAULT NULL,
  phonenumber varchar(11) DEFAULT NULL,
  login_date timestamp(6) DEFAULT NULL,
  status smallint NOT NULL,
  create_time date DEFAULT NULL,
  update_time date DEFAULT NULL,
  remark varchar(500) DEFAULT NULL,
  timezone varchar(50) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT username UNIQUE (username)
);

CREATE TABLE sys_menu (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name varchar(50) NOT NULL,
  icon varchar(100) DEFAULT NULL,
  parent_id integer DEFAULT NULL,
  order_num integer DEFAULT NULL,
  path varchar(200) DEFAULT NULL,
  component varchar(255) DEFAULT NULL,
  menu_type varchar(1) DEFAULT NULL,
  perms varchar(100) DEFAULT NULL,
  create_time date DEFAULT NULL,
  update_time date DEFAULT NULL,
  remark varchar(500) DEFAULT NULL,
  location smallint NOT NULL,
  is_expanded boolean NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT sys_menu_name UNIQUE (name)
);

CREATE TABLE sys_user_role (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  role_id integer NOT NULL,
  user_id integer NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT sys_user_role_user_id_role_id_ec6ef495_uniq UNIQUE (user_id, role_id),
  CONSTRAINT sys_user_role_role_id_63624973_fk_sys_role_id FOREIGN KEY (role_id) REFERENCES sys_role (id),
  CONSTRAINT sys_user_role_user_id_5f2fb964_fk_sys_user_id FOREIGN KEY (user_id) REFERENCES sys_user (id)
);

CREATE INDEX sys_user_role_role_id_63624973_fk_sys_role_id ON sys_user_role (role_id);

CREATE TABLE sys_role_menu (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  menu_id integer NOT NULL,
  role_id integer NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT sys_role_menu_menu_id_role_id_607d95aa_uniq UNIQUE (menu_id, role_id),
  CONSTRAINT sys_role_menu_menu_id_5c7ca896_fk_menu_sysmenu_id FOREIGN KEY (menu_id) REFERENCES sys_menu (id),
  CONSTRAINT sys_role_menu_role_id_e0dcb43b_fk_sys_role_id FOREIGN KEY (role_id) REFERENCES sys_role (id)
);

CREATE INDEX sys_role_menu_role_id_e0dcb43b_fk_sys_role_id ON sys_role_menu (role_id);

CREATE TABLE sys_agent_token (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  agent_id varchar(128) NOT NULL,
  token_hash varchar(255) NOT NULL,
  name varchar(128) DEFAULT NULL,
  is_active boolean NOT NULL,
  expires_at timestamp(6) DEFAULT NULL,
  last_used_at timestamp(6) DEFAULT NULL,
  remark varchar(500) DEFAULT NULL,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  created_by_id integer DEFAULT NULL,
  bind_mode varchar(32) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT sys_agent_token_created_by_id_526bb742_fk_sys_user_id FOREIGN KEY (created_by_id) REFERENCES sys_user (id)
);

CREATE INDEX sys_agent_token_created_by_id_526bb742_fk_sys_user_id ON sys_agent_token (created_by_id);

CREATE TABLE monitor_alert_media (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(128) NOT NULL,
  media_type varchar(16) NOT NULL,
  config jsonb NOT NULL,
  enabled boolean NOT NULL,
  recipients jsonb NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT monitor_alert_media_name_uniq UNIQUE (name)
);

CREATE TABLE sys_user_alert_media (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  sysuser_id integer NOT NULL,
  alertmedia_id bigint NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT sys_user_alert_media_sysuser_id_alertmedia_id_5ab059c5_uniq UNIQUE (sysuser_id, alertmedia_id),
  CONSTRAINT sys_user_alert_media_alertmedia_id_c286c9b1_fk_monitor_a FOREIGN KEY (alertmedia_id) REFERENCES monitor_alert_media (id),
  CONSTRAINT sys_user_alert_media_sysuser_id_29476095_fk_sys_user_id FOREIGN KEY (sysuser_id) REFERENCES sys_user (id)
);

CREATE INDEX sys_user_alert_media_alertmedia_id_c286c9b1_fk_monitor_a ON sys_user_alert_media (alertmedia_id);

CREATE TABLE sys_config (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  key varchar(128) NOT NULL,
  value text NOT NULL,
  value_type varchar(16) NOT NULL,
  name varchar(128) NOT NULL,
  description text,
  is_readonly boolean NOT NULL,
  default_value text,
  PRIMARY KEY (id),
  CONSTRAINT key UNIQUE (key)
);

CREATE TABLE audit_login_log (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  username varchar(150) NOT NULL,
  user_id integer DEFAULT NULL,
  status varchar(16) NOT NULL,
  client_ip varchar(64) NOT NULL,
  user_agent varchar(255) NOT NULL,
  message varchar(255) NOT NULL,
  login_time timestamp(6) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE audit_operation_log (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  username varchar(150) NOT NULL,
  user_id integer DEFAULT NULL,
  method varchar(16) NOT NULL,
  path varchar(255) NOT NULL,
  route_name varchar(255) NOT NULL,
  client_ip varchar(64) NOT NULL,
  user_agent varchar(255) NOT NULL,
  status_code integer NOT NULL,
  duration_ms integer DEFAULT NULL,
  message varchar(255) NOT NULL,
  created_at timestamp(6) NOT NULL,
  request_data text NOT NULL,
  response_data text NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE scheduler_scheduledtask (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(128) NOT NULL,
  code varchar(128) NOT NULL,
  description varchar(255) DEFAULT NULL,
  enabled boolean NOT NULL,
  interval_minutes integer DEFAULT NULL,
  last_run_time timestamp(6) DEFAULT NULL,
  last_status varchar(32) DEFAULT NULL,
  last_message text,
  menu_id integer DEFAULT NULL,
  next_run_time timestamp(6) DEFAULT NULL,
  is_running boolean NOT NULL,
  cron_expression varchar(120) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT scheduler_scheduledtask_name UNIQUE (name),
  CONSTRAINT scheduler_scheduledtask_code UNIQUE (code),
  CONSTRAINT scheduler_scheduledtask_menu_id_8b41dd60_fk_sys_menu_id FOREIGN KEY (menu_id) REFERENCES sys_menu (id)
);

CREATE INDEX scheduler_scheduledtask_menu_id_8b41dd60_fk_sys_menu_id ON scheduler_scheduledtask (menu_id);

CREATE TABLE scheduler_scheduledtasklog (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  run_time timestamp(6) NOT NULL,
  status varchar(32) NOT NULL,
  message text,
  duration_seconds double precision DEFAULT NULL,
  task_id bigint NOT NULL,
  output text,
  PRIMARY KEY (id),
  CONSTRAINT scheduler_scheduledtasklog_scheduler_scheduledt_task_id_a41cf2a FOREIGN KEY (task_id) REFERENCES scheduler_scheduledtask (id)
);

CREATE INDEX scheduler_scheduledt_task_id_a41cf2ab_fk_scheduler ON scheduler_scheduledtasklog (task_id);

CREATE TABLE assets_webssh_session_log (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  user_id integer DEFAULT NULL,
  username varchar(100) NOT NULL,
  client_ip varchar(64) NOT NULL,
  user_agent varchar(255) NOT NULL,
  status varchar(16) NOT NULL,
  start_time timestamp(6) NOT NULL,
  end_time timestamp(6) DEFAULT NULL,
  duration_seconds integer DEFAULT NULL,
  close_code integer DEFAULT NULL,
  error_message text NOT NULL,
  input_bytes integer NOT NULL,
  command_count integer NOT NULL,
  host_id bigint NOT NULL,
  input_content text NOT NULL,
  output_content text NOT NULL,
  recorded_content_bytes integer NOT NULL,
  is_content_truncated boolean NOT NULL,
  effective_username varchar(100) NOT NULL,
  requested_username varchar(100) NOT NULL,
  switch_user_error text NOT NULL,
  switch_user_status varchar(16) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT assets_webssh_session_log_host_id_71c2140d_fk_assets_host_id FOREIGN KEY (host_id) REFERENCES assets_host (id)
);

CREATE INDEX assets_webssh_session_log_host_id_71c2140d_fk_assets_host_id ON assets_webssh_session_log (host_id);

CREATE TABLE sys_user_group (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(128) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT sys_user_group_name UNIQUE (name)
);

CREATE TABLE sys_user_group_member (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  group_id bigint NOT NULL,
  user_id integer NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT sys_user_group_member_group_user UNIQUE (group_id, user_id),
  CONSTRAINT fk_user_group_member_group FOREIGN KEY (group_id) REFERENCES sys_user_group (id) ON DELETE CASCADE,
  CONSTRAINT fk_user_group_member_user FOREIGN KEY (user_id) REFERENCES sys_user (id) ON DELETE CASCADE
);

CREATE INDEX idx_user_group_member_user ON sys_user_group_member (user_id);
