CREATE TABLE assets_project (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(128) NOT NULL,
  code varchar(64) NOT NULL,
  owner varchar(128) NOT NULL,
  enabled boolean NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT assets_project_name UNIQUE (name),
  CONSTRAINT assets_project_code UNIQUE (code)
);

CREATE TABLE assets_business_system (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(128) NOT NULL,
  code varchar(64) NOT NULL,
  owner varchar(128) NOT NULL,
  enabled boolean NOT NULL,
  project_id bigint DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT unique_project_business_system_name UNIQUE (project_id, name),
  CONSTRAINT unique_project_business_system_code UNIQUE (project_id, code),
  CONSTRAINT assets_business_system_project_fk FOREIGN KEY (project_id) REFERENCES assets_project (id)
);

CREATE TABLE assets_business_environment (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(64) NOT NULL,
  code varchar(32) NOT NULL,
  "order" integer NOT NULL,
  owner varchar(128) NOT NULL,
  enabled boolean NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT unique_business_environment_code UNIQUE (code),
  CONSTRAINT unique_business_environment_name UNIQUE (name)
);

CREATE TABLE assets_credential (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(200) DEFAULT NULL,
  password varchar(512) DEFAULT NULL,
  private_key text,
  auth_type integer NOT NULL,
  username varchar(128) NOT NULL,
  port integer NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE assets_hostgroup (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(128) NOT NULL,
  parent_id bigint DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT assets_hostgroup_name UNIQUE (name),
  CONSTRAINT assets_hostgroup_parent_fk FOREIGN KEY (parent_id) REFERENCES assets_hostgroup (id)
);

CREATE TABLE assets_host (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  status varchar(32) NOT NULL,
  instance_id varchar(128) DEFAULT NULL,
  ip varchar(39) DEFAULT NULL,
  is_deleted_in_cloud boolean NOT NULL,
  cloud_account_id bigint DEFAULT NULL,
  group_id bigint DEFAULT NULL,
  instance_name varchar(128) DEFAULT NULL,
  collect_status varchar(16) NOT NULL,
  collect_message text NOT NULL,
  collect_time timestamp(6) DEFAULT NULL,
  agent_online boolean NOT NULL,
  agent_online_time timestamp(6) DEFAULT NULL,
  webssh_default_username varchar(100) NOT NULL,
  webssh_login_users varchar(512) NOT NULL,
  environment_id bigint DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT assets_host_instance_name_uniq UNIQUE (instance_name),
  CONSTRAINT assets_host_group_fk FOREIGN KEY (group_id) REFERENCES assets_hostgroup (id),
  CONSTRAINT assets_host_environment_fk FOREIGN KEY (environment_id) REFERENCES assets_business_environment (id)
);

CREATE INDEX assets_host_ip_idx ON assets_host (ip);

CREATE INDEX assets_host_group_id_idx ON assets_host (group_id);

CREATE INDEX assets_host_environment_id_idx ON assets_host (environment_id);

CREATE TABLE assets_hostcredential (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  is_default boolean NOT NULL,
  credential_id bigint NOT NULL,
  host_id bigint NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT assets_hostcredential_host_credential_uniq UNIQUE (host_id, credential_id),
  CONSTRAINT assets_hostcredential_credential_fk FOREIGN KEY (credential_id) REFERENCES assets_credential (id),
  CONSTRAINT assets_hostcredential_host_fk FOREIGN KEY (host_id) REFERENCES assets_host (id)
);

CREATE TABLE assets_application (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(128) NOT NULL,
  category varchar(32) NOT NULL,
  code varchar(64) NOT NULL,
  description text NOT NULL,
  enabled boolean NOT NULL,
  vendor varchar(128) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT assets_application_code UNIQUE (code),
  CONSTRAINT assets_application_name_efca0489_uniq UNIQUE (name)
);

CREATE TABLE assets_application_version (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  version varchar(128) NOT NULL,
  release_date date DEFAULT NULL,
  end_of_support date DEFAULT NULL,
  enabled boolean NOT NULL,
  application_id bigint NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT unique_application_version UNIQUE (application_id, version),
  CONSTRAINT assets_application_version_application_fk FOREIGN KEY (application_id) REFERENCES assets_application (id)
);

CREATE TABLE assets_cluster_profile (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(128) NOT NULL,
  code varchar(64) NOT NULL,
  profile_type varchar(16) NOT NULL,
  enabled boolean NOT NULL,
  application_id bigint DEFAULT NULL,
  cluster_type varchar(24) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT assets_cluster_profile_name UNIQUE (name),
  CONSTRAINT assets_cluster_profile_code UNIQUE (code),
  CONSTRAINT assets_cluster_profile_application_fk FOREIGN KEY (application_id) REFERENCES assets_application (id)
);

CREATE TABLE assets_application_deployment_template (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(128) NOT NULL,
  control_type varchar(32) NOT NULL,
  run_user varchar(100) NOT NULL,
  run_group varchar(100) NOT NULL,
  app_home varchar(512) NOT NULL,
  work_directory varchar(512) NOT NULL,
  service_name varchar(255) NOT NULL,
  ha_system_name varchar(128) NOT NULL,
  ha_cluster_name varchar(128) NOT NULL,
  ha_resource_name varchar(128) NOT NULL,
  enabled boolean NOT NULL,
  application_id bigint NOT NULL,
  systemd_scope varchar(16) NOT NULL,
  macro_definitions jsonb NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT unique_application_deployment_template UNIQUE (application_id, name),
  CONSTRAINT assets_application_deployment_template_application_fk FOREIGN KEY (application_id) REFERENCES assets_application (id)
);

CREATE TABLE assets_application_port (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(64) NOT NULL,
  protocol varchar(8) NOT NULL,
  bind_address varchar(255) NOT NULL,
  port integer NOT NULL,
  required boolean NOT NULL,
  external_access boolean NOT NULL,
  check_enabled boolean NOT NULL,
  deployment_template_id bigint NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT unique_template_protocol_port UNIQUE (deployment_template_id, protocol, port),
  CONSTRAINT assets_application_port_template_fk FOREIGN KEY (deployment_template_id) REFERENCES assets_application_deployment_template (id)
);

CREATE TABLE assets_application_path (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(64) NOT NULL,
  path_type varchar(16) NOT NULL,
  path varchar(512) NOT NULL,
  required boolean NOT NULL,
  expected_owner varchar(100) NOT NULL,
  expected_group varchar(100) NOT NULL,
  expected_mode varchar(8) NOT NULL,
  check_enabled boolean NOT NULL,
  deployment_template_id bigint NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT unique_template_path_name UNIQUE (deployment_template_id, name),
  CONSTRAINT assets_application_path_template_fk FOREIGN KEY (deployment_template_id) REFERENCES assets_application_deployment_template (id)
);

CREATE TABLE assets_application_config_file (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(128) NOT NULL,
  path varchar(512) NOT NULL,
  file_format varchar(16) NOT NULL,
  required boolean NOT NULL,
  deployment_template_id bigint NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT unique_template_config_path UNIQUE (deployment_template_id, path),
  CONSTRAINT assets_application_config_file_template_fk FOREIGN KEY (deployment_template_id) REFERENCES assets_application_deployment_template (id)
);

CREATE TABLE assets_application_log_definition (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(128) NOT NULL,
  path_pattern varchar(512) NOT NULL,
  deployment_template_id bigint NOT NULL,
  extra_fields jsonb NOT NULL,
  processing_rule_id bigint DEFAULT NULL,
  -- 模板级采集过滤默认值（2026-09-19）：两条引用各自独立，NULL = 该方向不用过滤。
  filter_include_rule_id bigint DEFAULT NULL,
  filter_exclude_rule_id bigint DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT unique_template_log_name UNIQUE (deployment_template_id, name),
  CONSTRAINT assets_application_log_definition_template_fk FOREIGN KEY (deployment_template_id) REFERENCES assets_application_deployment_template (id)
);

CREATE TABLE assets_application_control_action (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  action varchar(16) NOT NULL,
  command text NOT NULL,
  timeout_seconds integer NOT NULL,
  success_exit_codes jsonb NOT NULL,
  deployment_template_id bigint NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT unique_template_control_action UNIQUE (deployment_template_id, action),
  CONSTRAINT assets_application_control_action_template_fk FOREIGN KEY (deployment_template_id) REFERENCES assets_application_deployment_template (id)
);

CREATE TABLE assets_docker_control_config (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  container_name varchar(255) NOT NULL,
  docker_host varchar(255) NOT NULL,
  expected_image varchar(255) NOT NULL,
  expected_image_tag varchar(128) NOT NULL,
  deployment_template_id bigint NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT assets_docker_control_config_deployment_id UNIQUE (deployment_template_id),
  CONSTRAINT assets_docker_control_config_template_fk FOREIGN KEY (deployment_template_id) REFERENCES assets_application_deployment_template (id)
);

CREATE TABLE assets_docker_compose_control_config (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  project_name varchar(255) NOT NULL,
  service_name varchar(255) NOT NULL,
  compose_file_path varchar(512) NOT NULL,
  working_directory varchar(512) NOT NULL,
  env_file varchar(512) NOT NULL,
  expected_image varchar(255) NOT NULL,
  expected_image_tag varchar(128) NOT NULL,
  deployment_template_id bigint NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT assets_docker_compose_control_config_deployment_id UNIQUE (deployment_template_id),
  CONSTRAINT assets_docker_compose_control_config_template_fk FOREIGN KEY (deployment_template_id) REFERENCES assets_application_deployment_template (id)
);

CREATE TABLE assets_application_service (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(128) NOT NULL,
  code varchar(64) NOT NULL,
  topology_type varchar(16) NOT NULL,
  access_address varchar(255) NOT NULL,
  enabled boolean NOT NULL,
  application_id bigint NOT NULL,
  cluster_profile_id bigint DEFAULT NULL,
  environment_id bigint DEFAULT NULL,
  application_version_id bigint NOT NULL,
  deployment_template_id bigint NOT NULL,
  business_system_id bigint NOT NULL,
  macro_values jsonb NOT NULL,
  log_collection_enabled boolean NOT NULL,
  log_retention_tier_id bigint DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT unique_business_environment_service_code UNIQUE (business_system_id, environment_id, code),
  CONSTRAINT unique_business_environment_service UNIQUE (business_system_id, environment_id, name),
  CONSTRAINT assets_application_service_application_fk FOREIGN KEY (application_id) REFERENCES assets_application (id),
  CONSTRAINT assets_application_service_version_fk FOREIGN KEY (application_version_id) REFERENCES assets_application_version (id),
  CONSTRAINT assets_application_service_template_fk FOREIGN KEY (deployment_template_id) REFERENCES assets_application_deployment_template (id),
  CONSTRAINT assets_application_service_system_fk FOREIGN KEY (business_system_id) REFERENCES assets_business_system (id)
);

CREATE TABLE assets_application_deployment (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  instance_name varchar(128) NOT NULL,
  enabled boolean NOT NULL,
  host_id bigint NOT NULL,
  last_status_check_time timestamp(6) DEFAULT NULL,
  runtime_status varchar(16) NOT NULL,
  runtime_status_output text NOT NULL,
  ha_role varchar(16) NOT NULL,
  runtime_variables jsonb NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT unique_host_application_instance UNIQUE (host_id, instance_name),
  CONSTRAINT assets_application_deployment_host_fk FOREIGN KEY (host_id) REFERENCES assets_host (id)
);

CREATE TABLE assets_application_service_deployment (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  enabled boolean NOT NULL,
  deployment_id bigint NOT NULL,
  service_id bigint NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT unique_application_service_deployment UNIQUE (service_id, deployment_id),
  CONSTRAINT assets_application_service_deployment_deployment_fk FOREIGN KEY (deployment_id) REFERENCES assets_application_deployment (id),
  CONSTRAINT assets_application_service_deployment_service_fk FOREIGN KEY (service_id) REFERENCES assets_application_service (id)
);

CREATE TABLE assets_application_service_log_setting (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  collection_enabled boolean DEFAULT NULL,
  log_definition_id bigint NOT NULL,
  retention_tier_id bigint DEFAULT NULL,
  service_id bigint NOT NULL,
  -- 采集过滤的服务级覆盖（2026-09-19），两列都是三态：NULL = 继承模板；0 = 显式关闭；>0 = 指定规则。
  -- 分两列是因为一条日志可以同时有白名单与黑名单（include_lines 先于 exclude_lines 生效）。
  -- **这两列不能挂外键**：0 是有效取值，挂上外键就会被当成"指向 id=0 的规则"，保存即报
  -- 「关联资产不存在」（真库上 include 列的 Django 时代外键已由迁移 000040 摘掉；规则被删/停用
  -- 由渲染侧降级成"该方向不过滤 + 下发告警"）。守卫见
  -- internal/assets/log_filter_rule_fk_guard_test.go。
  collection_filter_rule_id bigint DEFAULT NULL,
  collection_exclude_filter_rule_id bigint DEFAULT NULL,
  format_verified_at timestamp(6) DEFAULT NULL,
  format_verified_fingerprint varchar(64) NOT NULL DEFAULT '',
  format_verified_source varchar(16) NOT NULL DEFAULT '',
  format_verified_by varchar(150) NOT NULL DEFAULT '',
  PRIMARY KEY (id),
  CONSTRAINT unique_service_log_setting UNIQUE (service_id, log_definition_id),
  CONSTRAINT assets_application_service_log_setting_log_fk FOREIGN KEY (log_definition_id) REFERENCES assets_application_log_definition (id),
  CONSTRAINT assets_application_service_log_setting_service_fk FOREIGN KEY (service_id) REFERENCES assets_application_service (id)
);

CREATE TABLE assets_hostsystem (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  os_type varchar(64) DEFAULT NULL,
  os_version varchar(128) DEFAULT NULL,
  kernel_version varchar(128) DEFAULT NULL,
  hostname varchar(128) DEFAULT NULL,
  agent_version varchar(64) DEFAULT NULL,
  host_id bigint NOT NULL,
  collected_at timestamp(6) DEFAULT NULL,
  collector_source varchar(32) DEFAULT NULL,
  timezone_name varchar(64) DEFAULT NULL,
  utc_offset varchar(16) DEFAULT NULL,
  os_id varchar(64) DEFAULT NULL,
  os_id_like varchar(128) DEFAULT NULL,
  os_version_id varchar(64) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT assets_hostsystem_host_id UNIQUE (host_id),
  CONSTRAINT assets_hostsystem_host_id_94282b79_fk_assets_host_id FOREIGN KEY (host_id) REFERENCES assets_host (id)
);

CREATE TABLE assets_hosthardware (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  cpu_cores integer DEFAULT NULL,
  cpu_model varchar(255) DEFAULT NULL,
  memory_gb double precision DEFAULT NULL,
  disk_total_gb double precision DEFAULT NULL,
  architecture varchar(64) DEFAULT NULL,
  host_id bigint NOT NULL,
  collected_at timestamp(6) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT assets_hosthardware_host_id UNIQUE (host_id),
  CONSTRAINT assets_hosthardware_host_id_b48623b8_fk_assets_host_id FOREIGN KEY (host_id) REFERENCES assets_host (id)
);

CREATE TABLE agent_package (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  version varchar(64) NOT NULL,
  file varchar(512) NOT NULL,
  sha256 varchar(64) NOT NULL,
  size_bytes bigint NOT NULL,
  is_active boolean NOT NULL DEFAULT false,
  create_time timestamp(6) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE assets_agent_job (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  job_id varchar(128) NOT NULL,
  instance_name varchar(128) NOT NULL,
  job_type varchar(32) NOT NULL,
  action varchar(64) NOT NULL,
  params jsonb NOT NULL,
  timeout_seconds integer NOT NULL,
  status varchar(16) NOT NULL,
  picked_at timestamp(6) DEFAULT NULL,
  finished_at timestamp(6) DEFAULT NULL,
  result_data jsonb NOT NULL,
  error_message text NOT NULL,
  host_id bigint DEFAULT NULL,
  client_request_id varchar(128) DEFAULT NULL,
  exit_code integer NOT NULL,
  stderr text NOT NULL,
  stdout text NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT assets_agent_job_job_id UNIQUE (job_id),
  CONSTRAINT client_request_id UNIQUE (client_request_id),
  CONSTRAINT assets_agent_job_host_id_06d13414_fk_assets_host_id FOREIGN KEY (host_id) REFERENCES assets_host (id),
  CONSTRAINT assets_agent_job_chk_1 CHECK ((timeout_seconds >= 0))
);

CREATE INDEX assets_agent_job_host_id_06d13414_fk_assets_host_id ON assets_agent_job (host_id);

CREATE INDEX assets_agen_agent_i_ed2f13_idx ON assets_agent_job (instance_name, status);

CREATE INDEX assets_agen_status_d7c3d4_idx ON assets_agent_job (status, create_time);

CREATE TABLE assets_cloudaccount (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(128) NOT NULL,
  cloud_type varchar(32) NOT NULL,
  endpoint varchar(255) DEFAULT NULL,
  username varchar(128) DEFAULT NULL,
  password varchar(128) DEFAULT NULL,
  access_key varchar(128) DEFAULT NULL,
  secret_key varchar(128) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE assets_hostdisk (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  device varchar(64) NOT NULL,
  mount_point varchar(128) DEFAULT NULL,
  size_gb double precision DEFAULT NULL,
  used_gb double precision DEFAULT NULL,
  filesystem varchar(64) DEFAULT NULL,
  host_id bigint NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT assets_hostdisk_host_id_c1a29894_fk_assets_host_id FOREIGN KEY (host_id) REFERENCES assets_host (id)
);

CREATE INDEX assets_hostdisk_host_id_c1a29894_fk_assets_host_id ON assets_hostdisk (host_id);

CREATE TABLE assets_hostruntime (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  cpu_usage_percent double precision DEFAULT NULL,
  cpu_times jsonb NOT NULL,
  memory_usage_percent double precision DEFAULT NULL,
  memory jsonb NOT NULL,
  disk_io jsonb NOT NULL,
  os_uptime_seconds bigint DEFAULT NULL,
  os_boot_time timestamp(6) DEFAULT NULL,
  metrics_sample_window_ms integer DEFAULT NULL,
  static_fingerprint varchar(64) NOT NULL,
  collected_at timestamp(6) DEFAULT NULL,
  host_id bigint NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT assets_hostruntime_host_id UNIQUE (host_id),
  CONSTRAINT assets_hostruntime_host_id_c8ce3dd4_fk_assets_host_id FOREIGN KEY (host_id) REFERENCES assets_host (id),
  CONSTRAINT assets_hostruntime_chk_1 CHECK ((metrics_sample_window_ms >= 0))
);

CREATE TABLE assets_webssh_temp_credential (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  session_pk integer DEFAULT NULL,
  created_at timestamp(6) NOT NULL,
  credential_id bigint NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT credential_id UNIQUE (credential_id),
  CONSTRAINT assets_webssh_temp_c_credential_id_fc449ce0_fk_assets_cr FOREIGN KEY (credential_id) REFERENCES assets_credential (id)
);

CREATE INDEX assets_webssh_temp_credential_session_pk_70b0ba26 ON assets_webssh_temp_credential (session_pk);
-- 外键列的索引：MySQL 建外键时若没有可用索引会自动创建一个（`SHOW CREATE TABLE` 里能看到），
-- PG **不会**自动创建 —— 于是同一个查询在两侧的计划不同（实测：告警主机服务树归属的那条
-- JOIN 在 90k 行的 assets_application_service_deployment 上退化成 Seq Scan，21.5ms；
-- 补上 deployment_id 的索引后 0.18ms）。这里按 MySQL 的既有索引逐列补齐（P1-9）。
CREATE INDEX assets_application_service_application_id_idx ON assets_application_service (application_id);
CREATE INDEX assets_application_service_application_version_id_idx ON assets_application_service (application_version_id);
CREATE INDEX assets_application_service_deployment_template_id_idx ON assets_application_service (deployment_template_id);
CREATE INDEX assets_application_service_deployment_deployment_id_idx ON assets_application_service_deployment (deployment_id);
CREATE INDEX assets_application_service_log_setting_log_definition_id_idx ON assets_application_service_log_setting (log_definition_id);
CREATE INDEX assets_cluster_profile_application_id_idx ON assets_cluster_profile (application_id);
CREATE INDEX assets_hostcredential_credential_id_idx ON assets_hostcredential (credential_id);
CREATE INDEX assets_hostgroup_parent_id_idx ON assets_hostgroup (parent_id);
