CREATE TABLE inspection_target_execution (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  execution_id bigint NOT NULL,
  deployment_id bigint DEFAULT NULL,
  host_id bigint DEFAULT NULL,
  target_name varchar(255) NOT NULL,
  host_id_snapshot integer DEFAULT NULL,
  host_ip_snapshot varchar(64) NOT NULL,
  instance_name_snapshot varchar(128) NOT NULL,
  status varchar(16) NOT NULL,
  passed boolean DEFAULT NULL,
  error_message text NOT NULL,
  raw_result jsonb NOT NULL,
  start_time timestamp(6) DEFAULT NULL,
  end_time timestamp(6) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE monitor_target (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  exporter_type varchar(64) NOT NULL,
  managed_enabled boolean NOT NULL,
  install_status varchar(16) NOT NULL,
  install_message text NOT NULL,
  last_scrape_status varchar(16) NOT NULL,
  last_scrape_at timestamp(6) DEFAULT NULL,
  labels jsonb NOT NULL,
  host_id bigint NOT NULL,
  retry_count integer NOT NULL,
  last_dispatch_manual boolean NOT NULL,
  scrape_port integer NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT monitor_target_host_id_exporter_type_dfe9c277_uniq UNIQUE (host_id, exporter_type),
  CONSTRAINT monitor_target_host_fk FOREIGN KEY (host_id) REFERENCES assets_host (id)
);

CREATE TABLE monitor_log_retention_tier (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  code varchar(32) NOT NULL,
  name varchar(64) NOT NULL,
  daily_size_gb double precision NOT NULL,
  retention_days integer NOT NULL,
  rollover_min_index_age varchar(16) NOT NULL,
  enabled boolean NOT NULL,
  is_default boolean NOT NULL,
  remark text NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT monitor_log_retention_tier_code UNIQUE (code)
);

CREATE TABLE monitor_opensearch_cluster (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  name varchar(128) NOT NULL,
  hosts varchar(512) NOT NULL,
  username varchar(128) NOT NULL,
  password varchar(512) NOT NULL,
  verify_tls boolean NOT NULL,
  ca_cert text NOT NULL,
  index_prefix varchar(64) NOT NULL,
  request_timeout integer NOT NULL,
  enabled boolean NOT NULL,
  is_default boolean NOT NULL,
  last_check_time timestamp(6) DEFAULT NULL,
  last_check_success boolean DEFAULT NULL,
  last_check_message text NOT NULL,
  remark text NOT NULL,
  storage_sync_error text NOT NULL,
  storage_sync_status varchar(16) NOT NULL,
  storage_sync_time timestamp(6) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT monitor_opensearch_cluster_name UNIQUE (name)
);

CREATE TABLE monitor_log_processing_rule (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(128) NOT NULL,
  description varchar(500) NOT NULL,
  input_format varchar(16) NOT NULL,
  multiline_enabled boolean NOT NULL,
  start_pattern text NOT NULL,
  continuation_pattern text NOT NULL,
  flush_timeout integer NOT NULL,
  pipeline_body jsonb NOT NULL,
  cluster_id bigint NOT NULL,
  application_id bigint DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT monitor_log_processing_rule_name UNIQUE (name),
  CONSTRAINT monitor_log_processing_rule_cluster_fk FOREIGN KEY (cluster_id) REFERENCES monitor_opensearch_cluster (id)
);

CREATE TABLE monitor_log_collection_filter_rule (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(128) NOT NULL,
  description varchar(500) NOT NULL,
  pattern text NOT NULL,
  enabled boolean NOT NULL,
  application_id bigint DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT monitor_log_collection_filter_rule_name UNIQUE (name)
);

CREATE TABLE automation_playbook_template (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(128) NOT NULL,
  description varchar(255) NOT NULL,
  content text NOT NULL,
  category varchar(32) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT automation_playbook_template_name UNIQUE (name)
);

CREATE TABLE monitor_software_package (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(64) NOT NULL,
  version varchar(32) NOT NULL,
  os varchar(16) NOT NULL,
  arch varchar(16) NOT NULL,
  file varchar(255) NOT NULL,
  sha256 varchar(64) NOT NULL,
  size_bytes bigint NOT NULL,
  enabled boolean NOT NULL,
  service_file_content text NOT NULL,
  service_run_as_group varchar(100) NOT NULL,
  service_run_as_user varchar(100) NOT NULL,
  install_playbook_template_id bigint DEFAULT NULL,
  uninstall_playbook_template_id bigint DEFAULT NULL,
  work_directory varchar(255) NOT NULL,
  default_port integer NOT NULL,
  package_format varchar(16) NOT NULL,
  platform_family varchar(16) NOT NULL,
  platform_major varchar(16) NOT NULL,
  package_type varchar(16) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT monitor_software_package_uniq UNIQUE (package_type, name, version, os, arch, platform_family, platform_major),
  CONSTRAINT monitor_software_package_install_fk FOREIGN KEY (install_playbook_template_id) REFERENCES automation_playbook_template (id),
  CONSTRAINT monitor_software_package_uninstall_fk FOREIGN KEY (uninstall_playbook_template_id) REFERENCES automation_playbook_template (id)
);

CREATE TABLE monitor_target_install_history (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  action varchar(16) NOT NULL,
  trigger_type varchar(16) NOT NULL,
  status varchar(16) NOT NULL,
  host_id_snapshot integer DEFAULT NULL,
  host_name_snapshot varchar(128) NOT NULL,
  host_ip_snapshot varchar(64) NOT NULL,
  exporter_type_snapshot varchar(64) NOT NULL,
  summary_message text NOT NULL,
  stdout_snapshot text NOT NULL,
  stderr_snapshot text NOT NULL,
  error_message_snapshot text NOT NULL,
  result_summary_snapshot jsonb NOT NULL,
  requested_user_id_snapshot integer DEFAULT NULL,
  requested_username_snapshot varchar(100) NOT NULL,
  start_time timestamp(6) DEFAULT NULL,
  end_time timestamp(6) DEFAULT NULL,
  duration_seconds double precision DEFAULT NULL,
  host_id bigint DEFAULT NULL,
  target_id bigint DEFAULT NULL,
  log_collection_target_id bigint DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT monitor_target_install_history_target_fk FOREIGN KEY (target_id) REFERENCES monitor_target (id)
);

CREATE TABLE monitor_alert_history (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  fingerprint varchar(40) NOT NULL,
  alertname varchar(200) NOT NULL,
  severity varchar(32) NOT NULL,
  instance varchar(200) NOT NULL,
  labels jsonb NOT NULL,
  annotations jsonb NOT NULL,
  generator_url varchar(500) NOT NULL,
  state varchar(16) NOT NULL,
  started_at timestamp(6) NOT NULL,
  resolved_at timestamp(6) DEFAULT NULL,
  last_seen_at timestamp(6) NOT NULL,
  resolved_by_reconciliation boolean NOT NULL,
  rule_group varchar(200) NOT NULL,
  rule_snapshot jsonb NOT NULL,
  source varchar(16) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE monitor_alert_notification_event (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  event_type varchar(16) NOT NULL,
  deduplication_key varchar(255) NOT NULL,
  status varchar(16) NOT NULL,
  attempt_count integer NOT NULL,
  error_message text NOT NULL,
  sent_at timestamp(6) DEFAULT NULL,
  alert_id bigint NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT deduplication_key UNIQUE (deduplication_key),
  CONSTRAINT monitor_alert_notification_event_alert_fk FOREIGN KEY (alert_id) REFERENCES monitor_alert_history (id)
);

CREATE TABLE monitor_alert_notification_delivery (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  address varchar(500) NOT NULL,
  status varchar(16) NOT NULL,
  attempt_count integer NOT NULL,
  error_message text NOT NULL,
  sent_at timestamp(6) DEFAULT NULL,
  event_id bigint NOT NULL,
  media_id bigint DEFAULT NULL,
  user_id integer DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT monitor_alert_delivery_uniq UNIQUE (event_id, media_id, user_id, address),
  CONSTRAINT monitor_alert_notification_delivery_event_fk FOREIGN KEY (event_id) REFERENCES monitor_alert_notification_event (id),
  CONSTRAINT monitor_alert_notification_delivery_media_fk FOREIGN KEY (media_id) REFERENCES monitor_alert_media (id),
  CONSTRAINT monitor_alert_notification_delivery_user_fk FOREIGN KEY (user_id) REFERENCES sys_user (id)
);

CREATE TABLE monitor_log_collection_target (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  agent_installed boolean NOT NULL,
  agent_version varchar(64) NOT NULL,
  runtime_status varchar(16) NOT NULL,
  config_fingerprint varchar(64) NOT NULL,
  last_applied_time timestamp(6) DEFAULT NULL,
  last_error text NOT NULL,
  host_id bigint NOT NULL,
  install_message text NOT NULL,
  install_status varchar(16) NOT NULL,
  last_dispatch_manual boolean NOT NULL,
  managed_enabled boolean NOT NULL,
  retry_count integer NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT monitor_log_collection_target_host_id UNIQUE (host_id),
  CONSTRAINT monitor_log_collection_target_host_id_34152fe2_fk_assets_host_i FOREIGN KEY (host_id) REFERENCES assets_host (id),
  CONSTRAINT monitor_log_collection_target_chk_1 CHECK ((retry_count >= 0))
);

CREATE TABLE monitor_notification_policy (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  parent_id bigint DEFAULT NULL,
  name varchar(128) NOT NULL,
  position integer NOT NULL DEFAULT 0,
  matchers jsonb NOT NULL,
  media_ids jsonb DEFAULT NULL,
  notify_on_firing boolean NOT NULL DEFAULT true,
  notify_on_resolved boolean NOT NULL DEFAULT true,
  user_group_ids jsonb DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_notification_policy_parent FOREIGN KEY (parent_id) REFERENCES monitor_notification_policy (id) ON DELETE CASCADE
);

CREATE INDEX idx_notification_policy_parent ON monitor_notification_policy (parent_id);

CREATE TABLE monitor_user_alert_media_binding (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  recipients jsonb NOT NULL,
  enabled boolean NOT NULL,
  media_id bigint NOT NULL,
  user_id integer NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT monitor_user_alert_media_binding_user_id_media_id_63ee2b52_uniq UNIQUE (user_id, media_id),
  CONSTRAINT monitor_user_alert_media_binding_monitor_user_alert_m_media_id_ FOREIGN KEY (media_id) REFERENCES monitor_alert_media (id),
  CONSTRAINT monitor_user_alert_media_binding_user_id_e65368f8_fk_sys_user_i FOREIGN KEY (user_id) REFERENCES sys_user (id)
);

CREATE INDEX monitor_user_alert_m_media_id_41516ddb_fk_monitor_a ON monitor_user_alert_media_binding (media_id);
-- 外键列的索引：MySQL 建外键时若没有可用索引会自动创建一个（`SHOW CREATE TABLE` 里能看到），
-- PG **不会**自动创建 —— 于是同一个查询在两侧的计划不同（实测：告警主机服务树归属的那条
-- JOIN 在 90k 行的 assets_application_service_deployment 上退化成 Seq Scan，21.5ms；
-- 补上 deployment_id 的索引后 0.18ms）。这里按 MySQL 的既有索引逐列补齐（P1-9）。
CREATE INDEX monitor_alert_notification_delivery_media_id_idx ON monitor_alert_notification_delivery (media_id);
CREATE INDEX monitor_alert_notification_delivery_user_id_idx ON monitor_alert_notification_delivery (user_id);
CREATE INDEX monitor_alert_notification_event_alert_id_idx ON monitor_alert_notification_event (alert_id);
CREATE INDEX monitor_log_processing_rule_cluster_id_idx ON monitor_log_processing_rule (cluster_id);
CREATE INDEX monitor_software_package_install_playbook_template_id_idx ON monitor_software_package (install_playbook_template_id);
CREATE INDEX monitor_software_package_uninstall_playbook_template_id_idx ON monitor_software_package (uninstall_playbook_template_id);
CREATE INDEX monitor_target_install_history_target_id_idx ON monitor_target_install_history (target_id);

-- 告警失联对账（每 5 分钟一次）用的 PG 专属 partial index：只索引未恢复的 prometheus 告警，
-- 于是索引大小只跟「当前未恢复告警」成正比，而不是跟历史告警总量成正比。
-- 实测（200k 行告警、5% firing）：Seq Scan 35.9ms → Index Scan 12.1ms，索引 88kB；
-- 普通 last_seen_at 索引不会被选中（95% 的行都满足谓词）。
CREATE INDEX monitor_alert_history_firing_recent_idx ON monitor_alert_history (last_seen_at)
  WHERE state = 'firing' AND source = 'prometheus';
