CREATE TABLE automation_inventory (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(128) NOT NULL,
  selected_host_ids jsonb NOT NULL,
  enabled boolean NOT NULL,
  last_sync_host_count integer NOT NULL,
  last_sync_message text NOT NULL,
  last_sync_status varchar(16) NOT NULL,
  last_sync_time timestamp(6) DEFAULT NULL,
  update_cache_timeout integer NOT NULL,
  update_on_launch boolean NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT automation_inventory_name UNIQUE (name)
);

CREATE TABLE automation_task (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(128) NOT NULL,
  env_vars jsonb NOT NULL,
  enabled boolean NOT NULL,
  inventory_id bigint DEFAULT NULL,
  default_limit varchar(255) NOT NULL,
  execution_timeout_seconds integer NOT NULL,
  playbook_template_id bigint DEFAULT NULL,
  run_as_user varchar(100) NOT NULL,
  run_as_group varchar(100) NOT NULL,
  work_directory varchar(255) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT automation_task_name UNIQUE (name),
  CONSTRAINT automation_task_inventory_fk FOREIGN KEY (inventory_id) REFERENCES automation_inventory (id),
  CONSTRAINT automation_task_playbook_template_fk FOREIGN KEY (playbook_template_id) REFERENCES automation_playbook_template (id)
);

CREATE TABLE automation_execution_job (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  job_id varchar(36) NOT NULL,
  status varchar(16) NOT NULL,
  trigger_type varchar(16) NOT NULL,
  source varchar(32) NOT NULL DEFAULT 'manual',
  inventory_snapshot jsonb NOT NULL,
  extra_vars jsonb NOT NULL,
  result_summary jsonb NOT NULL,
  requested_user_id integer DEFAULT NULL,
  requested_username varchar(100) NOT NULL,
  start_time timestamp(6) DEFAULT NULL,
  end_time timestamp(6) DEFAULT NULL,
  duration_seconds double precision DEFAULT NULL,
  task_id bigint DEFAULT NULL,
  template_content_snapshot text NOT NULL,
  task_name_snapshot varchar(128) NOT NULL,
  template_name_snapshot varchar(128) NOT NULL,
  "limit" varchar(255) NOT NULL,
  run_as_user_snapshot varchar(100) NOT NULL,
  run_as_group_snapshot varchar(100) NOT NULL,
  work_directory_snapshot varchar(255) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT automation_execution_job_job_id UNIQUE (job_id),
  CONSTRAINT automation_execution_job_task_fk FOREIGN KEY (task_id) REFERENCES automation_task (id)
);

CREATE TABLE automation_controller_ssh_key (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  public_key varchar(255) NOT NULL,
  private_key text NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT public_key UNIQUE (public_key)
);

CREATE TABLE automation_execution_host_log (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  remark text,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  host_id_snapshot integer DEFAULT NULL,
  host_name_snapshot varchar(128) NOT NULL,
  host_ip_snapshot varchar(64) NOT NULL,
  agent_job_id varchar(64) NOT NULL,
  status varchar(16) NOT NULL,
  exit_code integer DEFAULT NULL,
  stdout text NOT NULL,
  stderr text NOT NULL,
  error_message text NOT NULL,
  result_data jsonb NOT NULL,
  host_id bigint DEFAULT NULL,
  job_id bigint NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT automation_execution_host_log_host_id_b2ec126e_fk_assets_host_i FOREIGN KEY (host_id) REFERENCES assets_host (id),
  CONSTRAINT automation_execution_host_log_automation_execution_job_id_d6edd FOREIGN KEY (job_id) REFERENCES automation_execution_job (id)
);

CREATE INDEX automation_execution_host_log_host_id_b2ec126e_fk_assets_host_id ON automation_execution_host_log (host_id);

CREATE INDEX automation_execution_job_id_d6edd8d4_fk_automatio ON automation_execution_host_log (job_id);
-- 外键列的索引：MySQL 建外键时若没有可用索引会自动创建一个（`SHOW CREATE TABLE` 里能看到），
-- PG **不会**自动创建 —— 于是同一个查询在两侧的计划不同（实测：告警主机服务树归属的那条
-- JOIN 在 90k 行的 assets_application_service_deployment 上退化成 Seq Scan，21.5ms；
-- 补上 deployment_id 的索引后 0.18ms）。这里按 MySQL 的既有索引逐列补齐（P1-9）。
CREATE INDEX automation_execution_job_task_id_idx ON automation_execution_job (task_id);
CREATE INDEX automation_task_inventory_id_idx ON automation_task (inventory_id);
CREATE INDEX automation_task_playbook_template_id_idx ON automation_task (playbook_template_id);

CREATE TABLE automation_execution_job_log (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  remark text,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  job_id bigint NOT NULL,
  content text NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (job_id) REFERENCES automation_execution_job (id)
);

CREATE INDEX automation_execution_job_log_job_id_7f1c2a94 ON automation_execution_job_log (job_id);

