CREATE TABLE inspection_group (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(128) NOT NULL,
  description text NOT NULL,
  enabled boolean NOT NULL,
  category varchar(16) NOT NULL DEFAULT 'general',
  application_id bigint DEFAULT NULL,
  params jsonb NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT inspection_group_name UNIQUE (name)
);

CREATE TABLE inspection_check (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(128) NOT NULL,
  config jsonb NOT NULL,
  enabled boolean NOT NULL,
  "order" integer NOT NULL,
  group_id bigint NOT NULL,
  severity varchar(16) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT unique_inspection_group_check_name UNIQUE (group_id, name),
  CONSTRAINT inspection_check_group_fk FOREIGN KEY (group_id) REFERENCES inspection_group (id)
);

CREATE TABLE inspection_task (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(128) NOT NULL,
  concurrency integer NOT NULL,
  timeout_seconds integer NOT NULL,
  enabled boolean NOT NULL,
  group_id bigint NOT NULL,
  cron_expression varchar(120) NOT NULL,
  last_run_time timestamp(6) DEFAULT NULL,
  next_run_time timestamp(6) DEFAULT NULL,
  inspection_name varchar(128) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT inspection_task_group_fk FOREIGN KEY (group_id) REFERENCES inspection_group (id)
);

CREATE TABLE inspection_task_group (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  task_id bigint NOT NULL,
  group_id bigint NOT NULL,
  mount_type varchar(16) NOT NULL DEFAULT 'legacy_static',
  project_id bigint DEFAULT NULL,
  environment_id bigint DEFAULT NULL,
  business_system_id bigint DEFAULT NULL,
  instance_mode varchar(8) DEFAULT NULL,
  service_id bigint DEFAULT NULL,
  param_values jsonb NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT unique_inspection_task_group UNIQUE (task_id, group_id)
);

CREATE TABLE inspection_execution (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  status varchar(16) NOT NULL,
  task_snapshot jsonb NOT NULL,
  group_snapshot jsonb NOT NULL,
  service_snapshot jsonb NOT NULL,
  target_snapshot jsonb NOT NULL,
  summary jsonb NOT NULL,
  requested_user_id integer DEFAULT NULL,
  requested_username varchar(100) NOT NULL,
  start_time timestamp(6) DEFAULT NULL,
  end_time timestamp(6) DEFAULT NULL,
  task_id bigint DEFAULT NULL,
  trigger_type varchar(16) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT inspection_execution_task_fk FOREIGN KEY (task_id) REFERENCES inspection_task (id)
);

CREATE TABLE inspection_result (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  check_key varchar(255) NOT NULL,
  check_type varchar(64) NOT NULL,
  name varchar(255) NOT NULL,
  status varchar(16) NOT NULL,
  expected_value jsonb DEFAULT NULL,
  actual_value jsonb DEFAULT NULL,
  message text NOT NULL,
  target_id bigint NOT NULL,
  severity varchar(16) NOT NULL,
  group_id bigint DEFAULT NULL,
  group_name varchar(128) NOT NULL DEFAULT '',
  PRIMARY KEY (id),
  CONSTRAINT inspection_result_target_fk FOREIGN KEY (target_id) REFERENCES inspection_target_execution (id)
);
-- 外键列的索引：MySQL 建外键时若没有可用索引会自动创建一个（`SHOW CREATE TABLE` 里能看到），
-- PG **不会**自动创建 —— 于是同一个查询在两侧的计划不同（实测：告警主机服务树归属的那条
-- JOIN 在 90k 行的 assets_application_service_deployment 上退化成 Seq Scan，21.5ms；
-- 补上 deployment_id 的索引后 0.18ms）。这里按 MySQL 的既有索引逐列补齐（P1-9）。
CREATE INDEX inspection_execution_task_id_idx ON inspection_execution (task_id);
CREATE INDEX inspection_result_target_id_idx ON inspection_result (target_id);
CREATE INDEX inspection_task_group_id_idx ON inspection_task (group_id);
