CREATE TABLE inspection_group (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(128) NOT NULL,
  description text NOT NULL,
  enabled boolean NOT NULL,
  category varchar(16) NOT NULL DEFAULT 'general',
  application_id bigint DEFAULT NULL,
  params jsonb NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT inspection_group_name UNIQUE (name)
);

CREATE TABLE inspection_check (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(128) NOT NULL,
  config jsonb NOT NULL,
  enabled boolean NOT NULL,
  "order" integer NOT NULL,
  group_id bigint NOT NULL,
  severity varchar(16) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT unique_inspection_group_check_name UNIQUE (group_id, name),
  CONSTRAINT inspection_check_group_fk FOREIGN KEY (group_id) REFERENCES inspection_group (id)
);

CREATE TABLE inspection_task (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(128) NOT NULL,
  concurrency integer NOT NULL,
  timeout_seconds integer NOT NULL,
  enabled boolean NOT NULL,
  group_id bigint NOT NULL,
  cron_expression varchar(120) NOT NULL,
  last_run_time timestamp(6) DEFAULT NULL,
  next_run_time timestamp(6) DEFAULT NULL,
  inspection_name varchar(128) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT inspection_task_group_fk FOREIGN KEY (group_id) REFERENCES inspection_group (id)
);

CREATE TABLE inspection_task_group (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  task_id bigint NOT NULL,
  group_id bigint NOT NULL,
  mount_type varchar(16) NOT NULL DEFAULT 'legacy_static',
  project_id bigint DEFAULT NULL,
  environment_id bigint DEFAULT NULL,
  business_system_id bigint DEFAULT NULL,
  instance_mode varchar(8) DEFAULT NULL,
  service_id bigint DEFAULT NULL,
  param_values jsonb NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT unique_inspection_task_group UNIQUE (task_id, group_id)
);

CREATE TABLE inspection_execution (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  status varchar(16) NOT NULL,
  task_snapshot jsonb NOT NULL,
  group_snapshot jsonb NOT NULL,
  service_snapshot jsonb NOT NULL,
  target_snapshot jsonb NOT NULL,
  summary jsonb NOT NULL,
  requested_user_id integer DEFAULT NULL,
  requested_username varchar(100) NOT NULL,
  start_time timestamp(6) DEFAULT NULL,
  end_time timestamp(6) DEFAULT NULL,
  task_id bigint DEFAULT NULL,
  trigger_type varchar(16) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT inspection_execution_task_fk FOREIGN KEY (task_id) REFERENCES inspection_task (id)
);

CREATE TABLE inspection_result (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  check_key varchar(255) NOT NULL,
  check_type varchar(64) NOT NULL,
  name varchar(255) NOT NULL,
  status varchar(16) NOT NULL,
  expected_value jsonb DEFAULT NULL,
  actual_value jsonb DEFAULT NULL,
  message text NOT NULL,
  target_id bigint NOT NULL,
  severity varchar(16) NOT NULL,
  group_id bigint DEFAULT NULL,
  group_name varchar(128) NOT NULL DEFAULT '',
  PRIMARY KEY (id),
  CONSTRAINT inspection_result_target_fk FOREIGN KEY (target_id) REFERENCES inspection_target_execution (id)
);
