CREATE TABLE baseline (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(128) NOT NULL,
  version varchar(32) NOT NULL DEFAULT 'v1',
  description text NOT NULL,
  enabled boolean NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT baseline_name UNIQUE (name)
);

CREATE TABLE baseline_category (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(64) NOT NULL,
  sort integer NOT NULL DEFAULT 0,
  baseline_id bigint NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT baseline_category_baseline_fk FOREIGN KEY (baseline_id) REFERENCES baseline (id) ON DELETE CASCADE
);

CREATE INDEX baseline_category_baseline_fk ON baseline_category (baseline_id);

CREATE TABLE baseline_item (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  baseline_id bigint NOT NULL,
  category_id bigint NOT NULL,
  sort integer NOT NULL,
  name varchar(255) NOT NULL,
  description text NOT NULL,
  config jsonb NOT NULL,
  severity varchar(16) NOT NULL DEFAULT 'high',
  PRIMARY KEY (id),
  CONSTRAINT baseline_item_baseline_fk FOREIGN KEY (baseline_id) REFERENCES baseline (id),
  CONSTRAINT baseline_item_category_fk FOREIGN KEY (category_id) REFERENCES baseline_category (id)
);

CREATE INDEX baseline_item_baseline_fk ON baseline_item (baseline_id);

CREATE INDEX baseline_item_category_fk ON baseline_item (category_id);

CREATE TABLE security_scan (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  scan_type varchar(16) NOT NULL DEFAULT 'baseline',
  baseline_id bigint NOT NULL,
  mount_type varchar(16) NOT NULL,
  project_id bigint DEFAULT NULL,
  environment_id bigint DEFAULT NULL,
  status varchar(16) NOT NULL DEFAULT 'pending',
  summary jsonb NOT NULL,
  requested_username varchar(100) NOT NULL,
  start_time timestamp(6) DEFAULT NULL,
  end_time timestamp(6) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT security_scan_baseline_fk FOREIGN KEY (baseline_id) REFERENCES baseline (id)
);

CREATE INDEX security_scan_baseline_fk ON security_scan (baseline_id);

CREATE TABLE security_scan_target (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  scan_id bigint NOT NULL,
  host_id bigint NOT NULL,
  host_name varchar(255) NOT NULL,
  host_ip varchar(64) NOT NULL,
  instance_name_snapshot varchar(128) NOT NULL,
  status varchar(16) NOT NULL DEFAULT 'pending',
  passed_items integer NOT NULL DEFAULT 0,
  failed_items integer NOT NULL DEFAULT 0,
  compliance_rate numeric(5,2) NOT NULL DEFAULT 0,
  error_message text NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT security_scan_target_scan_fk FOREIGN KEY (scan_id) REFERENCES security_scan (id)
);

CREATE INDEX security_scan_target_scan_fk ON security_scan_target (scan_id);

CREATE TABLE baseline_scan_result (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  scan_id bigint NOT NULL,
  host_id bigint NOT NULL,
  item_id bigint NOT NULL,
  item_name varchar(255) NOT NULL,
  chapter varchar(64) NOT NULL,
  severity varchar(16) NOT NULL,
  status varchar(16) NOT NULL,
  expected_value jsonb DEFAULT NULL,
  actual_value jsonb DEFAULT NULL,
  message text NOT NULL,
  remediation text,
  PRIMARY KEY (id),
  CONSTRAINT baseline_scan_result_scan_fk FOREIGN KEY (scan_id) REFERENCES security_scan (id)
);

CREATE INDEX baseline_scan_result_scan_fk ON baseline_scan_result (scan_id);
