# Generated by Django 5.1.4 on 2026-06-29 04:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(default=datetime.date(2026, 6, 29), verbose_name='创建时间')),
                ('update_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('key', models.CharField(max_length=128, unique=True, verbose_name='参数键')),
                ('value', models.TextField(verbose_name='参数值')),
                ('value_type', models.CharField(choices=[('string', '字符串'), ('int', '整数'), ('bool', '布尔值'), ('json', 'JSON')], default='string', max_length=16, verbose_name='值类型')),
                ('name', models.CharField(max_length=128, verbose_name='参数名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('is_readonly', models.BooleanField(default=False, verbose_name='只读')),
            ],
            options={
                'verbose_name': '系统参数',
                'db_table': 'sys_config',
                'ordering': ['id'],
            },
        ),
    ]
