# Generated by Django 5.1.4 on 2026-07-05 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_config', '0003_sysconfig_default_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysconfig',
            name='create_time',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='创建时间'),
        ),
    ]
