# Generated by Django 5.1.4 on 2026-07-15 08:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_config', '0004_alter_sysconfig_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysconfig',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
