# Generated by Django 5.1.4 on 2026-07-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_config', '0011_add_automation_websocket_poll_interval_configs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysconfig',
            name='value_type',
            field=models.CharField(choices=[('string', '字符串'), ('int', '整数'), ('bool', '布尔值'), ('json', 'JSON'), ('secret', '密文（哈希存储，不回显明文）')], default='string', max_length=16, verbose_name='值类型'),
        ),
    ]
