# Generated by Django 5.1.4 on 2025-05-24 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SysUserRole',
        ),
    ]
