# Generated by Django 5.1.4 on 2025-05-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_delete_sysuserrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysrole',
            name='remark',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='备注'),
        ),
    ]
