# Generated by Django 5.1.4 on 2025-06-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0003_alter_sysrole_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysrole',
            name='create_time',
            field=models.DateField(blank=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='sysrole',
            name='update_time',
            field=models.DateField(blank=True, null=True, verbose_name='更新时间'),
        ),
    ]
