# Generated by Django 5.1.4 on 2025-05-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_sysuser_status_sysuserrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysuser',
            name='remark',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='备注'),
        ),
    ]
