# Generated by Django 5.1.4 on 2025-05-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_sysuser_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysuser',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码'),
        ),
    ]
