# Generated by Django 5.1.4 on 2025-06-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_sysuser_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysuser',
            name='create_time',
            field=models.DateField(blank=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='update_time',
            field=models.DateField(blank=True, null=True, verbose_name='更新时间'),
        ),
    ]
