# Generated by Django 5.1.4 on 2026-06-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_sysuser_create_time_alter_sysuser_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50, verbose_name='时区'),
        ),
    ]
