# Generated by Django 5.1.4 on 2026-07-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_sysuser_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysuser',
            name='login_date',
            field=models.DateTimeField(null=True, verbose_name='最后登录时间'),
        ),
    ]
