# Generated by Django 5.1.4 on 2026-07-18 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_fix_login_date_datetimefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_id', models.CharField(max_length=128, unique=True, verbose_name='Agent标识')),
                ('token_hash', models.CharField(max_length=255, verbose_name='Token哈希')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agent_tokens', to='user.sysuser', verbose_name='创建人')),
            ],
            options={
                'db_table': 'sys_agent_token',
            },
        ),
    ]
