# Generated by Django 5.1.4 on 2026-07-18 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_apitoken_agent_id_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='bind_mode',
            field=models.CharField(choices=[('agent', 'Agent共享'), ('api', 'Api绑定')], default='api', max_length=32, verbose_name='绑定模式'),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_tokens', to='user.sysuser', verbose_name='创建人'),
        ),
    ]
