-- 安全中心 / 基线扫描（一期）：OS 基线标准 + 条目 + 扫描执行与结果。
-- 扫描任务统一在 security_scan（scan_type 预留 cve 等后续类型）；基线只针对操作系统：
-- 与应用无关，目标按 项目/项目×环境 的主机集合解析。
--
-- PG 侧差异（类型与约束名，均对照 db/schema/postgres）：
--   MySQL 自增主键 → GENERATED BY DEFAULT AS IDENTITY；MySQL 的 datetime 微秒精度 → timestamp(6)；
--   MySQL 长文本类型 → text；json → jsonb；int unsigned → integer；decimal(5,2) → numeric(5,2)；
--   表内 KEY（非唯一）声明 → 独立的 CREATE INDEX（与同名外键约束并存，沿用 PG schema 命名）；
--   UNIQUE KEY name → CONSTRAINT <表名>_name（PG 约束名全库唯一，不能沿用裸 name）。
--   MySQL 的建表后缀（引擎/字符集/排序规则）：本文件未使用。

CREATE TABLE baseline (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(128) NOT NULL,
  version varchar(32) NOT NULL DEFAULT 'v1',
  description text NOT NULL,
  enabled boolean NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT baseline_name UNIQUE (name)
);

CREATE TABLE baseline_item (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  baseline_id bigint NOT NULL,
  chapter varchar(64) NOT NULL DEFAULT '通用',
  sort integer NOT NULL,
  name varchar(255) NOT NULL,
  description text NOT NULL,
  executor varchar(16) NOT NULL,
  config jsonb NOT NULL,
  severity varchar(16) NOT NULL DEFAULT 'high',
  PRIMARY KEY (id),
  CONSTRAINT baseline_item_baseline_fk FOREIGN KEY (baseline_id) REFERENCES baseline (id)
);

CREATE INDEX baseline_item_baseline_fk ON baseline_item (baseline_id);

CREATE TABLE security_scan (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  scan_type varchar(16) NOT NULL DEFAULT 'baseline',
  baseline_id bigint NOT NULL,
  mount_type varchar(16) NOT NULL,
  project_id bigint DEFAULT NULL,
  environment_id bigint DEFAULT NULL,
  status varchar(16) NOT NULL DEFAULT 'pending',
  summary jsonb NOT NULL,
  requested_username varchar(100) NOT NULL,
  start_time timestamp(6) DEFAULT NULL,
  end_time timestamp(6) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT security_scan_baseline_fk FOREIGN KEY (baseline_id) REFERENCES baseline (id)
);

CREATE INDEX security_scan_baseline_fk ON security_scan (baseline_id);

CREATE TABLE security_scan_target (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  scan_id bigint NOT NULL,
  host_id bigint NOT NULL,
  host_name varchar(255) NOT NULL,
  host_ip varchar(64) NOT NULL,
  agent_id varchar(128) NOT NULL,
  status varchar(16) NOT NULL DEFAULT 'pending',
  passed_items integer NOT NULL DEFAULT 0,
  failed_items integer NOT NULL DEFAULT 0,
  compliance_rate numeric(5,2) NOT NULL DEFAULT 0,
  error_message text NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT security_scan_target_scan_fk FOREIGN KEY (scan_id) REFERENCES security_scan (id)
);

CREATE INDEX security_scan_target_scan_fk ON security_scan_target (scan_id);

CREATE TABLE baseline_scan_result (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  scan_id bigint NOT NULL,
  host_id bigint NOT NULL,
  item_id bigint NOT NULL,
  item_name varchar(255) NOT NULL,
  chapter varchar(64) NOT NULL,
  severity varchar(16) NOT NULL,
  status varchar(16) NOT NULL,
  expected_value jsonb DEFAULT NULL,
  actual_value jsonb DEFAULT NULL,
  message text NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT baseline_scan_result_scan_fk FOREIGN KEY (scan_id) REFERENCES security_scan (id)
);

CREATE INDEX baseline_scan_result_scan_fk ON baseline_scan_result (scan_id);
