-- 通知策略树（对齐 Grafana notification policy）：
-- - 根节点 parent_id IS NULL，matchers=[] 恒命中，是唯一不可删除节点；
-- - matchers JSON：[{"type":"label","label":"severity","operator":"=","value":"critical"},
--   {"type":"tree","node_type":"business","id":3}]，节点内条件 AND；
-- - media_ids JSON：NULL=继承父节点出口，[]=显式不通知（静音）；
-- - 路由：从根向下，每层取 position/id 顺序下第一条命中的子策略，最深命中节点决定出口。
--
-- PG 侧差异：json → jsonb（含 NULL 列）；BOOLEAN DEFAULT TRUE → boolean DEFAULT true；
--   MySQL 的 datetime 微秒精度 → timestamp(6)；MySQL 自增主键 → IDENTITY；去掉 MySQL 的建表后缀；
--   表内 KEY 声明 → 独立 CREATE INDEX（名字沿用 db/schema/postgres 的 idx_notification_policy_parent）；
--   INSERT 种子去掉 MySQL 的 DUAL 伪表；sys_menu.update_time 在 PG 是 date，now() 隐式落为当天日期。

CREATE TABLE IF NOT EXISTS monitor_notification_policy (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  parent_id bigint DEFAULT NULL,
  name varchar(128) NOT NULL,
  position integer NOT NULL DEFAULT 0,
  matchers jsonb NOT NULL,
  media_ids jsonb DEFAULT NULL,
  notify_on_firing boolean NOT NULL DEFAULT TRUE,
  notify_on_resolved boolean NOT NULL DEFAULT TRUE,
  PRIMARY KEY (id),
  CONSTRAINT fk_notification_policy_parent FOREIGN KEY (parent_id) REFERENCES monitor_notification_policy (id) ON DELETE CASCADE
);

CREATE INDEX idx_notification_policy_parent ON monitor_notification_policy (parent_id);

INSERT INTO monitor_notification_policy(create_time,update_time,remark,parent_id,name,position,matchers,media_ids,notify_on_firing,notify_on_resolved)
SELECT now(), now(), '默认通知策略（匹配一切告警）', NULL, '默认策略', 0, '[]', '[]', TRUE, TRUE
WHERE NOT EXISTS (SELECT 1 FROM monitor_notification_policy WHERE parent_id IS NULL);

-- 策略树取代旧告警路由（monitor_alert_route / monitor_alert_route_media）；
-- 用户绑定退化为纯收件配置，订阅范围列一并移除。
DROP TABLE IF EXISTS monitor_alert_route_media;
DROP TABLE IF EXISTS monitor_alert_route;

ALTER TABLE monitor_user_alert_media_binding DROP COLUMN scope;

-- 菜单适配：旧「告警路由」菜单/按钮改为「通知策略」页。
UPDATE sys_menu SET name='通知策略', path='/monitor/notification-policies', component='monitor/notification-policies/index', update_time=now()
WHERE path LIKE '%alert-routes%' OR component LIKE '%alert-routes%';
