-- dj-agent 安装包管理：上传的二进制及其 sha256/大小/版本，is_active 独占激活，
-- Agent 安装/更新优先使用激活包，未激活时回退构建产物（internal/assets/agent_update.go）。
--
-- PG 侧差异：BIGINT UNSIGNED → bigint（PG 无 unsigned，类型退化与 db/schema/postgres 一致）；
--   CHAR(64) → varchar(64)；MySQL 的布尔列写法（0/1）→ boolean DEFAULT false；
--   MySQL 的 datetime 微秒精度 → timestamp(6)；MySQL 自增主键 → GENERATED BY DEFAULT AS IDENTITY。

CREATE TABLE agent_package (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  version varchar(64) NOT NULL,
  file varchar(512) NOT NULL,
  sha256 varchar(64) NOT NULL,
  size_bytes bigint NOT NULL,
  is_active boolean NOT NULL DEFAULT false,
  create_time timestamp(6) DEFAULT NULL,
  PRIMARY KEY (id)
);
