-- 基线条目分组升级：chapter 自由文本 → baseline_category 类目实体。
-- 类目成为一等对象（改名/排序/空类目稳定存在），策略（原条目）挂到类目下。
--
-- PG 侧差异：MySQL 自增主键 → IDENTITY；MySQL 长文本类型 → text；int unsigned → integer；
--   KEY/UNIQUE 声明 → 带名字的约束 + 独立 CREATE INDEX（沿用 db/schema/postgres 的命名，
--   索引与同名外键约束在 PG 里是两个命名空间，可以同名）；
--   MySQL 的多表 UPDATE ... JOIN ... SET → PG 的 UPDATE ... FROM（语义等价）；
--   MODIFY COLUMN ... NOT NULL → ALTER COLUMN ... SET NOT NULL。

CREATE TABLE baseline_category (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(64) NOT NULL,
  sort integer NOT NULL DEFAULT 0,
  baseline_id bigint NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT baseline_category_baseline_fk FOREIGN KEY (baseline_id) REFERENCES baseline (id) ON DELETE CASCADE
);

CREATE INDEX baseline_category_baseline_fk ON baseline_category (baseline_id);

-- 存量 chapter 按基线内首次出现顺序建类目（sort 从 0 递增）。
INSERT INTO baseline_category (create_time, update_time, name, baseline_id, sort)
SELECT now(), now(), chapter, baseline_id, rn - 1
FROM (
  SELECT chapter, baseline_id, ROW_NUMBER() OVER (PARTITION BY baseline_id ORDER BY MIN(id)) AS rn
  FROM baseline_item
  GROUP BY baseline_id, chapter
) t;

-- 回填 item.category_id（chapter 与类目名一一对应）。
ALTER TABLE baseline_item ADD COLUMN category_id bigint NULL;

UPDATE baseline_item i
SET category_id = c.id
FROM baseline_category c
WHERE c.baseline_id = i.baseline_id AND c.name = i.chapter;

ALTER TABLE baseline_item
  ALTER COLUMN category_id SET NOT NULL,
  ADD CONSTRAINT baseline_item_category_fk FOREIGN KEY (category_id) REFERENCES baseline_category (id);

CREATE INDEX baseline_item_category_fk ON baseline_item (category_id);

ALTER TABLE baseline_item DROP COLUMN chapter;
