-- 用户组：独立于角色的通知/协作分组实体。角色管权限，用户组管"人群"，
-- 后续告警通知接收组等按用户组寻址，避免为收告警而动权限。
--
-- PG 侧差异：MySQL 自增主键 → IDENTITY；MySQL 的 datetime 微秒精度 → timestamp(6)；MySQL 长文本类型 → text；
--   去掉 MySQL 的建表后缀；UNIQUE KEY/KEY → 带名字的约束 + 独立 CREATE INDEX
--   （名字沿用 db/schema/postgres：sys_user_group_name / sys_user_group_member_group_user /
--   idx_user_group_member_user / fk_user_group_member_group / fk_user_group_member_user）；
--   PG 无会话变量 SET @x := (...)，改为按 name 自连接 / 子查询取父菜单 id；
--   INSERT IGNORE → ON CONFLICT DO NOTHING。

CREATE TABLE IF NOT EXISTS sys_user_group (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(128) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT sys_user_group_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS sys_user_group_member (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  group_id bigint NOT NULL,
  user_id integer NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT sys_user_group_member_group_user UNIQUE (group_id, user_id),
  CONSTRAINT fk_user_group_member_group FOREIGN KEY (group_id) REFERENCES sys_user_group (id) ON DELETE CASCADE,
  CONSTRAINT fk_user_group_member_user FOREIGN KEY (user_id) REFERENCES sys_user (id) ON DELETE CASCADE
);

CREATE INDEX idx_user_group_member_user ON sys_user_group_member (user_id);

-- 菜单：挂在「系统管理」下（不存在则顶层），按钮权限沿用 system:usergroups:* 口径。
INSERT INTO sys_menu (name, icon, parent_id, order_num, path, component, menu_type, perms, location, is_expanded, create_time, update_time)
SELECT '用户组', 'fa-users-rectangle',
       COALESCE((SELECT id FROM sys_menu WHERE name = '系统管理' AND menu_type = 'M' LIMIT 1), 0),
       5, '/sys/user-groups', 'sys/usergroups/index', 'C', 'system:usergroups:view', 1, TRUE, now(), now()
WHERE NOT EXISTS (SELECT 1 FROM sys_menu WHERE name = '用户组');

INSERT INTO sys_menu (name, icon, parent_id, order_num, path, component, menu_type, perms, location, is_expanded, create_time, update_time)
SELECT '查询用户组', NULL, p.id, 1, '', NULL, 'F', 'system:usergroups:view', 1, FALSE, now(), now()
FROM sys_menu p
WHERE p.name = '用户组' AND p.menu_type = 'C'
  AND NOT EXISTS (SELECT 1 FROM sys_menu WHERE parent_id = p.id AND perms = 'system:usergroups:view');

INSERT INTO sys_menu (name, icon, parent_id, order_num, path, component, menu_type, perms, location, is_expanded, create_time, update_time)
SELECT '新增用户组', NULL, p.id, 2, '', NULL, 'F', 'system:usergroups:create', 1, FALSE, now(), now()
FROM sys_menu p
WHERE p.name = '用户组' AND p.menu_type = 'C'
  AND NOT EXISTS (SELECT 1 FROM sys_menu WHERE parent_id = p.id AND perms = 'system:usergroups:create');

INSERT INTO sys_menu (name, icon, parent_id, order_num, path, component, menu_type, perms, location, is_expanded, create_time, update_time)
SELECT '更新用户组', NULL, p.id, 3, '', NULL, 'F', 'system:usergroups:update', 1, FALSE, now(), now()
FROM sys_menu p
WHERE p.name = '用户组' AND p.menu_type = 'C'
  AND NOT EXISTS (SELECT 1 FROM sys_menu WHERE parent_id = p.id AND perms = 'system:usergroups:update');

INSERT INTO sys_menu (name, icon, parent_id, order_num, path, component, menu_type, perms, location, is_expanded, create_time, update_time)
SELECT '删除用户组', NULL, p.id, 4, '', NULL, 'F', 'system:usergroups:delete', 1, FALSE, now(), now()
FROM sys_menu p
WHERE p.name = '用户组' AND p.menu_type = 'C'
  AND NOT EXISTS (SELECT 1 FROM sys_menu WHERE parent_id = p.id AND perms = 'system:usergroups:delete');

-- 角色授权：已拥有「用户管理」菜单的角色，同步获得用户组菜单与按钮（维持原可见人群）。
INSERT INTO sys_role_menu (role_id, menu_id)
SELECT DISTINCT rm.role_id, ug.id
FROM sys_menu user_mgmt
JOIN sys_role_menu rm ON rm.menu_id = user_mgmt.id
JOIN sys_menu ug ON ug.name = '用户组' AND ug.menu_type = 'C'
WHERE user_mgmt.name = '用户管理' AND user_mgmt.menu_type = 'C'
ON CONFLICT DO NOTHING;

INSERT INTO sys_role_menu (role_id, menu_id)
SELECT rm.role_id, btn.id
FROM sys_menu ug
JOIN sys_role_menu rm ON rm.menu_id = ug.id
JOIN sys_menu btn ON btn.parent_id = ug.id AND btn.menu_type = 'F'
WHERE ug.name = '用户组' AND ug.menu_type = 'C'
ON CONFLICT DO NOTHING;
