-- 日志采集批量动作的进度载体（计划 LOG_COLLECTION_LIFECYCLE §8 Phase 2）。语义与 MySQL 侧一致，
-- 说明见 db/migrations/mysql/000033_log_batch_job.up.sql。
--
-- PG 侧差异：自增主键写 GENERATED BY DEFAULT AS IDENTITY；datetime(6) 写 timestamp(6)；
-- longtext 写 text；int 写 integer；索引单独 CREATE INDEX（PG 不支持表内 KEY 子句）。
CREATE TABLE monitor_log_batch_job (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  action varchar(16) NOT NULL,
  status varchar(16) NOT NULL,
  total_count integer NOT NULL,
  success_count integer NOT NULL,
  failed_count integer NOT NULL,
  concurrency integer NOT NULL,
  message text NOT NULL,
  requested_user_id bigint DEFAULT NULL,
  requested_username varchar(150) NOT NULL,
  started_at timestamp(6) DEFAULT NULL,
  finished_at timestamp(6) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE monitor_log_batch_job_item (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  batch_job_id bigint NOT NULL,
  target_id bigint NOT NULL,
  host_id bigint NOT NULL,
  host_name varchar(128) NOT NULL,
  host_ip varchar(64) NOT NULL,
  status varchar(16) NOT NULL,
  message text NOT NULL,
  started_at timestamp(6) DEFAULT NULL,
  finished_at timestamp(6) DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT monitor_log_batch_job_item_batch_job_id_fk FOREIGN KEY (batch_job_id) REFERENCES monitor_log_batch_job (id)
);

CREATE INDEX monitor_log_batch_job_item_batch_job_id_idx ON monitor_log_batch_job_item (batch_job_id);
