-- 回滚 000015：恢复旧路由表与绑定 scope 列（数据不可恢复，仅恢复结构）。
--
-- PG 侧差异：json → jsonb；BOOLEAN → boolean；MySQL 的 datetime 微秒精度 → timestamp(6)；
--   MySQL 自增主键 → IDENTITY；去掉 MySQL 的建表后缀；
--   monitor_alert_route 的 UNIQUE KEY name 在 PG 里必须换成全库唯一的名字（PG 约束名全库唯一，
--   裸 name 会与其他表冲突），按 db/schema/postgres 的 <表名>_name 约定取 monitor_alert_route_name。

ALTER TABLE monitor_user_alert_media_binding ADD COLUMN scope jsonb NULL;

DROP TABLE IF EXISTS monitor_notification_policy;

CREATE TABLE monitor_alert_route (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  create_time timestamp(6) NOT NULL,
  update_time timestamp(6) NOT NULL,
  remark text,
  name varchar(128) NOT NULL,
  enabled boolean NOT NULL,
  matchers jsonb NOT NULL,
  notify_on_firing boolean NOT NULL,
  notify_on_resolved boolean NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT monitor_alert_route_name UNIQUE (name)
);

CREATE TABLE monitor_alert_route_media (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  alertroute_id bigint NOT NULL,
  alertmedia_id bigint NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT alertroute_alertmedia UNIQUE (alertroute_id, alertmedia_id)
);
