# Generated by Django 5.1.4 on 2026-07-19 14:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0031_host_agent_online_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('exporter_type', models.CharField(choices=[('node_exporter', 'Node Exporter')], default='node_exporter', max_length=32)),
                ('exporter_port', models.PositiveIntegerField(default=9100)),
                ('managed_enabled', models.BooleanField(default=True)),
                ('install_status', models.CharField(choices=[('unknown', 'Unknown'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='unknown', max_length=16)),
                ('install_message', models.TextField(blank=True, default='')),
                ('last_scrape_status', models.CharField(choices=[('unknown', 'Unknown'), ('up', 'Up'), ('down', 'Down')], default='unknown', max_length=16)),
                ('last_scrape_at', models.DateTimeField(blank=True, null=True)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_targets', to='assets.host')),
            ],
            options={
                'db_table': 'monitor_target',
                'ordering': ['-id'],
                'unique_together': {('host', 'exporter_type')},
            },
        ),
    ]
