# Generated by Django 5.1.4 on 2026-07-20 06:07

import django.utils.timezone
import monitor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwarePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('name', models.CharField(default='node_exporter', max_length=64)),
                ('version', models.CharField(max_length=32)),
                ('os', models.CharField(choices=[('linux', 'Linux')], default='linux', max_length=16)),
                ('arch', models.CharField(choices=[('amd64', 'x86_64/amd64'), ('arm64', 'aarch64/arm64')], default='amd64', max_length=16)),
                ('file', models.FileField(max_length=255, storage=monitor.models.OverwriteStorage(), upload_to=monitor.models.software_package_upload_to)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'monitor_software_package',
                'ordering': ['-id'],
                'unique_together': {('name', 'version', 'os', 'arch')},
            },
        ),
    ]
