# Generated by Django 5.1.4 on 2026-07-20 06:22

import monitor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_softwarepackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwarepackage',
            name='file',
            field=models.FileField(blank=True, default='', max_length=255, storage=monitor.models.OverwriteStorage(), upload_to=monitor.models.software_package_upload_to),
        ),
    ]
