# Generated by Django 5.1.4 on 2026-07-20 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_seed_node_exporter_amd64_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortarget',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
