# Generated by Django 5.1.4 on 2026-07-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_monitortarget_retry_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarepackage',
            name='env_vars',
            field=models.TextField(blank=True, default='', help_text='环境变量，格式为每行一条 KEY=VALUE'),
        ),
        migrations.AddField(
            model_name='softwarepackage',
            name='start_args',
            field=models.TextField(blank=True, default='', help_text='启动命令行参数，如 --web.listen-address=:9100'),
        ),
        migrations.AddField(
            model_name='softwarepackage',
            name='start_script',
            field=models.TextField(blank=True, default='', help_text='自定义启动脚本内容，留空则使用 agent 内置默认脚本'),
        ),
        migrations.AddField(
            model_name='softwarepackage',
            name='status_script',
            field=models.TextField(blank=True, default='', help_text='自定义监控/状态检查脚本内容，留空则使用 agent 内置默认脚本'),
        ),
        migrations.AddField(
            model_name='softwarepackage',
            name='stop_script',
            field=models.TextField(blank=True, default='', help_text='自定义停止脚本内容，留空则使用 agent 内置默认脚本'),
        ),
    ]
