# Generated by Django 5.1.4 on 2026-07-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_softwarepackage_env_vars_softwarepackage_start_args_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortarget',
            name='env_vars',
            field=models.TextField(blank=True, default='', help_text='环境变量，格式为每行一条 KEY=VALUE'),
        ),
        migrations.AddField(
            model_name='monitortarget',
            name='install_script',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='monitortarget',
            name='start_args',
            field=models.TextField(blank=True, default='', help_text='启动命令行参数，如 --web.listen-address=:9100'),
        ),
        migrations.AddField(
            model_name='monitortarget',
            name='start_script',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='monitortarget',
            name='status_script',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='monitortarget',
            name='stop_script',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='monitortarget',
            name='uninstall_script',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='softwarepackage',
            name='install_script',
            field=models.TextField(blank=True, default='', help_text='安装脚本内容'),
        ),
        migrations.AddField(
            model_name='softwarepackage',
            name='uninstall_script',
            field=models.TextField(blank=True, default='', help_text='卸载脚本内容'),
        ),
        migrations.AlterField(
            model_name='monitortarget',
            name='exporter_type',
            field=models.CharField(default='node_exporter', max_length=64),
        ),
        migrations.AlterField(
            model_name='softwarepackage',
            name='start_script',
            field=models.TextField(blank=True, default='', help_text='启动脚本内容'),
        ),
        migrations.AlterField(
            model_name='softwarepackage',
            name='status_script',
            field=models.TextField(blank=True, default='', help_text='监控/状态检查脚本内容'),
        ),
        migrations.AlterField(
            model_name='softwarepackage',
            name='stop_script',
            field=models.TextField(blank=True, default='', help_text='停止脚本内容'),
        ),
    ]
