# Generated by Django 5.1.4 on 2026-07-20 08:33
# 手动调整生成顺序：先新增 manage_script 字段，再用数据迁移把原来 5 个脚本字段
# （+ start_args）合并进去，最后才删除旧字段，避免直接 makemigrations 顺序导致数据丢失。

from django.db import migrations, models


def _indent(text, prefix='\t\t'):
	"""给脚本正文按 case 分支缩进两层 tab，纯粹是可读性处理，不影响执行结果。"""
	lines = str(text or '').splitlines()
	return '\n'.join(f'{prefix}{line}' if line.strip() else line for line in lines)


def _shell_quote(value):
	return "'" + str(value or '').replace("'", "'\\''") + "'"


def _build_manage_script(install_script, uninstall_script, start_script, stop_script, status_script, start_args):
	"""把旧的 5 个独立脚本字段（+ start_args）拼装为新的统一 manage_script：
	按 $1 位置参数（install/uninstall/start/stop/status）分发到对应 case 分支。
	start_args 不再是独立字段，直接作为本地变量 START_ARGS 注入 start 分支内部，
	保持旧脚本里 ${START_ARGS} 引用不需要改写即可继续工作。"""
	branches = []
	if str(install_script or '').strip():
		branches.append(f'\tinstall)\n{_indent(install_script)}\n\t\t;;')
	if str(uninstall_script or '').strip():
		branches.append(f'\tuninstall)\n{_indent(uninstall_script)}\n\t\t;;')
	if str(start_script or '').strip():
		start_args_line = f"\t\tSTART_ARGS={_shell_quote(start_args)}\n" if str(start_args or '').strip() else ''
		branches.append(f'\tstart)\n{start_args_line}{_indent(start_script)}\n\t\t;;')
	if str(stop_script or '').strip():
		branches.append(f'\tstop)\n{_indent(stop_script)}\n\t\t;;')
	if str(status_script or '').strip():
		branches.append(f'\tstatus)\n{_indent(status_script)}\n\t\t;;')

	if not branches:
		return ''

	branches.append('\t*)\n\t\techo "usage: $0 {install|uninstall|start|stop|status}" >&2\n\t\texit 1\n\t\t;;')
	body = '\n'.join(branches)
	return f'ACTION="${{1:-}}"\ncase "$ACTION" in\n{body}\nesac\n'


def backfill_manage_script(apps, schema_editor):
	"""仅当 manage_script 当前为空时才回填，避免覆盖用户已经手动填写的新内容。"""
	for model_name in ('SoftwarePackage', 'MonitorTarget'):
		Model = apps.get_model('monitor', model_name)
		for obj in Model.objects.all():
			if str(getattr(obj, 'manage_script', '') or '').strip():
				continue
			script = _build_manage_script(
				obj.install_script, obj.uninstall_script, obj.start_script,
				obj.stop_script, obj.status_script, obj.start_args,
			)
			if script:
				obj.manage_script = script
				obj.save(update_fields=['manage_script'])


def noop_reverse(apps, schema_editor):
	pass


class Migration(migrations.Migration):

	dependencies = [
		('monitor', '0008_seed_node_exporter_default_scripts'),
	]

	operations = [
		migrations.AddField(
			model_name='monitortarget',
			name='manage_script',
			field=models.TextField(blank=True, default='', help_text='统一管理脚本，需按 $1 参数分发 install/uninstall/start/stop/status 五种动作'),
		),
		migrations.AddField(
			model_name='softwarepackage',
			name='manage_script',
			field=models.TextField(blank=True, default='', help_text='统一管理脚本，需按 $1 参数分发 install/uninstall/start/stop/status 五种动作'),
		),
		migrations.RunPython(backfill_manage_script, noop_reverse),
		migrations.RemoveField(
			model_name='monitortarget',
			name='install_script',
		),
		migrations.RemoveField(
			model_name='monitortarget',
			name='start_args',
		),
		migrations.RemoveField(
			model_name='monitortarget',
			name='start_script',
		),
		migrations.RemoveField(
			model_name='monitortarget',
			name='status_script',
		),
		migrations.RemoveField(
			model_name='monitortarget',
			name='stop_script',
		),
		migrations.RemoveField(
			model_name='monitortarget',
			name='uninstall_script',
		),
		migrations.RemoveField(
			model_name='softwarepackage',
			name='install_script',
		),
		migrations.RemoveField(
			model_name='softwarepackage',
			name='start_args',
		),
		migrations.RemoveField(
			model_name='softwarepackage',
			name='start_script',
		),
		migrations.RemoveField(
			model_name='softwarepackage',
			name='status_script',
		),
		migrations.RemoveField(
			model_name='softwarepackage',
			name='stop_script',
		),
		migrations.RemoveField(
			model_name='softwarepackage',
			name='uninstall_script',
		),
	]
