# Generated by Django 5.1.4 on 2026-07-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_replace_manage_script_with_automation_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarepackage',
            name='service_run_as_group',
            field=models.CharField(blank=True, default='', help_text='服务运行时的系统组，留空则使用 service_run_as_user 的主组', max_length=100),
        ),
        migrations.AddField(
            model_name='softwarepackage',
            name='service_run_as_user',
            field=models.CharField(blank=True, default='', help_text='安装后 systemd 服务运行时使用的系统用户，留空则使用软件包 name 作为用户名（安装 playbook 据此创建该系统用户）', max_length=100),
        ),
    ]
