# Generated by Django 5.1.4 on 2026-07-21 05:06

from django.db import migrations, models


def backfill_blank_service_run_as(apps, schema_editor):
    """0015 迁移时旧记录的 service_run_as_user/group 落的是空字符串默认值，
    这里补齐为新的默认账号 dj-agent，避免历史记录违反新加的必填约束/产生空用户下发。"""
    SoftwarePackage = apps.get_model('monitor', 'SoftwarePackage')
    SoftwarePackage.objects.filter(service_run_as_user='').update(service_run_as_user='dj-agent')
    SoftwarePackage.objects.filter(service_run_as_group='').update(service_run_as_group='dj-agent')


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0015_add_service_run_as_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwarepackage',
            name='service_run_as_group',
            field=models.CharField(blank=True, default='dj-agent', help_text='服务运行时的系统组，默认 dj-agent，留空则使用 service_run_as_user 的主组', max_length=100),
        ),
        migrations.AlterField(
            model_name='softwarepackage',
            name='service_run_as_user',
            field=models.CharField(default='dj-agent', help_text='安装后 systemd 服务运行时使用的系统用户（必填，安装 playbook 据此创建该系统用户），默认 dj-agent', max_length=100),
        ),
        migrations.RunPython(backfill_blank_service_run_as, migrations.RunPython.noop),
    ]
