# Generated by Django 5.1.4 on 2026-07-21 05:52
# 架构调整：安装/卸载不再经由 AutomationTask 中转，install_task/uninstall_task 直接改为
# install_playbook_template/uninstall_playbook_template（FK 到 automation.PlaybookTemplate）。
# 原因：dj-agent 实际下发时（assets.views.dispatch_exporter_install_job）会把主机范围强制
# 收窄到当前操作的单台主机，AutomationTask 自身的主机/清单选择字段对这个场景完全不生效，
# 要求用户先建一个任务纯属多余的一层封装；安装/卸载过程本身固定以 root 执行（需要创建系统
# 用户、写 /usr/lib/systemd/system 等），因此不再需要 run_as_user/run_as_group 配置项，
# 只新增 work_directory（默认 /tmp）供用户按需覆盖执行目录。
# 本次为纯结构调整（不兼容旧数据，沿用 0014 的先例）：旧 install_task/uninstall_task 绑定
# 关系随字段删除一并作废，迁移后需在监控软件仓库为每个软件包重新选择安装/卸载 Playbook。

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0045_add_template_category'),
        ('monitor', '0016_service_run_as_default_dj_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softwarepackage',
            name='install_task',
        ),
        migrations.RemoveField(
            model_name='softwarepackage',
            name='uninstall_task',
        ),
        migrations.AddField(
            model_name='softwarepackage',
            name='install_playbook_template',
            field=models.ForeignKey(blank=True, help_text='安装该软件包使用的 Playbook 模板（需为“软件包安装/卸载专用”分类）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='automation.playbooktemplate'),
        ),
        migrations.AddField(
            model_name='softwarepackage',
            name='uninstall_playbook_template',
            field=models.ForeignKey(blank=True, help_text='卸载该软件包使用的 Playbook 模板（需为“软件包安装/卸载专用”分类）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='automation.playbooktemplate'),
        ),
        migrations.AddField(
            model_name='softwarepackage',
            name='work_directory',
            field=models.CharField(blank=True, default='/tmp', help_text='安装/卸载 Playbook 执行时的工作目录，默认为 /tmp', max_length=255),
        ),
    ]
