# Generated by Django 5.1.4 on 2026-07-21 06:07
# 补上安装/卸载失败后的自动重试能力：改用 AutomationExecutionJob 执行链路后，原基于
# AgentJob 的 runagentconsumer._sync_monitor_target_install_status 自动重试逻辑已失效
# （不再有任何代码创建 action='install_exporter'/'uninstall_exporter' 的 AgentJob），
# 因此需要一个字段记录"这次下发是自动触发还是人工点击重试触发"，用于
# 区分失败后的处理策略（历史上曾用于自动重试链路，现仅保留人工触发语义）。

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0017_remove_softwarepackage_install_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortarget',
            name='last_dispatch_manual',
            field=models.BooleanField(default=False, help_text='最近一次安装/卸载下发是否为人工点击“重试”触发；为 True 时失败后不进入自动重试链'),
        ),
    ]
