# Generated by Django 5.1.4 on 2026-07-24 00:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0046_remove_workflow_entry_node_key'),
        ('assets', '0036_host_webssh_user_preferences'),
        ('monitor', '0018_monitortarget_last_dispatch_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorTargetInstallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('automation_job_id_snapshot', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('automation_job_uuid_snapshot', models.CharField(blank=True, default='', max_length=64)),
                ('action', models.CharField(choices=[('install', 'Install'), ('uninstall', 'Uninstall')], max_length=16)),
                ('trigger_type', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='auto', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('host_id_snapshot', models.IntegerField(blank=True, default=None, null=True)),
                ('host_name_snapshot', models.CharField(blank=True, default='', max_length=128)),
                ('host_ip_snapshot', models.CharField(blank=True, default='', max_length=64)),
                ('exporter_type_snapshot', models.CharField(blank=True, default='', max_length=64)),
                ('summary_message', models.TextField(blank=True, default='')),
                ('stdout_snapshot', models.TextField(blank=True, default='')),
                ('stderr_snapshot', models.TextField(blank=True, default='')),
                ('error_message_snapshot', models.TextField(blank=True, default='')),
                ('result_summary_snapshot', models.JSONField(blank=True, default=dict)),
                ('requested_user_id_snapshot', models.IntegerField(blank=True, default=None, null=True)),
                ('requested_username_snapshot', models.CharField(blank=True, default='', max_length=100)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('automation_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='automation.automationexecutionjob')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.host')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='install_histories', to='monitor.monitortarget')),
            ],
            options={
                'db_table': 'monitor_target_install_history',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='monitortargetinstallhistory',
            index=models.Index(fields=['target', '-id'], name='mon_hist_target_desc_ix'),
        ),
        migrations.AddIndex(
            model_name='monitortargetinstallhistory',
            index=models.Index(fields=['status', '-id'], name='mon_hist_status_desc_ix'),
        ),
        migrations.AddIndex(
            model_name='monitortargetinstallhistory',
            index=models.Index(fields=['automation_job_id_snapshot'], name='monitor_hist_auto_job_id_idx'),
        ),
    ]
