# Generated by Django 5.1.4 on 2026-07-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0019_monitortargetinstallhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitortarget',
            name='last_dispatch_manual',
            field=models.BooleanField(default=False, help_text='最近一次安装/卸载下发是否为人工点击“重试”触发'),
        ),
    ]
