# Generated by Django 5.1.4 on 2026-07-26 10:36

from django.db import migrations


def remove_alert_rule_deploy_config(apps, schema_editor):
    # 告警规则改为只读展示 Prometheus 侧规则，不再本地导出 YAML / 部署 / reload，
    # 这几个仅供部署流程使用的 SysConfig 配置项随之失效，清理避免留下死配置误导用户。
    SysConfig = apps.get_model('sys_config', 'SysConfig')
    SysConfig.objects.filter(key__in=[
        'monitor.prometheus.alert_rules_file_path',
        'sys.monitor.prometheus.alert_rules_file_path',
        'sys.monitor.prometheus.reload_timeout_seconds',
        'sys.monitor.prometheus.deploy_skip_promtool',
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0025_remove_legacy_alert_rules_yaml_config'),
        ('sys_config', '0011_add_automation_websocket_poll_interval_configs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertrule',
            name='group',
        ),
        migrations.DeleteModel(
            name='AlertRuleDeployHistory',
        ),
        migrations.DeleteModel(
            name='AlertRule',
        ),
        migrations.DeleteModel(
            name='AlertRuleGroup',
        ),
        migrations.RunPython(remove_alert_rule_deploy_config, migrations.RunPython.noop),
    ]
