# Generated by Django 5.1.4 on 2026-07-26 12:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0027_remove_promtool_path_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('fingerprint', models.CharField(db_index=True, max_length=40)),
                ('alertname', models.CharField(blank=True, default='', max_length=200)),
                ('severity', models.CharField(blank=True, default='', max_length=32)),
                ('instance', models.CharField(blank=True, default='', max_length=200)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('annotations', models.JSONField(blank=True, default=dict)),
                ('generator_url', models.CharField(blank=True, default='', max_length=500)),
                ('state', models.CharField(choices=[('firing', 'Firing'), ('resolved', 'Resolved')], default='firing', max_length=16)),
                ('started_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField()),
                ('resolved_by_reconciliation', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'monitor_alert_history',
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['state', '-started_at'], name='mon_alert_hist_state_ix'), models.Index(fields=['fingerprint', '-id'], name='mon_alert_hist_fp_ix'), models.Index(fields=['alertname', '-started_at'], name='mon_alert_hist_name_ix')],
            },
        ),
    ]
