# Generated by Django 5.1.4 on 2026-08-22 01:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0049_alerthistory_rule_snapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useralertmediabinding',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='useralertmediabinding',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='useralertmediabinding',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='useralertmediabinding',
            name='remark',
            field=models.TextField(blank=True, default='', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='useralertmediabinding',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
