# Generated by Django 5.1.4 on 2026-08-26 10:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0050_alter_useralertmediabinding_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenSearchCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='集群名称')),
                ('hosts', models.CharField(help_text='形如 https://10.0.0.1:9200，多个用逗号分隔', max_length=512, verbose_name='连接地址')),
                ('username', models.CharField(blank=True, default='', max_length=128, verbose_name='用户名')),
                ('password', models.CharField(blank=True, default='', max_length=512, verbose_name='密码')),
                ('verify_tls', models.BooleanField(default=False, verbose_name='校验 TLS 证书')),
                ('ca_cert', models.TextField(blank=True, default='', verbose_name='CA 证书')),
                ('index_prefix', models.CharField(default='logs', max_length=64, verbose_name='索引前缀')),
                ('request_timeout', models.PositiveIntegerField(default=10, verbose_name='请求超时（秒）')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认集群')),
                ('last_check_time', models.DateTimeField(blank=True, null=True, verbose_name='最近连接测试时间')),
                ('last_check_success', models.BooleanField(blank=True, null=True, verbose_name='最近连接测试结果')),
                ('last_check_message', models.TextField(blank=True, default='', verbose_name='最近连接测试信息')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '日志存储集群',
                'db_table': 'monitor_opensearch_cluster',
                'ordering': ['-is_default', 'id'],
            },
        ),
    ]
