# Generated by Django 5.1.4 on 2026-08-27 01:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0094_remove_applicationlogdefinition_retention_days_and_more'),
        ('monitor', '0051_opensearchcluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogCollectionTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('agent_installed', models.BooleanField(default=False, verbose_name='Fluent Bit 已安装')),
                ('agent_version', models.CharField(blank=True, default='', max_length=64, verbose_name='Fluent Bit 版本')),
                ('runtime_status', models.CharField(choices=[('unknown', '未知'), ('running', '运行中'), ('stopped', '已停止'), ('error', '异常')], default='unknown', max_length=16, verbose_name='运行状态')),
                ('config_fingerprint', models.CharField(blank=True, default='', max_length=64, verbose_name='已下发配置指纹')),
                ('last_applied_time', models.DateTimeField(blank=True, null=True, verbose_name='最近下发时间')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='最近错误')),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='log_collection_target', to='assets.host')),
            ],
            options={
                'verbose_name': '日志采集目标',
                'db_table': 'monitor_log_collection_target',
                'ordering': ['-id'],
            },
        ),
    ]
