# Generated by Django 5.1.4 on 2026-08-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0052_logcollectiontarget'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='softwarepackage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='softwarepackage',
            name='package_format',
            field=models.CharField(choices=[('tar.gz', 'tar.gz'), ('rpm', 'RPM'), ('deb', 'DEB')], default='tar.gz', max_length=16, verbose_name='包格式'),
        ),
        migrations.AddField(
            model_name='softwarepackage',
            name='platform_family',
            field=models.CharField(choices=[('any', '通用 Linux'), ('rhel', 'RHEL/CentOS/Rocky/AlmaLinux'), ('ubuntu', 'Ubuntu'), ('debian', 'Debian')], default='any', max_length=16, verbose_name='适用平台族'),
        ),
        migrations.AddField(
            model_name='softwarepackage',
            name='platform_major',
            field=models.CharField(blank=True, default='', help_text='rpm/deb 必填，例如 RHEL 7/8/9 或 Ubuntu 20/22/24；通用 tar.gz 留空', max_length=16, verbose_name='适用平台主版本'),
        ),
        migrations.AlterUniqueTogether(
            name='softwarepackage',
            unique_together={('name', 'version', 'os', 'arch', 'platform_family', 'platform_major')},
        ),
    ]
