# Generated by Django 5.1.4 on 2026-08-27 03:17

from django.db import migrations, models


def classify_existing_packages(apps, schema_editor):
    SoftwarePackage = apps.get_model('monitor', 'SoftwarePackage')
    SoftwarePackage.objects.filter(name__in=['fluent-bit', 'fluent_bit']).update(package_type='fluent_bit')


def restore_exporter_type(apps, schema_editor):
    SoftwarePackage = apps.get_model('monitor', 'SoftwarePackage')
    SoftwarePackage.objects.filter(package_type='fluent_bit').update(package_type='exporter')


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0053_alter_softwarepackage_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='softwarepackage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='softwarepackage',
            name='package_type',
            field=models.CharField(choices=[('exporter', 'Exporter'), ('fluent_bit', 'Fluent Bit')], default='exporter', max_length=16, verbose_name='软件包类型'),
        ),
        migrations.RunPython(classify_existing_packages, restore_exporter_type),
        migrations.AlterUniqueTogether(
            name='softwarepackage',
            unique_together={('package_type', 'name', 'version', 'os', 'arch', 'platform_family', 'platform_major')},
        ),
    ]
