# Generated by Django 5.1.4 on 2026-08-27 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0054_alter_softwarepackage_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logcollectiontarget',
            name='install_message',
            field=models.TextField(blank=True, default='', verbose_name='安装信息'),
        ),
        migrations.AddField(
            model_name='logcollectiontarget',
            name='install_status',
            field=models.CharField(choices=[('unknown', '未知'), ('pending', '执行中'), ('success', '成功'), ('failed', '失败')], default='unknown', max_length=16, verbose_name='安装状态'),
        ),
        migrations.AddField(
            model_name='logcollectiontarget',
            name='last_dispatch_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logcollectiontarget',
            name='managed_enabled',
            field=models.BooleanField(default=True, verbose_name='纳管启用'),
        ),
        migrations.AddField(
            model_name='logcollectiontarget',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monitortargetinstallhistory',
            name='log_collection_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='install_histories', to='monitor.logcollectiontarget'),
        ),
        migrations.AlterField(
            model_name='monitortargetinstallhistory',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='install_histories', to='monitor.monitortarget'),
        ),
    ]
