# Generated by Django 5.1.4 on 2026-08-27 06:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0058_add_fluent_bit_bootstrap_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogProcessingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='规则名称')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='说明')),
                ('input_format', models.CharField(choices=[('text', '文本'), ('json', 'JSON')], default='text', max_length=16, verbose_name='日志格式')),
                ('multiline_enabled', models.BooleanField(default=False, verbose_name='启用多行合并')),
                ('start_pattern', models.TextField(blank=True, default='', verbose_name='首行正则')),
                ('continuation_pattern', models.TextField(blank=True, default='', verbose_name='续行正则')),
                ('flush_timeout', models.PositiveIntegerField(default=1000, verbose_name='合并超时（毫秒）')),
                ('pipeline_body', models.JSONField(default=dict, verbose_name='OpenSearch Pipeline')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_processing_rules', to='monitor.opensearchcluster', verbose_name='OpenSearch 集群')),
            ],
            options={
                'verbose_name': '日志处理规则',
                'db_table': 'monitor_log_processing_rule',
                'ordering': ['name'],
            },
        ),
    ]
