# Generated by Django 5.1.4 on 2026-08-27 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0096_remove_applicationlogdefinition_ingest_pipeline_and_more'),
        ('monitor', '0059_logprocessingrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='logprocessingrule',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='log_processing_rules', to='assets.application', verbose_name='所属应用'),
        ),
    ]
