# Generated by Django 5.1.4 on 2026-08-27 09:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0060_logprocessingrule_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRetentionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('code', models.SlugField(max_length=32, unique=True, verbose_name='档位编码')),
                ('name', models.CharField(max_length=64, verbose_name='档位名称')),
                ('daily_size_gb', models.FloatField(default=5, verbose_name='每天写入量（GB）')),
                ('retention_days', models.PositiveIntegerField(default=30, verbose_name='保留天数')),
                ('rollover_min_index_age', models.CharField(default='1d', max_length=16, verbose_name='滚动最小时长')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认档位')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '日志保留档位',
                'db_table': 'monitor_log_retention_tier',
                'ordering': ['retention_days', 'id'],
            },
        ),
    ]
