# Generated by Django 5.1.4 on 2026-08-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0062_seed_default_retention_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerthistory',
            name='source',
            field=models.CharField(choices=[('prometheus', 'Prometheus'), ('inspection', '巡检')], db_index=True, default='prometheus', max_length=16),
        ),
    ]
