# Generated by Django 5.1.4 on 2026-08-30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0104_applicationservicelogsetting_collection_mode'),
        ('monitor', '0063_alerthistory_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogCollectionFilterRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='规则名称')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='说明')),
                ('pattern', models.TextField(verbose_name='匹配正则')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='log_collection_filter_rules', to='assets.application', verbose_name='所属应用')),
            ],
            options={
                'verbose_name': '日志采集过滤规则',
                'ordering': ['name'],
                'db_table': 'monitor_log_collection_filter_rule',
            },
        ),
    ]