# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import agent_channel_pb2 as agent__channel__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_channel_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentChannelStub:
    """dj-agent 统一控制/数据通道：与现有 RabbitMQ 心跳/任务模型保持相同的网络方向——
    由 agent 主动拨号连接 backend 并建立一条长连接双向流，backend 在这条流里下发
    各类操作命令（文件传输 / WebSSH 终端 / 自动化任务执行），agent 在本地执行后把
    结果/数据块回传。所有操作以 request_id 在同一条流上多路复用。
    之所以不采用 backend 主动连 agent 的模型，是因为目标主机通常在 NAT/防火墙后面，
    不具备被 backend 直接访问的入站连通性；agent-拨出模型可以复用现有网络策略。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Session = channel.stream_stream(
                '/djadmin.agent.v1.AgentChannel/Session',
                request_serializer=agent__channel__pb2.AgentFrame.SerializeToString,
                response_deserializer=agent__channel__pb2.ServerFrame.FromString,
                _registered_method=True)


class AgentChannelServicer:
    """dj-agent 统一控制/数据通道：与现有 RabbitMQ 心跳/任务模型保持相同的网络方向——
    由 agent 主动拨号连接 backend 并建立一条长连接双向流，backend 在这条流里下发
    各类操作命令（文件传输 / WebSSH 终端 / 自动化任务执行），agent 在本地执行后把
    结果/数据块回传。所有操作以 request_id 在同一条流上多路复用。
    之所以不采用 backend 主动连 agent 的模型，是因为目标主机通常在 NAT/防火墙后面，
    不具备被 backend 直接访问的入站连通性；agent-拨出模型可以复用现有网络策略。
    """

    def Session(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentChannelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Session': grpc.stream_stream_rpc_method_handler(
                    servicer.Session,
                    request_deserializer=agent__channel__pb2.AgentFrame.FromString,
                    response_serializer=agent__channel__pb2.ServerFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'djadmin.agent.v1.AgentChannel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('djadmin.agent.v1.AgentChannel', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentChannel:
    """dj-agent 统一控制/数据通道：与现有 RabbitMQ 心跳/任务模型保持相同的网络方向——
    由 agent 主动拨号连接 backend 并建立一条长连接双向流，backend 在这条流里下发
    各类操作命令（文件传输 / WebSSH 终端 / 自动化任务执行），agent 在本地执行后把
    结果/数据块回传。所有操作以 request_id 在同一条流上多路复用。
    之所以不采用 backend 主动连 agent 的模型，是因为目标主机通常在 NAT/防火墙后面，
    不具备被 backend 直接访问的入站连通性；agent-拨出模型可以复用现有网络策略。
    """

    @staticmethod
    def Session(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/djadmin.agent.v1.AgentChannel/Session',
            agent__channel__pb2.AgentFrame.SerializeToString,
            agent__channel__pb2.ServerFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
